// Secret bindings are intentionally absent from `cloudflare-env.d.ts`, which is
// regenerated by `npm run cf:typegen` from `wrangler.jsonc`. Declaration merging
// keeps the generated file reproducible while typing secrets that are uploaded
// with `wrangler secret put` and never stored in source control.
interface CloudflareEnv {
  CRON_SECRET: string;
}
