import type { Config } from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        // Macquarie University Design Tokens
        mq: {
          primary: 'var(--mq-primary)',
          secondary: 'var(--mq-secondary)',
          red: 'var(--mq-red)',
          'red-bright': 'var(--mq-red-bright)',
          'red-deep': 'var(--mq-red-deep)',
          magenta: 'var(--mq-magenta)',
          purple: 'var(--mq-purple)',
          background: 'var(--mq-background)',
          'background-secondary': 'var(--mq-background-secondary)',
          'background-tertiary': 'var(--mq-background-tertiary)',
          content: 'var(--mq-content)',
          'content-secondary': 'var(--mq-content-secondary)',
          'content-tertiary': 'var(--mq-content-tertiary)',
          border: 'var(--mq-border)',
          'border-secondary': 'var(--mq-border-secondary)',
          focus: 'var(--mq-focus)',
          charcoal: {
            100: 'var(--mq-charcoal-100)',
            200: 'var(--mq-charcoal-200)',
            300: 'var(--mq-charcoal-300)',
            400: 'var(--mq-charcoal-400)',
            500: 'var(--mq-charcoal-500)',
            600: 'var(--mq-charcoal-600)',
            700: 'var(--mq-charcoal-700)',
            800: 'var(--mq-charcoal-800)',
            900: 'var(--mq-charcoal-900)',
          },
          sand: {
            100: 'var(--mq-sand-100)',
            200: 'var(--mq-sand-200)',
            300: 'var(--mq-sand-300)',
            400: 'var(--mq-sand-400)',
            500: 'var(--mq-sand-500)',
          },
          navy: {
            100: 'var(--mq-navy-100)',
            200: 'var(--mq-navy-200)',
            300: 'var(--mq-navy-300)',
            400: 'var(--mq-navy-400)',
            500: 'var(--mq-navy-500)',
            600: 'var(--mq-navy-600)',
            700: 'var(--mq-navy-700)',
            800: 'var(--mq-navy-800)',
            900: 'var(--mq-navy-900)',
          },
          slate: {
            100: 'var(--mq-slate-100)',
            200: 'var(--mq-slate-200)',
            300: 'var(--mq-slate-300)',
            400: 'var(--mq-slate-400)',
            500: 'var(--mq-slate-500)',
          },
        },
        // Macquarie University Brand Colors (legacy)
        macquarie: {
          red: '#A6192E',
          blue: '#002A45',
          gold: '#FFB81C',
        },
      },
      fontFamily: {
        sans: ['var(--font-work-sans)', 'var(--mq-font-primary)'],
        serif: ['var(--font-source-serif-pro)', 'var(--mq-font-secondary)'],
        mq: ['var(--font-work-sans)', 'var(--mq-font-primary)'],
        mqSerif: ['var(--font-source-serif-pro)', 'var(--mq-font-secondary)'],
      },
      fontSize: {
        'mq-xs': 'var(--mq-font-size-xs)',
        'mq-sm': 'var(--mq-font-size-sm)',
        'mq-base': 'var(--mq-font-size-base)',
        'mq-lg': 'var(--mq-font-size-lg)',
        'mq-xl': 'var(--mq-font-size-xl)',
        'mq-2xl': 'var(--mq-font-size-2xl)',
        'mq-3xl': 'var(--mq-font-size-3xl)',
        'mq-4xl': 'var(--mq-font-size-4xl)',
        'mq-5xl': 'var(--mq-font-size-5xl)',
      },
      spacing: {
        'mq-1': 'var(--mq-space-1)',
        'mq-2': 'var(--mq-space-2)',
        'mq-3': 'var(--mq-space-3)',
        'mq-4': 'var(--mq-space-4)',
        'mq-5': 'var(--mq-space-5)',
        'mq-6': 'var(--mq-space-6)',
        'mq-8': 'var(--mq-space-8)',
        'mq-10': 'var(--mq-space-10)',
        'mq-12': 'var(--mq-space-12)',
        'mq-16': 'var(--mq-space-16)',
      },
      borderRadius: {
        'mq-sm': 'var(--mq-radius-sm)',
        'mq': 'var(--mq-radius)',
        'mq-md': 'var(--mq-radius-md)',
        'mq-lg': 'var(--mq-radius-lg)',
        'mq-xl': 'var(--mq-radius-xl)',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'mq-sm': 'var(--mq-shadow-sm)',
        'mq': 'var(--mq-shadow)',
        'mq-md': 'var(--mq-shadow-md)',
        'mq-lg': 'var(--mq-shadow-lg)',
      },
      transitionTimingFunction: {
        'mq-ease': 'cubic-bezier(0.5, 0.5, 0, 1)',
        'mq-snap': 'cubic-bezier(0, 0, 0, 1)',
      },
      transitionDuration: {
        'mq-fast': '0.15s',
        'mq-slow': '0.6s',
        'mq-mid': '0.3s',
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
