const fs = require('fs');
const path = require('path');

// --- 1. Filtered New Data ---
const newBuildings = [
  {
    id: 'EAST3',
    name: 'East 3 Car Park',
    position: [2836, 2466],
    description: 'Multi-storey car park.',
    tags: ['other', 'parking'],
    translationKey: 'building_EAST3_name',
    descriptionKey: 'building_EAST3_desc',
    category: 'other',
    location: { lat: -33.775629, lng: 151.116761, osmId: 14744550 },
  },
  {
    id: 'EAST2',
    name: 'East 2 Car Park',
    position: [2492, 2505],
    description: 'Multi-storey car park.',
    tags: ['other', 'parking'],
    translationKey: 'building_EAST2_name',
    descriptionKey: 'building_EAST2_desc',
    category: 'other',
    location: { lat: -33.774796, lng: 151.116951, osmId: 14744551 },
  },
  {
    id: '75TR',
    name: '75 Talavera Road',
    position: [2119, 2870],
    description: 'Commercial building.',
    tags: ['academic'],
    translationKey: 'building_75TR_name',
    descriptionKey: 'building_75TR_desc',
    address: '75 Talavera Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.774162, lng: 151.118597, osmId: 23716719 },
  },
  {
    id: '3SR',
    name: '3 Science Road',
    position: [1925, 2423],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_3SR_name',
    descriptionKey: 'building_3SR_desc',
    address: '3 Science Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.773295, lng: 151.116613, osmId: 23716725 },
  },
  {
    id: '6FW',
    name: '6 First Walk',
    position: [3099, 1406],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_6FW_name',
    descriptionKey: 'building_6FW_desc',
    address: '6 First Walk',
    category: 'academic',
    location: { lat: -33.775402, lng: 151.112022, osmId: 62060227 },
    levels: 3,
  },
  {
    id: '17MW',
    name: '17 Macquarie Walk',
    position: [3335, 1667],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_17MW_name',
    descriptionKey: 'building_17MW_desc',
    address: '17 Macquarie Walk',
    category: 'academic',
    location: { lat: -33.776217, lng: 151.113178, osmId: 141281548 },
  },
  {
    id: '1MD',
    name: '1 Management Drive',
    position: [1307, 2298],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_1MD_name',
    descriptionKey: 'building_1MD_desc',
    address: '1 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.771631, lng: 151.116079, osmId: 148387966 },
  },
  {
    id: '3MD',
    name: '3 Management Drive',
    position: [1450, 2214],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_3MD_name',
    descriptionKey: 'building_3MD_desc',
    address: '3 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.771921, lng: 151.1157, osmId: 148387968 },
  },
  {
    id: '5MD',
    name: '5 Management Drive',
    position: [1418, 2431],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_5MD_name',
    descriptionKey: 'building_5MD_desc',
    address: '5 Management Drive',
    category: 'academic',
    location: { lat: -33.772023, lng: 151.116669, osmId: 148387969 },
  },
  {
    id: '1EXR',
    name: '1 Executive Road',
    position: [1108, 2259],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_1EXR_name',
    descriptionKey: 'building_1EXR_desc',
    address: '1 Executive Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.771097, lng: 151.115913, osmId: 148387970 },
  },
  {
    id: '2FW',
    name: '2 First Walk',
    position: [2969, 1709],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_2FW_name',
    descriptionKey: 'building_2FW_desc',
    address: '2 First Walk Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775327, lng: 151.113379, osmId: 148389591 },
    levels: 3,
  },
  {
    id: '4FW',
    name: '4 First Walk',
    position: [3025, 1590],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_4FW_name',
    descriptionKey: 'building_4FW_desc',
    address: '4 First Walk',
    category: 'academic',
    location: { lat: -33.77537, lng: 151.112847, osmId: 148389593 },
    levels: 4,
  },
  {
    id: '2LR',
    name: '2 Link Road',
    position: [3400, 42],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_2LR_name',
    descriptionKey: 'building_2LR_desc',
    address: '2 Link Road',
    category: 'academic',
    location: { lat: -33.775009, lng: 151.105921, osmId: 148390207 },
  },
  {
    id: '6LR',
    name: '6 Link Road',
    position: [3363, 151],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_6LR_name',
    descriptionKey: 'building_6LR_desc',
    address: '6 Link Road',
    category: 'academic',
    location: { lat: -33.775009, lng: 151.106411, osmId: 148390210 },
  },
  {
    id: '4LR',
    name: '4 Link Road',
    position: [3485, 83],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_4LR_name',
    descriptionKey: 'building_4LR_desc',
    address: '4 Link Road',
    category: 'academic',
    location: { lat: -33.775259, lng: 151.106101, osmId: 148390211 },
  },
  {
    id: 'DESTINATIO',
    name: 'Destination Orana',
    position: [1810, 3099],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_DESTINATIO_name',
    descriptionKey: 'building_DESTINATIO_desc',
    address: '112-118 Talavera Road Macquarie Park',
    category: 'residential',
    location: { lat: -33.773576, lng: 151.11963, osmId: 286832282 },
    levels: 28,
  },
  {
    id: '3IR',
    name: '3 Innovation Road',
    position: [2540, 2881],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_3IR_name',
    descriptionKey: 'building_3IR_desc',
    address: '3 Innovation Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775235, lng: 151.118627, osmId: 324612872 },
  },
  {
    id: '1IR',
    name: '1 Innovation Road',
    position: [2634, 2996],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_1IR_name',
    descriptionKey: 'building_1IR_desc',
    address: '1 Innovation Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775569, lng: 151.119137, osmId: 324612876 },
  },
  {
    id: '15RPD',
    name: '15 Research Park Drive',
    position: [1742, 2472],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_15RPD_name',
    descriptionKey: 'building_15RPD_desc',
    address: '15 Research Park Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772875, lng: 151.116836, osmId: 459015425 },
  },
  {
    id: 'RONREILLYP',
    name: 'Ron Reilly Pavilion',
    position: [0, 2016],
    description: 'Sports pavilion.',
    tags: ['sports'],
    translationKey: 'building_RONREILLYP_name',
    descriptionKey: 'building_RONREILLYP_desc',
    category: 'sports',
    location: { lat: -33.766262, lng: 151.114914, osmId: 791253931 },
  },
  {
    id: 'M2OPERATIO',
    name: 'M2 Operations Centre',
    position: [199, 2350],
    description: 'Operations Centre for M2 Motorway.',
    tags: ['other'],
    translationKey: 'building_M2OPERATIO_name',
    descriptionKey: 'building_M2OPERATIO_desc',
    category: 'other',
    location: { lat: -33.768879, lng: 151.11636, osmId: 791276982 },
  },
  {
    id: 'ADELAIDE',
    name: 'Adelaide',
    position: [4813, 1526],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_ADELAIDE_name',
    descriptionKey: 'building_ADELAIDE_desc',
    category: 'residential',
    location: { lat: -33.779828, lng: 151.112484, osmId: 967523408 },
  },
  {
    id: 'DARWIN',
    name: 'Darwin',
    position: [4893, 1618],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_DARWIN_name',
    descriptionKey: 'building_DARWIN_desc',
    category: 'residential',
    location: { lat: -33.780107, lng: 151.112889, osmId: 967523409 },
  },
  {
    id: 'PERTH',
    name: 'Perth',
    position: [4949, 1453],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_PERTH_name',
    descriptionKey: 'building_PERTH_desc',
    category: 'residential',
    location: { lat: -33.780108, lng: 151.112151, osmId: 967523414 },
  },
  {
    id: 'BLOCKA',
    name: 'Block A (Herring Road)',
    position: [4931, 1937],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKA_name',
    descriptionKey: 'building_BLOCKA_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780472, lng: 151.114311, osmId: 967530686 },
  },
  {
    id: 'BLOCKB',
    name: 'Block B (Herring Road)',
    position: [4873, 1904],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKB_name',
    descriptionKey: 'building_BLOCKB_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780298, lng: 151.114168, osmId: 967533739 },
  },
  {
    id: 'BLOCKC',
    name: 'Block C (Herring Road)',
    position: [4814, 1873],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKC_name',
    descriptionKey: 'building_BLOCKC_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780121, lng: 151.114029, osmId: 967533740 },
  },
  {
    id: 'BLOCKD',
    name: 'Block D (Herring Road)',
    position: [4774, 1832],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKD_name',
    descriptionKey: 'building_BLOCKD_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779986, lng: 151.113847, osmId: 967533741 },
  },
  {
    id: 'BLOCKE',
    name: 'Block E (Herring Road)',
    position: [4737, 1790],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKE_name',
    descriptionKey: 'building_BLOCKE_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779857, lng: 151.113663, osmId: 967533742 },
  },
  {
    id: 'BLOCKF',
    name: 'Block F (Herring Road)',
    position: [4824, 1769],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKF_name',
    descriptionKey: 'building_BLOCKF_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780059, lng: 151.113567, osmId: 967533743 },
  },
  {
    id: 'VILLAS',
    name: 'The Villas',
    position: [4660, 1616],
    description: 'Residential villas.',
    tags: ['residential'],
    translationKey: 'building_VILLAS_name',
    descriptionKey: 'building_VILLAS_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779518, lng: 151.11289, osmId: 967533744 },
  },
  {
    id: 'HOLIDAYINN',
    name: 'Holiday Inn Express',
    position: [4660, 3219],
    description: 'Holiday Inn Express Sydney Macquarie Park.',
    tags: ['other', 'hotel'],
    translationKey: 'building_HOLIDAYINN_name',
    descriptionKey: 'building_HOLIDAYINN_desc',
    category: 'other',
    location: { lat: -33.780869, lng: 151.120041, osmId: 1108110442 },
  },
  {
    id: 'MACRESIDEN',
    name: 'Mac Residences',
    position: [4920, 2164],
    description: 'Residential building.',
    tags: ['residential'],
    translationKey: 'building_MACRESIDEN_name',
    descriptionKey: 'building_MACRESIDEN_desc',
    category: 'residential',
    location: { lat: -33.780634, lng: 151.115322, osmId: 1161574505 },
  },
  {
    id: '6MD',
    name: '6 Management Drive',
    position: [1503, 2297],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_6MD_name',
    descriptionKey: 'building_6MD_desc',
    address: '6 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772124, lng: 151.116066, osmId: 1192234862 },
  },
  {
    id: '7MD',
    name: '7 Management Drive',
    position: [1584, 2211],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_7MD_name',
    descriptionKey: 'building_7MD_desc',
    address: '7 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772257, lng: 151.115679, osmId: 1192234863 },
  },
  {
    id: '12MW',
    name: '12 Macquarie Walk',
    position: [2846, 1875],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_12MW_name',
    descriptionKey: 'building_12MW_desc',
    address: '12 Macquarie Walk Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775158, lng: 151.114124, osmId: 1192234871 },
  },
  {
    id: '18ER',
    name: '18 Eastern Road',
    position: [1824, 2221],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_18ER_name',
    descriptionKey: 'building_18ER_desc',
    address: '18 Eastern Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772871, lng: 151.115713, osmId: 1192257351 },
  },
  {
    id: '2WW',
    name: "2 Wally's Walk",
    position: [2216, 2560],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_2WW_name',
    descriptionKey: 'building_2WW_desc',
    address: "2 Wally's Walk Macquarie Park NSW",
    category: 'academic',
    location: { lat: -33.774145, lng: 151.117209, osmId: 1303624872 },
  },
  {
    id: 'REDDYEXPRE',
    name: 'Reddy Express',
    position: [3483, 0],
    description: 'Convenience store.',
    tags: ['food', 'retail'],
    translationKey: 'building_REDDYEXPRE_name',
    descriptionKey: 'building_REDDYEXPRE_desc',
    category: 'food',
    location: { lat: -33.775123, lng: 151.105399, osmId: 1444070791 },
  },
];

// --- 2. Update Buildings TS ---
const buildingsPath = path.join(process.cwd(), 'lib/map/buildings.ts');
let buildingsContent = fs.readFileSync(buildingsPath, 'utf8');

// Find insertion point (before the end of the array)
const closingBracketIndex = buildingsContent.lastIndexOf('];');
if (closingBracketIndex === -1) {
  console.error('Could not find closing bracket of buildings array');
  process.exit(1);
}

// Generate TS code
const newBuildingsCode = newBuildings
  .map((b) => {
    const addressLine = b.address ? `    address: ${JSON.stringify(b.address)},` : '';
    const levelsLine = b.levels ? `\n    levels: ${b.levels}` : '';

    return `  {
    id: '${b.id}',
    name: ${JSON.stringify(b.name)},
    position: [${b.position[0]}, ${b.position[1]}],
    description: ${JSON.stringify(b.description)},
    tags: ${JSON.stringify(b.tags)},
    translationKey: '${b.translationKey}',
    descriptionKey: '${b.descriptionKey}',
${addressLine}
    category: '${b.category}',
    location: { lat: ${b.location.lat}, lng: ${b.location.lng}, osmId: ${b.location.osmId} }${levelsLine}
  }`;
  })
  .join(',\n');

// Insert
const updatedBuildingsContent =
  buildingsContent.slice(0, closingBracketIndex) +
  '  // --- NEW BUILDINGS (Imported from OSM) ---\n' +
  newBuildingsCode +
  '\n' +
  buildingsContent.slice(closingBracketIndex);

fs.writeFileSync(buildingsPath, updatedBuildingsContent);
console.log('Updated lib/map/buildings.ts');

// --- 3. Update Translations JSON ---
const translationsPath = path.join(process.cwd(), 'locales/en/translations.json');
const translations = JSON.parse(fs.readFileSync(translationsPath, 'utf8'));

newBuildings.forEach((b) => {
  translations[b.translationKey] = b.name;
  translations[b.descriptionKey] = b.description;
});

fs.writeFileSync(translationsPath, JSON.stringify(translations, null, 2));
console.log('Updated locales/en/translations.json');
