#!/usr/bin/env python3
"""Generate privacy patches for remaining locales: fi, hu, ne, nl, no, pl, pt, ro, si, sv, uk.
Run: python3 tools/generate-privacy-patches-2.py
"""
import json, os

PATCHES_DIR = os.path.join(os.path.dirname(__file__), "privacy-patches")
os.makedirs(PATCHES_DIR, exist_ok=True)

T = {}

T["fi"] = {
  "privacy_back_to": "Takaisin sovellukseen {{appName}}",
  "privacy_title": "Tietosuojakäytäntö",
  "privacy_last_updated": "Päivitetty viimeksi: 16. helmikuuta 2026 (AEDT)",
  "privacy_s1_title": "Tarkoitus ja soveltamisala",
  "privacy_s1_p1": "Tämä tietosuojakäytäntö selittää, miten {{appName}} kerää, säilyttää, käyttää ja luovuttaa henkilötietoja käyttäessäsi palveluamme.",
  "privacy_s1_p2": "{{appName}} on kampustyökalu, joka on kehitetty {{uniName}}-yliopiston opiskelijoille. Tämä käytäntö koskee kaikkia palvelun käyttäjiä.",
  "privacy_s2_title": "Mitä henkilötietoja keräämme",
  "privacy_s2_a_title": "A) Tili- ja identiteettitiedot",
  "privacy_s2_a_li1": "Koko nimi (tai näyttönimi)",
  "privacy_s2_a_li2": "Sähköpostiosoite",
  "privacy_s2_a_li3": "Salasana (tallennettu kryptografisena tiivisteenä — emme koskaan tallenna salasanaasi selkotekstinä)",
  "privacy_s2_a_li4": "Opiskelijanumero, tutkinto-ohjelma ja opiskeluvuosi",
  "privacy_s2_a_li5": "Tilin asetukset ja mieltymykset",
  "privacy_s2_a_li6": "Profiilikuva (jos ladattu)",
  "privacy_s2_b_title": "B) Monivaiheisen todennuksen tiedot",
  "privacy_s2_b_li1": "TOTP-rekisteröintisalaisuudet, tallennettu salattuna ja Cache-Control: no-store -otsikolla",
  "privacy_s2_b_li2": "WebAuthn/passkey-tunnistetiedot ja julkiset avaimet (biometrisiä tietoja ei tallenneta)",
  "privacy_s2_c_title": "C) Käyttö- ja laitetiedot",
  "privacy_s2_c_li1": "Laitetyyppi, selain, käyttöjärjestelmä, kieliasetus",
  "privacy_s2_c_li2": "IP-osoite (turvallisuuden nopeusrajoitusta ja väärinkäytön estoa varten)",
  "privacy_s2_c_li3": "Aikaleimat ja peruspyyntöjen metatiedot",
  "privacy_s2_c_li4": "Sovellusvirhelokit ja suorituskykydiagnostiikka (kerätty Sentryn kautta tekstin peittämisellä ja median estolla)",
  "privacy_s2_d_title": "D) Oppimis- ja lukujärjestyssisältö (käyttäjän tarjoama)",
  "privacy_s2_d_li1": "Opintojaksot, aikataulut, määräajat, muistutukset ja tehtävät, jotka luot",
  "privacy_s2_d_li2": "Kalenteritapahtumat ja syöteasetukset",
  "privacy_s2_e_title": "E) Sijaintitiedot (vain luvallasi)",
  "privacy_s2_e_li1": "GPS-koordinaatit kampuskarttaa ja navigointia varten — kerätään vain kun myönnät sijaintiluvan",
  "privacy_s2_e_li2": "Sijaintitiedot käsitellään paikallisesti laitteessasi eikä niitä tallenneta palvelimillemme",
  "privacy_s2_e_li3": "Voit peruuttaa sijaintiluvan milloin tahansa laitteen tai selaimen asetuksista",
  "privacy_s2_f_title": "F) Evästeet ja istuntotiedot",
  "privacy_s2_f_li1": "Istuntoevästeet (välttämättömät todennusta varten)",
  "privacy_s2_f_li2": "Turvallisuusevästeet (CSRF-suojaus)",
  "privacy_s2_f_li3": "Teema- ja kieliasetusevästeet",
  "privacy_s2_footer": "Emme kerää tarkoituksellisesti arkaluonteisia tietoja Privacy Actin mukaisesti, ellei se ole välttämätöntä ja nimenomaisella suostumuksellasi.",
  "privacy_s3_p1": "Keräämme tietoja:",
  "privacy_s3_li1": "Suoraan sinulta — kun rekisteröidyt, päivität profiiliasi, luot sisältöä tai muutat asetuksia",
  "privacy_s3_li2": "Automaattisesti — istuntoevästeiden, palvelinlokien ja virheenvalvonnan kautta",
  "privacy_s3_footer": "APP 5:n mukaisesti ryhdymme kohtuullisiin toimiin ilmoittaaksemme sinulle keräyshetkellä tai sitä ennen.",
  "privacy_s4_p1": "Käytämme henkilötietoja seuraaviin tarkoituksiin:",
  "privacy_s4_li1": "Palvelun tarjoaminen ja toiminta (todennus, ydintoiminnot, tietojen synkronointi)",
  "privacy_s4_li2": "Kokemuksesi personointi (asetukset, tallennetut mieltymykset, teema)",
  "privacy_s4_li3": "Turvallisuuden ylläpitäminen (petosten esto, väärinkäytön havaitseminen, nopeusrajoitus)",
  "privacy_s4_li4": "Suorituskyvyn ja luotettavuuden parantaminen (virheseuranta, diagnostiikka)",
  "privacy_s4_li5": "Viestintä kanssasi (palveluviestit, tärkeät tietoturvapäivitykset)",
  "privacy_s4_li6": "Lakisääteisten velvoitteiden täyttäminen ja ehtojemme noudattaminen",
  "privacy_s4_footer": "Keräämme vain tietoja, jotka ovat kohtuullisesti tarpeen toimintojamme varten.",
  "privacy_s5_p1": "Voimme luovuttaa henkilötietoja:",
  "privacy_s5_li1": "Palveluntarjoajille, jotka auttavat palvelun toiminnassa (katso osio 6)",
  "privacy_s5_li2": "Viranomaisille lain, oikeuden määräyksen tai vakavien uhkien estämiseksi",
  "privacy_s5_li3": "Liiketoiminnan siirrot (esim. yrityskauppa tai fuusio) asianmukaisella suojalla",
  "privacy_s5_footer": "Emme myy henkilötietoja.",
  "privacy_s6_p1": "Jotkut palveluntarjoajat voivat tallentaa tai käsitellä tietoja Australian ulkopuolella. Ryhdymme kohtuullisiin toimiin APPs-yhteensopivuuden varmistamiseksi.",
  "privacy_s6_table_h2": "Tarkoitus",
  "privacy_s6_table_h3": "Tietoalue",
  "privacy_s6_table_r1_c2": "Todennus, tietokanta, tiedostojen tallennus",
  "privacy_s6_table_r1_c3": "Projektikohtainen (AU/US/EU)",
  "privacy_s6_table_r2_c2": "Isännöinti ja CDN",
  "privacy_s6_table_r2_c3": "Globaali edge (US ensisijainen)",
  "privacy_s6_table_r3_c2": "Virheenvalvonta ja suorituskykydiagnostiikka",
  "privacy_s6_table_r4_c2": "Navigointireititys (vain palvelinpuoli)",
  "privacy_s6_table_r4_c3": "EU (Saksa)",
  "privacy_s7_p1": "Ryhdymme kohtuullisiin toimiin henkilötietojen suojaamiseksi. Turvatoimemme sisältävät:",
  "privacy_s7_li1": "Salaus siirrossa (TLS/HTTPS HSTS:n kautta)",
  "privacy_s7_li2": "Salaus levossa tietokannalle ja tiedostoille",
  "privacy_s7_li3": "Turvallinen salasanan tiivistäminen",
  "privacy_s7_li4": "Monivaiheisen todennuksen vaihtoehdot (TOTP, WebAuthn/passkeys)",
  "privacy_s7_li5": "Roolipohjainen pääsynhallinta ja vähimmäisoikeuksien palveluavaimet",
  "privacy_s7_li6": "Nopeusrajoitus ja brute-force-suojaus todennuspäätepisteissä",
  "privacy_s7_li7": "Content Security Policy (CSP) nonce-arvoilla XSS:n estämiseksi",
  "privacy_s7_li8": "Service worker -turvallisuus: API-reittejä ei välimuistita; kaikki välimuistit tyhjennetään uloskirjautumisen yhteydessä",
  "privacy_s7_li9": "Automaattinen istunnon vanheneminen ja turvallinen evästeiden käsittely",
  "privacy_s7_footer": "Mikään elektroninen siirto- tai tallennusmenetelmä ei ole 100% turvallinen.",
  "privacy_s8_p1": "Säilytämme henkilötietoja vain niin kauan kuin on tarpeen:",
  "privacy_s8_li1": "Palvelun tarjoamiseksi ja tilisi ylläpitämiseksi",
  "privacy_s8_li2": "Lakisääteisten velvoitteiden täyttämiseksi",
  "privacy_s8_li3": "Riitojen ratkaisemiseksi ja ehtojemme noudattamiseksi",
  "privacy_s8_li4": "Turvallisuuden ja tarkastuksen eheyden ylläpitämiseksi",
  "privacy_s8_footer": "Kun tietojasi ei enää tarvita, ryhdymme kohtuullisiin toimiin niiden poistamiseksi tai anonymisoimiseksi.",
  "privacy_s9_p1": "Käytämme evästeitä ja vastaavia teknologioita:",
  "privacy_s9_li1": "Pitääksemme sinut kirjautuneena ja ylläpitääksemme turvallisia istuntoja",
  "privacy_s9_li2": "Muistaaksemme asetuksesi (teema, kieli, saavutettavuusasetukset)",
  "privacy_s9_li3": "Valvoaksemme sovellusvirheitä ja suorituskykyä (Sentryn kautta)",
  "privacy_s9_footer": "Emme käytä kolmannen osapuolen mainosevästeitä tai käyttäytymisen seurantaa.",
  "privacy_s10_p1": "APPs 12 ja 13 mukaisesti voit pyytää pääsyä henkilötietoihisi ja pyytää korjauksia.",
  "privacy_s10_p2_part1": "Voit tarkastella ja päivittää tietojasi suoraan",
  "privacy_s10_p2_part2": "ja",
  "privacy_s10_p2_part3": ". Muita pyyntöjä varten ota yhteyttä osoitteeseen",
  "privacy_s10_p2_part4": ". Saatamme joutua vahvistamaan henkilöllisyytesi ennen pyyntöjen käsittelyä.",
  "privacy_s11_p1_part1": "Jos uskot, että olemme rikkoneet Australian Privacy Principles -periaatteita, voit tehdä valituksen lähettämällä sähköpostia osoitteeseen",
  "privacy_s11_p1_part2": "huolesi yksityiskohtien kanssa.",
  "privacy_s11_p2_part1": "Vahvistamme valituksesi ja vastaamme kohtuullisessa ajassa (yleensä 30 päivän kuluessa). Jos et ole tyytyväinen, voit valittaa",
  "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "Jos Privacy Act 1988 koskee meitä ja tapahtuu tietomurto, joka todennäköisesti aiheuttaa vakavaa haittaa, ilmoitamme asianomaisille ja OAIC:lle",
  "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} on suunniteltu {{uniName}}-yliopiston opiskelijoille. Emme tietoisesti kerää henkilötietoja alle 16-vuotiailta lapsilta.",
  "privacy_s14_p1": "Voimme päivittää tätä käytäntöä ajoittain. Olennaisista muutoksista ilmoitetaan sovelluksen sisäisellä ilmoituksella."
}

T["hu"] = {
  "privacy_back_to": "Vissza a(z) {{appName}} alkalmazáshoz",
  "privacy_title": "Adatvédelmi irányelvek",
  "privacy_last_updated": "Utolsó frissítés: 2026. február 16. (AEDT)",
  "privacy_s1_title": "Cél és hatály",
  "privacy_s1_p1": "Ez az adatvédelmi irányelv ismerteti, hogyan gyűjti, tárolja, használja és közli a(z) {{appName}} a személyes adatokat a szolgáltatásunk használatakor.",
  "privacy_s1_p2": "A(z) {{appName}} a(z) {{uniName}} hallgatói számára fejlesztett kampusz segédeszköz. Ez az irányelv a Szolgáltatás minden felhasználójára vonatkozik.",
  "privacy_s2_title": "Milyen személyes adatokat gyűjtünk",
  "privacy_s2_a_title": "A) Fiók- és személyazonossági adatok",
  "privacy_s2_a_li1": "Teljes név (vagy megjelenítendő név)",
  "privacy_s2_a_li2": "E-mail cím",
  "privacy_s2_a_li3": "Jelszó (kriptográfiai hash-ként tárolva — soha nem tároljuk a jelszavát egyszerű szövegként)",
  "privacy_s2_a_li4": "Hallgatói azonosító, szak és tanév",
  "privacy_s2_a_li5": "Fiókbeállítások és preferenciák",
  "privacy_s2_a_li6": "Profilkép (ha feltöltve)",
  "privacy_s2_b_title": "B) Többtényezős hitelesítési adatok",
  "privacy_s2_b_li1": "TOTP regisztrációs titkok, titkosítva tárolva és Cache-Control: no-store fejléccel kiszolgálva",
  "privacy_s2_b_li2": "WebAuthn/passkey hitelesítő adatok és nyilvános kulcsok (biometrikus adatot nem tárolunk)",
  "privacy_s2_c_title": "C) Használati és eszközadatok",
  "privacy_s2_c_li1": "Eszköztípus, böngésző, operációs rendszer, nyelvi beállítás",
  "privacy_s2_c_li2": "IP-cím (biztonsági sebességkorlátozáshoz és visszaélés-megelőzéshez)",
  "privacy_s2_c_li3": "Időbélyegek és alapvető kérés-metaadatok",
  "privacy_s2_c_li4": "Alkalmazás-hibanaplók és teljesítménydiagnosztika (Sentry-n keresztül gyűjtve, szövegmaszkolással és médiablokkolással)",
  "privacy_s2_d_title": "D) Tanulási és órarendi tartalom (felhasználó által megadott)",
  "privacy_s2_d_li1": "Tantárgyak/kurzusok, órarendek, határidők, emlékeztetők és feladatok",
  "privacy_s2_d_li2": "Naptáresemények és hírfolyam-beállítások",
  "privacy_s2_e_title": "E) Helyadatok (csak az Ön engedélyével)",
  "privacy_s2_e_li1": "GPS-koordináták a kampusztérképhez és navigációs funkciókhoz — csak a helymeghatározási engedély megadásakor gyűjtve",
  "privacy_s2_e_li2": "A helyadatok helyileg kerülnek feldolgozásra az eszközén, és nem tároljuk a szervereinken",
  "privacy_s2_e_li3": "A helymeghatározási engedélyt bármikor visszavonhatja az eszköz vagy böngésző beállításaiban",
  "privacy_s2_f_title": "F) Sütik és munkamenet-adatok",
  "privacy_s2_f_li1": "Munkamenet-sütik (feltétlenül szükségesek a hitelesítéshez)",
  "privacy_s2_f_li2": "Biztonsági sütik (CSRF-védelem)",
  "privacy_s2_f_li3": "Téma- és nyelvi beállítás sütik",
  "privacy_s2_footer": "Szándékosan nem gyűjtünk érzékeny információkat a Privacy Act értelmében, kivéve ha feltétlenül szükséges és az Ön kifejezett hozzájárulásával.",
  "privacy_s3_p1": "Információkat gyűjtünk:",
  "privacy_s3_li1": "Közvetlenül Öntől — regisztrációkor, profil frissítésekor, tartalom létrehozásakor vagy beállítások módosításakor",
  "privacy_s3_li2": "Automatikusan — munkamenet-sütikön, szervernaplókon és hibafelügyeleten keresztül",
  "privacy_s3_footer": "Az APP 5 értelmében ésszerű lépéseket teszünk az értesítésére a gyűjtés időpontjában vagy azt megelőzően.",
  "privacy_s4_p1": "Személyes adatokat a következőkre használunk:",
  "privacy_s4_li1": "A Szolgáltatás biztosítása és működtetése (hitelesítés, alapfunkciók, adatszinkronizálás)",
  "privacy_s4_li2": "Az Ön élményének személyre szabása (beállítások, mentett preferenciák, téma)",
  "privacy_s4_li3": "Biztonság fenntartása (csalásmegelőzés, visszaélés-észlelés, sebességkorlátozás)",
  "privacy_s4_li4": "Teljesítmény és megbízhatóság javítása (hibakövetés, diagnosztika)",
  "privacy_s4_li5": "Kommunikáció Önnel (szolgáltatási üzenetek, fontos biztonsági frissítések)",
  "privacy_s4_li6": "Jogi kötelezettségek teljesítése és feltételeink érvényesítése",
  "privacy_s4_footer": "Csak olyan információkat gyűjtünk, amelyek ésszerűen szükségesek funkcióinkhoz.",
  "privacy_s5_p1": "Személyes adatokat közölhetünk:",
  "privacy_s5_li1": "Szolgáltatókkal, akik segítenek a Szolgáltatás működtetésében (részletekért lásd a 6. részt)",
  "privacy_s5_li2": "Hatóságokkal, ha jogszabály, bírósági végzés követeli meg, vagy komoly fenyegetések megelőzéséhez",
  "privacy_s5_li3": "Üzleti átruházásokkal (pl. felvásárlás vagy egyesülés) megfelelő védelemmel",
  "privacy_s5_footer": "Nem adjuk el a személyes adatokat.",
  "privacy_s6_p1": "Egyes szolgáltatók Ausztrálián kívül tárolhatják vagy dolgozhatják fel az adatokat. Ésszerű lépéseket teszünk az APPs-nak való megfelelés biztosítására.",
  "privacy_s6_table_h2": "Cél",
  "privacy_s6_table_h3": "Adatrégió",
  "privacy_s6_table_r1_c2": "Hitelesítés, adatbázis, fájltárolás",
  "privacy_s6_table_r1_c3": "Projektenkénti konfiguráció (AU/US/EU)",
  "privacy_s6_table_r2_c2": "Tárhelyszolgáltatás és CDN",
  "privacy_s6_table_r2_c3": "Globális edge (US elsődleges)",
  "privacy_s6_table_r3_c2": "Hibafelügyelet és teljesítménydiagnosztika",
  "privacy_s6_table_r4_c2": "Navigációs útválasztás (csak szerveroldali)",
  "privacy_s6_table_r4_c3": "EU (Németország)",
  "privacy_s7_p1": "Ésszerű lépéseket teszünk a személyes adatok védelmére. Biztonsági intézkedéseink:",
  "privacy_s7_li1": "Titkosítás átvitel közben (TLS/HTTPS HSTS-en keresztül)",
  "privacy_s7_li2": "Titkosítás nyugalmi állapotban adatbázishoz és fájlokhoz",
  "privacy_s7_li3": "Biztonságos jelszó-hash-elés",
  "privacy_s7_li4": "Többtényezős hitelesítési lehetőségek (TOTP, WebAuthn/passkeys)",
  "privacy_s7_li5": "Szerepalapú hozzáférés-szabályozás és minimális jogosultságú szolgáltatáskulcsok",
  "privacy_s7_li6": "Sebességkorlátozás és brute-force védelem hitelesítési végpontokon",
  "privacy_s7_li7": "Content Security Policy (CSP) nonce-okkal az XSS megelőzésére",
  "privacy_s7_li8": "Service worker biztonság: API útvonalak soha nem kerülnek gyorsítótárba; kijelentkezéskor minden gyorsítótár törlődik",
  "privacy_s7_li9": "Automatikus munkamenet-lejárat és biztonságos sütikezelés",
  "privacy_s7_footer": "Egyetlen elektronikus átviteli vagy tárolási módszer sem 100%-ban biztonságos.",
  "privacy_s8_p1": "Személyes adatokat csak a szükséges ideig őrizzük meg:",
  "privacy_s8_li1": "A Szolgáltatás biztosításához és fiókja fenntartásához",
  "privacy_s8_li2": "Jogi kötelezettségek teljesítéséhez",
  "privacy_s8_li3": "Viták rendezéséhez és feltételeink érvényesítéséhez",
  "privacy_s8_li4": "Biztonság és ellenőrzési integritás fenntartásához",
  "privacy_s8_footer": "Amikor adataira már nincs szükség, ésszerű lépéseket teszünk törlésükre vagy anonimizálásukra.",
  "privacy_s9_p1": "Sütiket és hasonló technológiákat használunk:",
  "privacy_s9_li1": "Bejelentkezve tartásához és biztonságos munkamenetek fenntartásához",
  "privacy_s9_li2": "Beállításai megjegyzéséhez (téma, nyelv, akadálymentesítési beállítások)",
  "privacy_s9_li3": "Alkalmazáshibák és teljesítmény figyeléséhez (Sentry-n keresztül)",
  "privacy_s9_footer": "Nem használunk harmadik féltől származó reklámszütiket vagy viselkedéskövetést.",
  "privacy_s10_p1": "Az APPs 12 és 13 értelmében hozzáférést kérhet személyes adataihoz és javítást kérhet.",
  "privacy_s10_p2_part1": "Adatai nagy részét közvetlenül megtekintheti és frissítheti a",
  "privacy_s10_p2_part2": "és",
  "privacy_s10_p2_part3": " felületen. Egyéb kérésekhez lépjen kapcsolatba velünk a",
  "privacy_s10_p2_part4": " címen. Szükség lehet személyazonosságának igazolására a kérések teljesítése előtt.",
  "privacy_s11_p1_part1": "Ha úgy véli, hogy megsértettük az Australian Privacy Principles-t, panaszt tehet a",
  "privacy_s11_p1_part2": "e-mail címre küldve, a probléma részleteivel.",
  "privacy_s11_p2_part1": "Panaszát igazoljuk és ésszerű időn belül válaszolunk (általában 30 napon belül). Ha nem elégedett, panaszt tehet a",
  "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "Ha a Privacy Act 1988 vonatkozik ránk, és olyan adatszivárgás történik, amely valószínűleg komoly kárt okoz, értesítjük az érintetteket és az OAIC-t a",
  "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "A(z) {{appName}} a(z) {{uniName}} egyetemi hallgatói számára készült. Nem gyűjtünk tudatosan személyes adatokat 16 év alatti gyermekektől.",
  "privacy_s14_p1": "Ezt az irányelvet időről időre frissíthetjük. Lényeges változásokról alkalmazáson belüli értesítéssel tájékoztatunk."
}

T["nl"] = {
  "privacy_back_to": "Terug naar {{appName}}",
  "privacy_title": "Privacybeleid",
  "privacy_last_updated": "Laatst bijgewerkt: 16 februari 2026 (AEDT)",
  "privacy_s1_title": "Doel en reikwijdte",
  "privacy_s1_p1": "Dit privacybeleid legt uit hoe {{appName}} persoonsgegevens verzamelt, bewaart, gebruikt en openbaar maakt wanneer u onze webapplicatie gebruikt.",
  "privacy_s1_p2": "{{appName}} is een campustool ontwikkeld voor studenten van {{uniName}}. Dit beleid is van toepassing op alle gebruikers van de Dienst.",
  "privacy_s2_title": "Welke persoonsgegevens we verzamelen",
  "privacy_s2_a_title": "A) Account- en identiteitsgegevens",
  "privacy_s2_a_li1": "Volledige naam (of weergavenaam)",
  "privacy_s2_a_li2": "E-mailadres",
  "privacy_s2_a_li3": "Wachtwoord (opgeslagen als cryptografische hash — we slaan uw wachtwoord nooit op als platte tekst)",
  "privacy_s2_a_li4": "Studentnummer, opleiding en studiejaar",
  "privacy_s2_a_li5": "Accountvoorkeuren en -instellingen",
  "privacy_s2_a_li6": "Profielafbeelding (indien geüpload)",
  "privacy_s2_b_title": "B) Multifactor-authenticatiegegevens",
  "privacy_s2_b_li1": "TOTP-registratiegeheimen, versleuteld opgeslagen en geserveerd met Cache-Control: no-store",
  "privacy_s2_b_li2": "WebAuthn/passkey-referentie-ID's en openbare sleutels (geen biometrische gegevens worden opgeslagen)",
  "privacy_s2_c_title": "C) Gebruiks- en apparaatgegevens",
  "privacy_s2_c_li1": "Apparaattype, browser, besturingssysteem, taalvoorkeur",
  "privacy_s2_c_li2": "IP-adres (voor beveiligingssnelheidsbeperking en misbruikpreventie)",
  "privacy_s2_c_li3": "Tijdstempels en basis verzoekmetadata",
  "privacy_s2_c_li4": "Applicatiefoutlogboeken en prestatiediagnostiek (verzameld via Sentry met tekstmaskering en mediablokkering)",
  "privacy_s2_d_title": "D) Leer- en roosterinhoud (door gebruiker verstrekt)",
  "privacy_s2_d_li1": "Vakken/cursussen, roosters, deadlines, herinneringen en taken die u aanmaakt",
  "privacy_s2_d_li2": "Agendagebeurtennissen en feedvoorkeuren",
  "privacy_s2_e_title": "E) Locatiegegevens (alleen met uw toestemming)",
  "privacy_s2_e_li1": "GPS-coördinaten voor campuskaart en navigatiefuncties — alleen verzameld als u locatietoestemming verleent",
  "privacy_s2_e_li2": "Locatiegegevens worden lokaal op uw apparaat verwerkt en niet op onze servers opgeslagen",
  "privacy_s2_e_li3": "U kunt locatietoestemming op elk moment intrekken via uw apparaat- of browserinstellingen",
  "privacy_s2_f_title": "F) Cookies en sessiegegevens",
  "privacy_s2_f_li1": "Sessiecookies (strikt noodzakelijk voor authenticatie)",
  "privacy_s2_f_li2": "Beveiligingscookies (CSRF-bescherming)",
  "privacy_s2_f_li3": "Thema- en taalvoorkeurcookies",
  "privacy_s2_footer": "We verzamelen niet opzettelijk gevoelige informatie zoals gedefinieerd in de Privacy Act, tenzij strikt noodzakelijk en met uw uitdrukkelijke toestemming.",
  "privacy_s3_p1": "We verzamelen informatie:",
  "privacy_s3_li1": "Rechtstreeks van u — wanneer u zich registreert, uw profiel bijwerkt, inhoud maakt of instellingen aanpast",
  "privacy_s3_li2": "Automatisch — via sessiecookies, serverlogboeken en foutbewaking",
  "privacy_s3_footer": "In overeenstemming met APP 5 nemen we redelijke stappen om u op of vóór het moment van verzameling te informeren.",
  "privacy_s4_p1": "We gebruiken persoonsgegevens om:",
  "privacy_s4_li1": "De Dienst te leveren en te beheren (authenticatie, kernfuncties, datasynchronisatie)",
  "privacy_s4_li2": "Uw ervaring te personaliseren (voorkeuren, opgeslagen instellingen, thema)",
  "privacy_s4_li3": "Beveiliging te handhaven (fraudepreventie, misbruikdetectie, snelheidsbeperking)",
  "privacy_s4_li4": "Prestaties en betrouwbaarheid te verbeteren (foutopsporing, diagnostiek)",
  "privacy_s4_li5": "Met u te communiceren (serviceberichten, belangrijke beveiligingsupdates)",
  "privacy_s4_li6": "Wettelijke verplichtingen na te komen en onze voorwaarden te handhaven",
  "privacy_s4_footer": "We verzamelen alleen informatie die redelijkerwijs noodzakelijk is voor onze functies en activiteiten.",
  "privacy_s5_p1": "We kunnen persoonsgegevens openbaar maken aan:",
  "privacy_s5_li1": "Dienstverleners die helpen bij het beheren van de Dienst (zie sectie 6 voor details)",
  "privacy_s5_li2": "Autoriteiten indien vereist door de wet, gerechtelijk bevel, of om ernstige bedreigingen te voorkomen",
  "privacy_s5_li3": "Bedrijfsoverdrachten (bijv. overname of fusie), met passende bescherming",
  "privacy_s5_footer": "We verkopen geen persoonsgegevens.",
  "privacy_s6_p1": "Sommige dienstverleners kunnen gegevens buiten Australië opslaan of verwerken. We nemen redelijke stappen om naleving van de APPs te waarborgen.",
  "privacy_s6_table_h2": "Doel",
  "privacy_s6_table_h3": "Dataregio",
  "privacy_s6_table_r1_c2": "Authenticatie, database, bestandsopslag",
  "privacy_s6_table_r1_c3": "Geconfigureerd per project (AU/US/EU)",
  "privacy_s6_table_r2_c2": "Hosting en CDN",
  "privacy_s6_table_r2_c3": "Globale edge (US primair)",
  "privacy_s6_table_r3_c2": "Foutbewaking en prestatiediagnostiek",
  "privacy_s6_table_r4_c2": "Navigatierouting (alleen serverzijde)",
  "privacy_s6_table_r4_c3": "EU (Duitsland)",
  "privacy_s7_p1": "We nemen redelijke stappen om persoonsgegevens te beschermen. Onze beveiligingsmaatregelen omvatten:",
  "privacy_s7_li1": "Versleuteling tijdens overdracht (TLS/HTTPS afgedwongen via HSTS)",
  "privacy_s7_li2": "Versleuteling in rust voor database en bestandsopslag",
  "privacy_s7_li3": "Veilige wachtwoordhashing",
  "privacy_s7_li4": "Multifactor-authenticatieopties (TOTP, WebAuthn/passkeys)",
  "privacy_s7_li5": "Rolgebaseerde toegangscontrole en servicesleutels met minimale rechten",
  "privacy_s7_li6": "Snelheidsbeperking en brute-force-bescherming op authenticatie-eindpunten",
  "privacy_s7_li7": "Content Security Policy (CSP) met nonces ter voorkoming van XSS",
  "privacy_s7_li8": "Service worker-beveiliging: API-routes en geauthenticeerde pagina's worden nooit gecached; alle caches worden gewist bij uitloggen",
  "privacy_s7_li9": "Automatisch sessieverlies en veilige cookiebehandeling",
  "privacy_s7_footer": "Geen enkele methode van elektronische overdracht of opslag is 100% veilig.",
  "privacy_s8_p1": "We bewaren persoonsgegevens alleen zolang nodig voor:",
  "privacy_s8_li1": "Het leveren van de Dienst en het onderhouden van uw account",
  "privacy_s8_li2": "Het naleven van wettelijke verplichtingen",
  "privacy_s8_li3": "Het oplossen van geschillen en het handhaven van onze voorwaarden",
  "privacy_s8_li4": "Het handhaven van beveiliging en auditintegriteit",
  "privacy_s8_footer": "Wanneer uw gegevens niet meer nodig zijn, nemen we redelijke stappen om ze te verwijderen of te anonimiseren.",
  "privacy_s9_p1": "We gebruiken cookies en vergelijkbare technologieën om:",
  "privacy_s9_li1": "U ingelogd te houden en veilige sessies te onderhouden",
  "privacy_s9_li2": "Uw voorkeuren te onthouden (thema, taal, toegankelijkheidsinstellingen)",
  "privacy_s9_li3": "Applicatiefouten en prestaties te bewaken (via Sentry)",
  "privacy_s9_footer": "We gebruiken geen advertentiecookies van derden of gedragstracering.",
  "privacy_s10_p1": "Onder APPs 12 en 13 kunt u toegang vragen tot uw persoonsgegevens en correcties aanvragen.",
  "privacy_s10_p2_part1": "U kunt de meeste van uw gegevens direct bekijken en bijwerken in",
  "privacy_s10_p2_part2": "en",
  "privacy_s10_p2_part3": ". Voor andere verzoeken kunt u contact met ons opnemen via",
  "privacy_s10_p2_part4": ". We moeten mogelijk uw identiteit verifiëren voordat we verzoeken behandelen.",
  "privacy_s11_p1_part1": "Als u denkt dat we de Australian Privacy Principles hebben geschonden, kunt u een klacht indienen via e-mail naar",
  "privacy_s11_p1_part2": "met details over uw probleem.",
  "privacy_s11_p2_part1": "We bevestigen uw klacht en reageren binnen een redelijke termijn (doorgaans binnen 30 dagen). Als u niet tevreden bent, kunt u klagen bij de",
  "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "Als de Privacy Act 1988 op ons van toepassing is en er een datalek optreedt dat waarschijnlijk ernstige schade veroorzaakt, zullen we betrokkenen en de OAIC informeren volgens het",
  "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} is ontworpen voor universiteitsstudenten aan {{uniName}}. We verzamelen niet bewust persoonsgegevens van kinderen onder de 16.",
  "privacy_s14_p1": "We kunnen dit beleid van tijd tot tijd bijwerken. Wezenlijke wijzigingen worden gecommuniceerd via een in-app melding."
}

T["no"] = {
  "privacy_back_to": "Tilbake til {{appName}}",
  "privacy_title": "Personvernpolicy",
  "privacy_last_updated": "Sist oppdatert: 16. februar 2026 (AEDT)",
  "privacy_s1_title": "Form\u00e5l og omfang",
  "privacy_s1_p1": "Denne personvernpolicyen forklarer hvordan {{appName}} samler inn, lagrer, bruker og utleverer personopplysninger n\u00e5r du bruker v\u00e5r tjeneste.",
  "privacy_s1_p2": "{{appName}} er et campusverkt\u00f8y utviklet for studenter ved {{uniName}}. Denne policyen gjelder alle brukere av Tjenesten.",
  "privacy_s2_title": "Hvilke personopplysninger vi samler inn", "privacy_s2_a_title": "A) Konto- og identitetsdata", "privacy_s2_a_li1": "Fullt navn (eller visningsnavn)", "privacy_s2_a_li2": "E-postadresse", "privacy_s2_a_li3": "Passord (lagret som kryptografisk hash)", "privacy_s2_a_li4": "Studentnummer, studieprogram og studie\u00e5r", "privacy_s2_a_li5": "Kontoinnstillinger og preferanser", "privacy_s2_a_li6": "Profilbilde (hvis lastet opp)", "privacy_s2_b_title": "B) Multifaktorautentiseringsdata", "privacy_s2_b_li1": "TOTP-registreringshemmeligheter, lagret kryptert og med Cache-Control: no-store", "privacy_s2_b_li2": "WebAuthn/passkey-legitimasjons-IDer og offentlige n\u00f8kler (ingen biometriske data lagres)", "privacy_s2_c_title": "C) Bruks- og enhetsdata", "privacy_s2_c_li1": "Enhetstype, nettleser, operativsystem, spr\u00e5kpreferanse", "privacy_s2_c_li2": "IP-adresse (for sikkerhetsfartsbegrensning og misbruksforebygging)", "privacy_s2_c_li3": "Tidsstempler og grunnleggende foresp\u00f8rselsmetadata", "privacy_s2_c_li4": "Applikasjonsfeillogger og ytelsesdiagnostikk (samlet inn via Sentry)", "privacy_s2_d_title": "D) L\u00e6rings- og timeplaninnhold (brukeroppgitt)", "privacy_s2_d_li1": "Emner/kurs, timeplaner, frister, p\u00e5minnelser og oppgaver du oppretter", "privacy_s2_d_li2": "Kalenderbegivenheter og str\u00f8mpreferanser", "privacy_s2_e_title": "E) Posisjonsdata (kun med din tillatelse)", "privacy_s2_e_li1": "GPS-koordinater for campuskart og navigasjonsfunksjoner", "privacy_s2_e_li2": "Posisjonsdata behandles lokalt p\u00e5 enheten din og lagres ikke p\u00e5 v\u00e5re servere", "privacy_s2_e_li3": "Du kan tilbakekalle posisjonstillatelse n\u00e5r som helst", "privacy_s2_f_title": "F) Informasjonskapsler og \u00f8ktdata", "privacy_s2_f_li1": "\u00d8ktinformasjonskapsler (strengt n\u00f8dvendige for autentisering)", "privacy_s2_f_li2": "Sikkerhetsinformasjonskapsler (CSRF-beskyttelse)", "privacy_s2_f_li3": "Tema- og spr\u00e5kpreferanseinformasjonskapsler",
  "privacy_s2_footer": "Vi samler ikke bevisst inn sensitiv informasjon i henhold til Privacy Act uten at det er strengt n\u00f8dvendig og med ditt uttrykkelige samtykke.",
  "privacy_s3_p1": "Vi samler inn informasjon:", "privacy_s3_li1": "Direkte fra deg \u2014 n\u00e5r du registrerer deg, oppdaterer profilen din, oppretter innhold eller justerer innstillinger", "privacy_s3_li2": "Automatisk \u2014 via \u00f8ktinformasjonskapsler, serverlogger og feiovervaking", "privacy_s3_footer": "I samsvar med APP 5 tar vi rimelige skritt for \u00e5 varsle deg ved eller f\u00f8r innsamlingstidspunktet.",
  "privacy_s4_p1": "Vi bruker personopplysninger til \u00e5:", "privacy_s4_li1": "Levere og drifte Tjenesten", "privacy_s4_li2": "Tilpasse din opplevelse", "privacy_s4_li3": "Opprettholde sikkerhet", "privacy_s4_li4": "Forbedre ytelse og p\u00e5litelighet", "privacy_s4_li5": "Kommunisere med deg", "privacy_s4_li6": "Oppfylle juridiske forpliktelser", "privacy_s4_footer": "Vi samler kun inn informasjon som er rimelig n\u00f8dvendig.",
  "privacy_s5_p1": "Vi kan utlevere personopplysninger til:", "privacy_s5_li1": "Tjenesteleverand\u00f8rer (se seksjon 6)", "privacy_s5_li2": "Myndigheter ved lovp\u00e5legg", "privacy_s5_li3": "Virksomhetsoverdragelser med passende beskyttelse", "privacy_s5_footer": "Vi selger ikke personopplysninger.",
  "privacy_s6_p1": "Noen leverand\u00f8rer kan lagre data utenfor Australia. Vi tar rimelige skritt for \u00e5 sikre samsvar med APPs.", "privacy_s6_table_h2": "Form\u00e5l", "privacy_s6_table_h3": "Dataregion", "privacy_s6_table_r1_c2": "Autentisering, database, fillagring", "privacy_s6_table_r1_c3": "Konfigurert per prosjekt (AU/US/EU)", "privacy_s6_table_r2_c2": "Hosting og CDN", "privacy_s6_table_r2_c3": "Globalt edge (US prim\u00e6r)", "privacy_s6_table_r3_c2": "Feilovervaking og ytelsesdiagnostikk", "privacy_s6_table_r4_c2": "Navigasjonsruting (kun serverside)", "privacy_s6_table_r4_c3": "EU (Tyskland)",
  "privacy_s7_p1": "Vi tar rimelige skritt for \u00e5 beskytte personopplysninger. V\u00e5re sikkerhetstiltak inkluderer:", "privacy_s7_li1": "Kryptering under overf\u00f8ring (TLS/HTTPS via HSTS)", "privacy_s7_li2": "Kryptering i hvile for database og filer", "privacy_s7_li3": "Sikker passordhashing", "privacy_s7_li4": "Multifaktorautentiseringsalternativer (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "Rollebaserte tilgangskontroller", "privacy_s7_li6": "Fartsbegrensning og brute-force-beskyttelse", "privacy_s7_li7": "Content Security Policy (CSP) med nonces mot XSS", "privacy_s7_li8": "Service worker-sikkerhet: API-ruter caches aldri; alle cacher t\u00f8mmes ved utlogging", "privacy_s7_li9": "Automatisk \u00f8ktutl\u00f8p og sikker informasjonskapselh\u00e5ndtering", "privacy_s7_footer": "Ingen elektronisk overf\u00f8ringsmetode er 100% sikker.",
  "privacy_s8_p1": "Vi beholder personopplysninger kun s\u00e5 lenge det er n\u00f8dvendig for \u00e5:", "privacy_s8_li1": "Levere Tjenesten og vedlikeholde kontoen din", "privacy_s8_li2": "Overholde juridiske forpliktelser", "privacy_s8_li3": "L\u00f8se tvister og h\u00e5ndheve v\u00e5re vilk\u00e5r", "privacy_s8_li4": "Opprettholde sikkerhet og revisjonsintegritet", "privacy_s8_footer": "N\u00e5r dataene dine ikke lenger er n\u00f8dvendige, tar vi rimelige skritt for \u00e5 slette eller anonymisere dem.",
  "privacy_s9_p1": "Vi bruker informasjonskapsler for \u00e5:", "privacy_s9_li1": "Holde deg innlogget", "privacy_s9_li2": "Huske dine preferanser", "privacy_s9_li3": "Overv\u00e5ke feil og ytelse (via Sentry)", "privacy_s9_footer": "Vi bruker ikke tredjeparts reklameinformasjonskapsler.",
  "privacy_s10_p1": "I henhold til APPs 12 og 13 kan du be om tilgang til og korrigering av dine personopplysninger.", "privacy_s10_p2_part1": "Du kan se og oppdatere informasjonen din direkte i", "privacy_s10_p2_part2": "og", "privacy_s10_p2_part3": ". For andre foresp\u00f8rsler, kontakt oss p\u00e5", "privacy_s10_p2_part4": ". Vi kan m\u00e5tte verifisere identiteten din.",
  "privacy_s11_p1_part1": "Hvis du mener vi har brutt Australian Privacy Principles, kan du klage via e-post til", "privacy_s11_p1_part2": "med detaljer.", "privacy_s11_p2_part1": "Vi bekrefter klagen og svarer innen rimelig tid (normalt 30 dager). Hvis du ikke er forn\u00f8yd, kan du klage til", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "Ved et kvalifisert databrudd som kan for\u00e5rsake alvorlig skade, vil vi varsle ber\u00f8rte personer og OAIC i henhold til", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} er laget for universitetsstudenter ved {{uniName}}. Vi samler ikke bevisst inn personopplysninger fra barn under 16 \u00e5r.",
  "privacy_s14_p1": "Vi kan oppdatere denne policyen. Vesentlige endringer kommuniseres via varsling i appen."
}

T["pl"] = {
  "privacy_back_to": "Wróć do {{appName}}",
  "privacy_title": "Polityka prywatności",
  "privacy_last_updated": "Ostatnia aktualizacja: 16 lutego 2026 (AEDT)",
  "privacy_s1_title": "Cel i zakres",
  "privacy_s1_p1": "Niniejsza Polityka prywatności wyjaśnia, w jaki sposób {{appName}} gromadzi, przechowuje, wykorzystuje i ujawnia dane osobowe podczas korzystania z naszej usługi.",
  "privacy_s1_p2": "{{appName}} to narzędzie kampusowe opracowane dla studentów {{uniName}}. Niniejsza polityka dotyczy wszystkich użytkowników Usługi.",
  "privacy_s2_title": "Jakie dane osobowe gromadzimy", "privacy_s2_a_title": "A) Dane konta i tożsamości", "privacy_s2_a_li1": "Imię i nazwisko (lub nazwa wyświetlana)", "privacy_s2_a_li2": "Adres e-mail", "privacy_s2_a_li3": "Hasło (przechowywane jako hash kryptograficzny — nigdy nie przechowujemy hasła w postaci jawnej)", "privacy_s2_a_li4": "Numer studenta, kierunek i rok studiów", "privacy_s2_a_li5": "Preferencje i ustawienia konta", "privacy_s2_a_li6": "Awatar profilu (jeśli przesłany)", "privacy_s2_b_title": "B) Dane uwierzytelniania wieloskładnikowego", "privacy_s2_b_li1": "Sekrety rejestracji TOTP, przechowywane zaszyfrowane i z Cache-Control: no-store", "privacy_s2_b_li2": "Identyfikatory poświadczeń WebAuthn/passkey i klucze publiczne (dane biometryczne nie są przechowywane)", "privacy_s2_c_title": "C) Dane użytkowania i urządzenia", "privacy_s2_c_li1": "Typ urządzenia, przeglądarka, system operacyjny, preferencja językowa", "privacy_s2_c_li2": "Adres IP (do ograniczania szybkości i zapobiegania nadużyciom)", "privacy_s2_c_li3": "Znaczniki czasu i podstawowe metadane żądań", "privacy_s2_c_li4": "Dzienniki błędów aplikacji i diagnostyka wydajności (zbierane przez Sentry z maskowaniem tekstu i blokowaniem mediów)", "privacy_s2_d_title": "D) Treści edukacyjne i planu zajęć (dostarczone przez użytkownika)", "privacy_s2_d_li1": "Przedmioty/kursy, harmonogramy, terminy, przypomnienia i zadania, które tworzysz", "privacy_s2_d_li2": "Wydarzenia kalendarzowe i preferencje kanału", "privacy_s2_e_title": "E) Dane lokalizacyjne (tylko za Twoją zgodą)", "privacy_s2_e_li1": "Współrzędne GPS do mapy kampusu i nawigacji — zbierane tylko po udzieleniu zgody na lokalizację", "privacy_s2_e_li2": "Dane lokalizacyjne są przetwarzane lokalnie na urządzeniu i nie są przechowywane na naszych serwerach", "privacy_s2_e_li3": "Możesz cofnąć zgodę na lokalizację w dowolnym momencie w ustawieniach urządzenia lub przeglądarki", "privacy_s2_f_title": "F) Pliki cookie i dane sesji", "privacy_s2_f_li1": "Pliki cookie sesji (ściśle niezbędne do uwierzytelniania)", "privacy_s2_f_li2": "Pliki cookie bezpieczeństwa (ochrona CSRF)", "privacy_s2_f_li3": "Pliki cookie preferencji motywu i języka",
  "privacy_s2_footer": "Nie gromadzimy celowo informacji wrażliwych w rozumieniu Privacy Act, chyba że jest to ściśle konieczne i za Twoją wyraźną zgodą.",
  "privacy_s3_p1": "Gromadzimy informacje:", "privacy_s3_li1": "Bezpośrednio od Ciebie — podczas rejestracji, aktualizacji profilu, tworzenia treści lub zmiany ustawień", "privacy_s3_li2": "Automatycznie — przez pliki cookie sesji, dzienniki serwera i monitorowanie błędów", "privacy_s3_footer": "Zgodnie z APP 5 podejmujemy rozsądne kroki, aby poinformować Cię w momencie lub przed zbieraniem danych.",
  "privacy_s4_p1": "Wykorzystujemy dane osobowe do:", "privacy_s4_li1": "Dostarczania i obsługi Usługi", "privacy_s4_li2": "Personalizacji Twojego doświadczenia", "privacy_s4_li3": "Utrzymania bezpieczeństwa", "privacy_s4_li4": "Poprawy wydajności i niezawodności", "privacy_s4_li5": "Komunikacji z Tobą", "privacy_s4_li6": "Wypełniania zobowiązań prawnych", "privacy_s4_footer": "Gromadzimy tylko informacje rozsądnie niezbędne do naszych funkcji.",
  "privacy_s5_p1": "Możemy ujawnić dane osobowe:", "privacy_s5_li1": "Dostawcom usług (szczegóły w sekcji 6)", "privacy_s5_li2": "Organom władzy jeśli wymagane prawem", "privacy_s5_li3": "Przy transferach biznesowych z odpowiednią ochroną", "privacy_s5_footer": "Nie sprzedajemy danych osobowych.",
  "privacy_s6_p1": "Niektórzy dostawcy mogą przechowywać dane poza Australią. Podejmujemy rozsądne kroki w celu zapewnienia zgodności z APPs.", "privacy_s6_table_h2": "Cel", "privacy_s6_table_h3": "Region danych", "privacy_s6_table_r1_c2": "Uwierzytelnianie, baza danych, przechowywanie plików", "privacy_s6_table_r1_c3": "Konfigurowane per projekt (AU/US/EU)", "privacy_s6_table_r2_c2": "Hosting i CDN", "privacy_s6_table_r2_c3": "Globalny edge (US główny)", "privacy_s6_table_r3_c2": "Monitorowanie błędów i diagnostyka wydajności", "privacy_s6_table_r4_c2": "Routing nawigacji (tylko po stronie serwera)", "privacy_s6_table_r4_c3": "UE (Niemcy)",
  "privacy_s7_p1": "Podejmujemy rozsądne kroki w celu ochrony danych osobowych. Nasze środki bezpieczeństwa obejmują:", "privacy_s7_li1": "Szyfrowanie w tranzycie (TLS/HTTPS przez HSTS)", "privacy_s7_li2": "Szyfrowanie w spoczynku dla bazy danych i plików", "privacy_s7_li3": "Bezpieczne hashowanie haseł", "privacy_s7_li4": "Opcje uwierzytelniania wieloskładnikowego (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "Kontrola dostępu oparta na rolach", "privacy_s7_li6": "Ograniczanie szybkości i ochrona brute-force", "privacy_s7_li7": "Content Security Policy (CSP) z nonces przeciwko XSS", "privacy_s7_li8": "Bezpieczeństwo service worker: trasy API nigdy nie są buforowane; wszystkie pamięci podręczne są czyszczone przy wylogowaniu", "privacy_s7_li9": "Automatyczne wygasanie sesji i bezpieczna obsługa plików cookie", "privacy_s7_footer": "Żadna metoda transmisji elektronicznej nie jest w 100% bezpieczna.",
  "privacy_s8_p1": "Przechowujemy dane osobowe tylko tak długo, jak to konieczne do:", "privacy_s8_li1": "Dostarczania Usługi i utrzymania konta", "privacy_s8_li2": "Wypełniania zobowiązań prawnych", "privacy_s8_li3": "Rozwiązywania sporów", "privacy_s8_li4": "Utrzymania bezpieczeństwa i integralności audytu", "privacy_s8_footer": "Gdy dane nie są już potrzebne, podejmujemy kroki w celu ich usunięcia lub anonimizacji.",
  "privacy_s9_p1": "Używamy plików cookie do:", "privacy_s9_li1": "Utrzymania Twojego zalogowania", "privacy_s9_li2": "Zapamiętywania Twoich preferencji", "privacy_s9_li3": "Monitorowania błędów aplikacji (przez Sentry)", "privacy_s9_footer": "Nie używamy reklamowych plików cookie stron trzecich.",
  "privacy_s10_p1": "Zgodnie z APPs 12 i 13 możesz żądać dostępu do swoich danych osobowych i ich korekty.", "privacy_s10_p2_part1": "Większość swoich danych możesz przeglądać i aktualizować bezpośrednio w", "privacy_s10_p2_part2": "i", "privacy_s10_p2_part3": ". W sprawie innych żądań skontaktuj się z nami pod adresem", "privacy_s10_p2_part4": ". Możemy potrzebować zweryfikować Twoją tożsamość.",
  "privacy_s11_p1_part1": "Jeśli uważasz, że naruszyliśmy Australian Privacy Principles, możesz złożyć skargę na adres", "privacy_s11_p1_part2": "ze szczegółami.", "privacy_s11_p2_part1": "Potwierdzimy skargę i odpowiemy w rozsądnym terminie (zwykle 30 dni). Jeśli nie jesteś zadowolony, możesz złożyć skargę do", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "W przypadku naruszenia danych mogącego spowodować poważną szkodę, powiadomimy osoby dotknięte i OAIC zgodnie z", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} jest przeznaczony dla studentów {{uniName}}. Nie gromadzimy świadomie danych osobowych dzieci poniżej 16. roku życia.",
  "privacy_s14_p1": "Możemy aktualizować tę politykę. Istotne zmiany będą komunikowane przez powiadomienie w aplikacji."
}

T["pt"] = {
  "privacy_back_to": "Voltar para {{appName}}",
  "privacy_title": "Política de Privacidade",
  "privacy_last_updated": "Última atualização: 16 de fevereiro de 2026 (AEDT)",
  "privacy_s1_title": "Propósito e âmbito",
  "privacy_s1_p1": "Esta Política de Privacidade explica como o {{appName}} coleta, armazena, utiliza e divulga informações pessoais quando você usa nosso serviço.",
  "privacy_s1_p2": "{{appName}} é uma ferramenta universitária desenvolvida para estudantes da {{uniName}}. Esta política se aplica a todos os usuários do Serviço.",
  "privacy_s2_title": "Quais informações pessoais coletamos", "privacy_s2_a_title": "A) Dados de conta e identidade", "privacy_s2_a_li1": "Nome completo (ou nome de exibição)", "privacy_s2_a_li2": "Endereço de e-mail", "privacy_s2_a_li3": "Senha (armazenada como hash criptográfico — nunca armazenamos sua senha em texto simples)", "privacy_s2_a_li4": "Número de matrícula, curso e ano de estudo", "privacy_s2_a_li5": "Preferências e configurações da conta", "privacy_s2_a_li6": "Avatar do perfil (se carregado)", "privacy_s2_b_title": "B) Dados de autenticação multifator", "privacy_s2_b_li1": "Segredos de inscrição TOTP, armazenados criptografados e servidos com Cache-Control: no-store", "privacy_s2_b_li2": "IDs de credenciais WebAuthn/passkey e chaves públicas (nenhum dado biométrico é armazenado)", "privacy_s2_c_title": "C) Dados de uso e dispositivo", "privacy_s2_c_li1": "Tipo de dispositivo, navegador, sistema operacional, preferência de idioma", "privacy_s2_c_li2": "Endereço IP (para limitação de taxa e prevenção de abuso)", "privacy_s2_c_li3": "Carimbos de data/hora e metadados básicos de solicitação", "privacy_s2_c_li4": "Logs de erro do aplicativo e diagnósticos de desempenho (via Sentry com mascaramento de texto e bloqueio de mídia)", "privacy_s2_d_title": "D) Conteúdo de aprendizado e horários (fornecido pelo usuário)", "privacy_s2_d_li1": "Unidades/cursos, horários, prazos, lembretes e tarefas que você cria", "privacy_s2_d_li2": "Eventos de calendário e preferências de feed", "privacy_s2_e_title": "E) Dados de localização (apenas com sua permissão)", "privacy_s2_e_li1": "Coordenadas GPS para mapa do campus e navegação — coletadas apenas quando você concede permissão", "privacy_s2_e_li2": "Dados de localização são processados localmente no seu dispositivo e não armazenados nos nossos servidores", "privacy_s2_e_li3": "Você pode revogar a permissão de localização a qualquer momento", "privacy_s2_f_title": "F) Cookies e dados de sessão", "privacy_s2_f_li1": "Cookies de sessão (estritamente necessários para autenticação)", "privacy_s2_f_li2": "Cookies de segurança (proteção CSRF)", "privacy_s2_f_li3": "Cookies de preferência de tema e idioma",
  "privacy_s2_footer": "Não coletamos intencionalmente informações sensíveis conforme definidas pelo Privacy Act, a menos que seja estritamente necessário e com seu consentimento explícito.",
  "privacy_s3_p1": "Coletamos informações:", "privacy_s3_li1": "Diretamente de você — ao se cadastrar, atualizar perfil, criar conteúdo ou ajustar configurações", "privacy_s3_li2": "Automaticamente — via cookies de sessão, logs de servidor e monitoramento de erros", "privacy_s3_footer": "De acordo com o APP 5, tomamos medidas razoáveis para notificá-lo no momento ou antes da coleta.",
  "privacy_s4_p1": "Usamos informações pessoais para:", "privacy_s4_li1": "Fornecer e operar o Serviço", "privacy_s4_li2": "Personalizar sua experiência", "privacy_s4_li3": "Manter a segurança", "privacy_s4_li4": "Melhorar desempenho e confiabilidade", "privacy_s4_li5": "Comunicar com você", "privacy_s4_li6": "Cumprir obrigações legais", "privacy_s4_footer": "Coletamos apenas informações razoavelmente necessárias.",
  "privacy_s5_p1": "Podemos divulgar informações pessoais para:", "privacy_s5_li1": "Provedores de serviço (veja Seção 6)", "privacy_s5_li2": "Autoridades se exigido por lei", "privacy_s5_li3": "Transferências empresariais com proteções apropriadas", "privacy_s5_footer": "Não vendemos informações pessoais.",
  "privacy_s6_p1": "Alguns provedores podem armazenar dados fora da Austrália. Tomamos medidas razoáveis para garantir conformidade com os APPs.", "privacy_s6_table_h2": "Finalidade", "privacy_s6_table_h3": "Região dos dados", "privacy_s6_table_r1_c2": "Autenticação, banco de dados, armazenamento de arquivos", "privacy_s6_table_r1_c3": "Configurado por projeto (AU/US/EU)", "privacy_s6_table_r2_c2": "Hospedagem e CDN", "privacy_s6_table_r2_c3": "Edge global (US primário)", "privacy_s6_table_r3_c2": "Monitoramento de erros e diagnósticos de desempenho", "privacy_s6_table_r4_c2": "Roteamento de navegação (apenas servidor)", "privacy_s6_table_r4_c3": "UE (Alemanha)",
  "privacy_s7_p1": "Tomamos medidas razoáveis para proteger informações pessoais. Nossas medidas incluem:", "privacy_s7_li1": "Criptografia em trânsito (TLS/HTTPS via HSTS)", "privacy_s7_li2": "Criptografia em repouso para banco de dados e arquivos", "privacy_s7_li3": "Hash seguro de senha", "privacy_s7_li4": "Opções de autenticação multifator (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "Controles de acesso baseados em função", "privacy_s7_li6": "Limitação de taxa e proteção contra força bruta", "privacy_s7_li7": "Content Security Policy (CSP) com nonces para prevenir XSS", "privacy_s7_li8": "Segurança do service worker: rotas de API nunca são armazenadas em cache; todos os caches são limpos no logout", "privacy_s7_li9": "Expiração automática de sessão e manipulação segura de cookies", "privacy_s7_footer": "Nenhum método de transmissão eletrônica é 100% seguro.",
  "privacy_s8_p1": "Retemos informações pessoais apenas pelo tempo necessário para:", "privacy_s8_li1": "Fornecer o Serviço e manter sua conta", "privacy_s8_li2": "Cumprir obrigações legais", "privacy_s8_li3": "Resolver disputas", "privacy_s8_li4": "Manter segurança e integridade de auditoria", "privacy_s8_footer": "Quando seus dados não forem mais necessários, tomamos medidas para excluí-los ou anonimizá-los.",
  "privacy_s9_p1": "Usamos cookies para:", "privacy_s9_li1": "Manter você conectado", "privacy_s9_li2": "Lembrar suas preferências", "privacy_s9_li3": "Monitorar erros do aplicativo (via Sentry)", "privacy_s9_footer": "Não usamos cookies de publicidade de terceiros.",
  "privacy_s10_p1": "Sob os APPs 12 e 13, você pode solicitar acesso e correções às suas informações pessoais.", "privacy_s10_p2_part1": "Você pode visualizar e atualizar suas informações diretamente em", "privacy_s10_p2_part2": "e", "privacy_s10_p2_part3": ". Para outras solicitações, entre em contato em", "privacy_s10_p2_part4": ". Podemos precisar verificar sua identidade.",
  "privacy_s11_p1_part1": "Se você acredita que violamos os Australian Privacy Principles, pode registrar uma reclamação em", "privacy_s11_p1_part2": "com detalhes de sua preocupação.", "privacy_s11_p2_part1": "Confirmaremos sua reclamação e responderemos em prazo razoável (geralmente 30 dias). Se não estiver satisfeito, pode reclamar ao", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "Em caso de violação de dados elegível que resulte em dano grave, notificaremos os afetados e o OAIC conforme", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} é projetado para estudantes universitários na {{uniName}}. Não coletamos intencionalmente informações de crianças menores de 16 anos.",
  "privacy_s14_p1": "Podemos atualizar esta política. Alterações materiais serão comunicadas via notificação no aplicativo."
}

T["ro"] = {
  "privacy_back_to": "Înapoi la {{appName}}", "privacy_title": "Politica de confidențialitate", "privacy_last_updated": "Ultima actualizare: 16 februarie 2026 (AEDT)",
  "privacy_s1_title": "Scop și domeniu de aplicare", "privacy_s1_p1": "Această politică explică modul în care {{appName}} colectează, stochează, utilizează și divulgă informații personale.", "privacy_s1_p2": "{{appName}} este un instrument de campus dezvoltat pentru studenții de la {{uniName}}. Această politică se aplică tuturor utilizatorilor Serviciului.",
  "privacy_s2_title": "Ce informații personale colectăm", "privacy_s2_a_title": "A) Date de cont și identitate", "privacy_s2_a_li1": "Numele complet (sau numele afișat)", "privacy_s2_a_li2": "Adresa de e-mail", "privacy_s2_a_li3": "Parola (stocată ca hash criptografic — nu stocăm niciodată parola în text clar)", "privacy_s2_a_li4": "Număr de student, program de studii și anul de studiu", "privacy_s2_a_li5": "Preferințe și setări ale contului", "privacy_s2_a_li6": "Avatarul profilului (dacă este încărcat)", "privacy_s2_b_title": "B) Date de autentificare multifactor", "privacy_s2_b_li1": "Secrete de înregistrare TOTP, stocate criptat și cu Cache-Control: no-store", "privacy_s2_b_li2": "ID-uri de acreditare WebAuthn/passkey și chei publice (nu se stochează date biometrice)", "privacy_s2_c_title": "C) Date de utilizare și dispozitiv", "privacy_s2_c_li1": "Tipul dispozitivului, browser, sistem de operare, preferință de limbă", "privacy_s2_c_li2": "Adresa IP (pentru limitarea ratei și prevenirea abuzurilor)", "privacy_s2_c_li3": "Marcaje temporale și metadate de bază", "privacy_s2_c_li4": "Jurnale de erori și diagnostice de performanță (prin Sentry)", "privacy_s2_d_title": "D) Conținut educațional și orar (furnizat de utilizator)", "privacy_s2_d_li1": "Discipline/cursuri, orare, termene limită, memento-uri și sarcini", "privacy_s2_d_li2": "Evenimente din calendar și preferințe de flux", "privacy_s2_e_title": "E) Date de locație (doar cu permisiunea dvs.)", "privacy_s2_e_li1": "Coordonate GPS pentru harta campusului și navigare", "privacy_s2_e_li2": "Datele de locație sunt procesate local pe dispozitiv și nu sunt stocate pe serverele noastre", "privacy_s2_e_li3": "Puteți revoca permisiunea de locație oricând", "privacy_s2_f_title": "F) Cookie-uri și date de sesiune", "privacy_s2_f_li1": "Cookie-uri de sesiune (strict necesare pentru autentificare)", "privacy_s2_f_li2": "Cookie-uri de securitate (protecție CSRF)", "privacy_s2_f_li3": "Cookie-uri de preferință pentru temă și limbă",
  "privacy_s2_footer": "Nu colectăm intenționat informații sensibile conform Privacy Act, cu excepția cazului în care este strict necesar și cu consimțământul dvs. explicit.",
  "privacy_s3_p1": "Colectăm informații:", "privacy_s3_li1": "Direct de la dvs. — când vă înregistrați, actualizați profilul, creați conținut sau ajustați setările", "privacy_s3_li2": "Automat — prin cookie-uri de sesiune, jurnale de server și monitorizarea erorilor", "privacy_s3_footer": "În conformitate cu APP 5, luăm măsuri rezonabile pentru a vă informa în momentul colectării.",
  "privacy_s4_p1": "Utilizăm informații personale pentru:", "privacy_s4_li1": "Furnizarea și operarea Serviciului", "privacy_s4_li2": "Personalizarea experienței dvs.", "privacy_s4_li3": "Menținerea securității", "privacy_s4_li4": "Îmbunătățirea performanței și fiabilității", "privacy_s4_li5": "Comunicarea cu dvs.", "privacy_s4_li6": "Îndeplinirea obligațiilor legale", "privacy_s4_footer": "Colectăm doar informațiile necesare în mod rezonabil.",
  "privacy_s5_p1": "Putem divulga informații personale:", "privacy_s5_li1": "Furnizorilor de servicii (vezi secțiunea 6)", "privacy_s5_li2": "Autorităților dacă este cerut de lege", "privacy_s5_li3": "Transferuri de afaceri cu protecție adecvată", "privacy_s5_footer": "Nu vindem informații personale.",
  "privacy_s6_p1": "Unii furnizori pot stoca date în afara Australiei. Luăm măsuri rezonabile pentru conformitate cu APPs.", "privacy_s6_table_h2": "Scop", "privacy_s6_table_h3": "Regiunea datelor", "privacy_s6_table_r1_c2": "Autentificare, bază de date, stocare fișiere", "privacy_s6_table_r1_c3": "Configurat per proiect (AU/US/EU)", "privacy_s6_table_r2_c2": "Hosting și CDN", "privacy_s6_table_r2_c3": "Edge global (US primar)", "privacy_s6_table_r3_c2": "Monitorizare erori și diagnostice", "privacy_s6_table_r4_c2": "Rutare navigare (doar server)", "privacy_s6_table_r4_c3": "UE (Germania)",
  "privacy_s7_p1": "Luăm măsuri rezonabile pentru protejarea informațiilor personale. Măsurile noastre includ:", "privacy_s7_li1": "Criptare în tranzit (TLS/HTTPS prin HSTS)", "privacy_s7_li2": "Criptare în repaus pentru baza de date și fișiere", "privacy_s7_li3": "Hashing securizat al parolelor", "privacy_s7_li4": "Opțiuni de autentificare multifactor (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "Controlul accesului bazat pe roluri", "privacy_s7_li6": "Limitarea ratei și protecție brute-force", "privacy_s7_li7": "Content Security Policy (CSP) cu nonces împotriva XSS", "privacy_s7_li8": "Securitate service worker: rutele API nu sunt niciodată stocate în cache; toate cache-urile sunt șterse la deconectare", "privacy_s7_li9": "Expirare automată a sesiunii și gestionare securizată a cookie-urilor", "privacy_s7_footer": "Nicio metodă de transmisie electronică nu este 100% sigură.",
  "privacy_s8_p1": "Păstrăm informațiile personale doar cât este necesar pentru:", "privacy_s8_li1": "Furnizarea Serviciului", "privacy_s8_li2": "Conformitate legală", "privacy_s8_li3": "Soluționarea disputelor", "privacy_s8_li4": "Menținerea securității și integrității auditului", "privacy_s8_footer": "Când datele nu mai sunt necesare, luăm măsuri pentru ștergere sau anonimizare.",
  "privacy_s9_p1": "Utilizăm cookie-uri pentru:", "privacy_s9_li1": "A vă menține autentificat", "privacy_s9_li2": "A reține preferințele dvs.", "privacy_s9_li3": "A monitoriza erorile (prin Sentry)", "privacy_s9_footer": "Nu folosim cookie-uri publicitare terțe.",
  "privacy_s10_p1": "Conform APPs 12 și 13, puteți solicita acces și corecții ale datelor dvs.", "privacy_s10_p2_part1": "Puteți vizualiza și actualiza datele în", "privacy_s10_p2_part2": "și", "privacy_s10_p2_part3": ". Pentru alte solicitări, contactați-ne la", "privacy_s10_p2_part4": ". Poate fi necesară verificarea identității.",
  "privacy_s11_p1_part1": "Dacă credeți că am încălcat Australian Privacy Principles, puteți depune o plângere la", "privacy_s11_p1_part2": "cu detalii.", "privacy_s11_p2_part1": "Vom confirma plângerea și vom răspunde în termen rezonabil (de obicei 30 de zile). Dacă nu sunteți mulțumit, puteți contacta", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "În cazul unei breșe de date care poate cauza daune grave, vom notifica persoanele afectate și OAIC conform", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} este conceput pentru studenții de la {{uniName}}. Nu colectăm în mod conștient date de la copiii sub 16 ani.",
  "privacy_s14_p1": "Putem actualiza această politică. Modificările importante vor fi comunicate prin notificare în aplicație."
}

T["sv"] = {
  "privacy_back_to": "Tillbaka till {{appName}}", "privacy_title": "Integritetspolicy", "privacy_last_updated": "Senast uppdaterad: 16 februari 2026 (AEDT)",
  "privacy_s1_title": "Syfte och omfattning", "privacy_s1_p1": "Denna integritetspolicy förklarar hur {{appName}} samlar in, lagrar, använder och lämnar ut personuppgifter när du använder vår tjänst.", "privacy_s1_p2": "{{appName}} är ett campusverktyg utvecklat för studenter vid {{uniName}}. Denna policy gäller alla användare av Tjänsten.",
  "privacy_s2_title": "Vilka personuppgifter vi samlar in", "privacy_s2_a_title": "A) Konto- och identitetsuppgifter", "privacy_s2_a_li1": "Fullständigt namn (eller visningsnamn)", "privacy_s2_a_li2": "E-postadress", "privacy_s2_a_li3": "Lösenord (lagrat som kryptografisk hash — vi lagrar aldrig ditt lösenord i klartext)", "privacy_s2_a_li4": "Studentnummer, program och studieår", "privacy_s2_a_li5": "Kontoinställningar och preferenser", "privacy_s2_a_li6": "Profilbild (om uppladdad)", "privacy_s2_b_title": "B) Multifaktorautentiseringsdata", "privacy_s2_b_li1": "TOTP-registreringshemligheter, lagrade krypterat och med Cache-Control: no-store", "privacy_s2_b_li2": "WebAuthn/passkey-autentiserings-IDn och publika nycklar (inga biometriska data lagras)", "privacy_s2_c_title": "C) Användnings- och enhetsdata", "privacy_s2_c_li1": "Enhetstyp, webbläsare, operativsystem, språkpreferens", "privacy_s2_c_li2": "IP-adress (för säkerhetsbegränsning och missbruksförebyggande)", "privacy_s2_c_li3": "Tidsstämplar och grundläggande begäranmetadata", "privacy_s2_c_li4": "Applikationsfelloggar och prestandadiagnostik (via Sentry)", "privacy_s2_d_title": "D) Lärande- och schemainnehåll (tillhandahållet av användare)", "privacy_s2_d_li1": "Kurser, scheman, deadlines, påminnelser och uppgifter du skapar", "privacy_s2_d_li2": "Kalenderhändelser och flödespreferenser", "privacy_s2_e_title": "E) Platsdata (endast med ditt tillstånd)", "privacy_s2_e_li1": "GPS-koordinater för campuskarta och navigering — samlas in först när du ger platstillstånd", "privacy_s2_e_li2": "Platsdata bearbetas lokalt på din enhet och lagras inte på våra servrar", "privacy_s2_e_li3": "Du kan återkalla platstillstånd när som helst", "privacy_s2_f_title": "F) Cookies och sessionsdata", "privacy_s2_f_li1": "Sessionscookies (strikt nödvändiga för autentisering)", "privacy_s2_f_li2": "Säkerhetscookies (CSRF-skydd)", "privacy_s2_f_li3": "Tema- och språkpreferenscookies",
  "privacy_s2_footer": "Vi samlar inte medvetet in känslig information enligt Privacy Act utan att det är strikt nödvändigt och med ditt uttryckliga samtycke.",
  "privacy_s3_p1": "Vi samlar in information:", "privacy_s3_li1": "Direkt från dig — när du registrerar dig, uppdaterar din profil, skapar innehåll eller justerar inställningar", "privacy_s3_li2": "Automatiskt — via sessionscookies, serverloggar och felövervakning", "privacy_s3_footer": "I enlighet med APP 5 vidtar vi rimliga åtgärder för att informera dig vid eller före insamlingstidpunkten.",
  "privacy_s4_p1": "Vi använder personuppgifter för att:", "privacy_s4_li1": "Tillhandahålla och driva Tjänsten", "privacy_s4_li2": "Anpassa din upplevelse", "privacy_s4_li3": "Upprätthålla säkerhet", "privacy_s4_li4": "Förbättra prestanda och tillförlitlighet", "privacy_s4_li5": "Kommunicera med dig", "privacy_s4_li6": "Uppfylla rättsliga skyldigheter", "privacy_s4_footer": "Vi samlar bara in information som rimligen behövs.",
  "privacy_s5_p1": "Vi kan lämna ut personuppgifter till:", "privacy_s5_li1": "Tjänsteleverantörer (se avsnitt 6)", "privacy_s5_li2": "Myndigheter om det krävs enligt lag", "privacy_s5_li3": "Affärsöverlåtelser med lämpligt skydd", "privacy_s5_footer": "Vi säljer inte personuppgifter.",
  "privacy_s6_p1": "Vissa leverantörer kan lagra data utanför Australien. Vi vidtar rimliga åtgärder för att säkerställa överensstämmelse med APPs.", "privacy_s6_table_h2": "Syfte", "privacy_s6_table_h3": "Dataregion", "privacy_s6_table_r1_c2": "Autentisering, databas, fillagring", "privacy_s6_table_r1_c3": "Konfigurerat per projekt (AU/US/EU)", "privacy_s6_table_r2_c2": "Hosting och CDN", "privacy_s6_table_r2_c3": "Globalt edge (US primär)", "privacy_s6_table_r3_c2": "Felövervakning och prestandadiagnostik", "privacy_s6_table_r4_c2": "Navigeringsrouting (endast serverside)", "privacy_s6_table_r4_c3": "EU (Tyskland)",
  "privacy_s7_p1": "Vi vidtar rimliga åtgärder för att skydda personuppgifter. Våra säkerhetsåtgärder inkluderar:", "privacy_s7_li1": "Kryptering under överföring (TLS/HTTPS via HSTS)", "privacy_s7_li2": "Kryptering i vila för databas och filer", "privacy_s7_li3": "Säker lösenordshashning", "privacy_s7_li4": "Alternativ för multifaktorautentisering (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "Rollbaserad åtkomstkontroll", "privacy_s7_li6": "Hastighetsbegränsning och brute-force-skydd", "privacy_s7_li7": "Content Security Policy (CSP) med nonces mot XSS", "privacy_s7_li8": "Service worker-säkerhet: API-rutter cachas aldrig; alla cachar rensas vid utloggning", "privacy_s7_li9": "Automatiskt sessionsutgång och säker cookiehantering", "privacy_s7_footer": "Ingen elektronisk överföringsmetod är 100% säker.",
  "privacy_s8_p1": "Vi behåller personuppgifter bara så länge det behövs för att:", "privacy_s8_li1": "Tillhandahålla Tjänsten", "privacy_s8_li2": "Uppfylla rättsliga skyldigheter", "privacy_s8_li3": "Lösa tvister", "privacy_s8_li4": "Upprätthålla säkerhet och revisionsintegritet", "privacy_s8_footer": "När dina uppgifter inte längre behövs vidtar vi rimliga åtgärder för att radera eller anonymisera dem.",
  "privacy_s9_p1": "Vi använder cookies för att:", "privacy_s9_li1": "Hålla dig inloggad", "privacy_s9_li2": "Komma ihåg dina preferenser", "privacy_s9_li3": "Övervaka fel och prestanda (via Sentry)", "privacy_s9_footer": "Vi använder inte tredjepartsannonskookies.",
  "privacy_s10_p1": "Enligt APPs 12 och 13 kan du begära tillgång till och korrigering av dina personuppgifter.", "privacy_s10_p2_part1": "Du kan visa och uppdatera dina uppgifter direkt i", "privacy_s10_p2_part2": "och", "privacy_s10_p2_part3": ". För andra förfrågningar, kontakta oss på", "privacy_s10_p2_part4": ". Vi kan behöva verifiera din identitet.",
  "privacy_s11_p1_part1": "Om du anser att vi brutit mot Australian Privacy Principles kan du lämna in ett klagomål till", "privacy_s11_p1_part2": "med detaljer.", "privacy_s11_p2_part1": "Vi bekräftar ditt klagomål och svarar inom rimlig tid (vanligtvis 30 dagar). Om du inte är nöjd kan du klaga till", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "Vid ett kvalificerat dataintrång som kan orsaka allvarlig skada, meddelar vi berörda och OAIC enligt", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} är designat för universitetsstudenter vid {{uniName}}. Vi samlar inte medvetet in personuppgifter från barn under 16.",
  "privacy_s14_p1": "Vi kan uppdatera denna policy. Väsentliga ändringar kommuniceras via avisering i appen."
}

T["uk"] = {
  "privacy_back_to": "Назад до {{appName}}", "privacy_title": "Політика конфіденційності", "privacy_last_updated": "Останнє оновлення: 16 лютого 2026 (AEDT)",
  "privacy_s1_title": "Мета та сфера застосування", "privacy_s1_p1": "Ця Політика конфіденційності пояснює, як {{appName}} збирає, зберігає, використовує та розкриває особисту інформацію під час використання нашого сервісу.", "privacy_s1_p2": "{{appName}} — це інструмент для студентів {{uniName}}. Ця політика стосується всіх користувачів Сервісу.",
  "privacy_s2_title": "Яку особисту інформацію ми збираємо", "privacy_s2_a_title": "А) Дані облікового запису та ідентифікації", "privacy_s2_a_li1": "Повне ім'я (або відображуване ім'я)", "privacy_s2_a_li2": "Адреса електронної пошти", "privacy_s2_a_li3": "Пароль (зберігається як криптографічний хеш — ми ніколи не зберігаємо ваш пароль у відкритому тексті)", "privacy_s2_a_li4": "Студентський номер, спеціальність та рік навчання", "privacy_s2_a_li5": "Налаштування та уподобання облікового запису", "privacy_s2_a_li6": "Аватар профілю (якщо завантажено)", "privacy_s2_b_title": "Б) Дані багатофакторної автентифікації", "privacy_s2_b_li1": "Секрети реєстрації TOTP, зберігаються зашифровано з Cache-Control: no-store", "privacy_s2_b_li2": "Ідентифікатори облікових даних WebAuthn/passkey та публічні ключі (біометричні дані не зберігаються)", "privacy_s2_c_title": "В) Дані використання та пристрою", "privacy_s2_c_li1": "Тип пристрою, браузер, операційна система, мовне уподобання", "privacy_s2_c_li2": "IP-адреса (для обмеження швидкості та запобігання зловживанням)", "privacy_s2_c_li3": "Позначки часу та базові метадані запитів", "privacy_s2_c_li4": "Журнали помилок додатку та діагностика продуктивності (через Sentry)", "privacy_s2_d_title": "Г) Навчальний контент та розклад (надано користувачем)", "privacy_s2_d_li1": "Предмети/курси, розклади, дедлайни, нагадування та завдання", "privacy_s2_d_li2": "Події календаря та налаштування стрічки", "privacy_s2_e_title": "Д) Дані місцезнаходження (лише з вашого дозволу)", "privacy_s2_e_li1": "GPS-координати для карти кампусу та навігації", "privacy_s2_e_li2": "Дані місцезнаходження обробляються локально на вашому пристрої та не зберігаються на наших серверах", "privacy_s2_e_li3": "Ви можете відкликати дозвіл на місцезнаходження в будь-який час", "privacy_s2_f_title": "Е) Файли cookie та дані сеансу", "privacy_s2_f_li1": "Сеансові cookie (суворо необхідні для автентифікації)", "privacy_s2_f_li2": "Cookie безпеки (захист CSRF)", "privacy_s2_f_li3": "Cookie уподобань теми та мови",
  "privacy_s2_footer": "Ми не збираємо навмисно конфіденційну інформацію відповідно до Privacy Act без крайньої необхідності та вашої явної згоди.",
  "privacy_s3_p1": "Ми збираємо інформацію:", "privacy_s3_li1": "Безпосередньо від вас — при реєстрації, оновленні профілю, створенні контенту або зміні налаштувань", "privacy_s3_li2": "Автоматично — через сеансові cookie, журнали сервера та моніторинг помилок", "privacy_s3_footer": "Відповідно до APP 5, ми вживаємо розумних заходів для повідомлення вас під час збору даних.",
  "privacy_s4_p1": "Ми використовуємо особисту інформацію для:", "privacy_s4_li1": "Надання та роботи Сервісу", "privacy_s4_li2": "Персоналізації вашого досвіду", "privacy_s4_li3": "Підтримки безпеки", "privacy_s4_li4": "Покращення продуктивності та надійності", "privacy_s4_li5": "Спілкування з вами", "privacy_s4_li6": "Виконання юридичних зобов'язань", "privacy_s4_footer": "Ми збираємо лише розумно необхідну інформацію.",
  "privacy_s5_p1": "Ми можемо розкрити особисту інформацію:", "privacy_s5_li1": "Постачальникам послуг (див. розділ 6)", "privacy_s5_li2": "Органам влади, якщо цього вимагає закон", "privacy_s5_li3": "При бізнес-передачах з належним захистом", "privacy_s5_footer": "Ми не продаємо особисту інформацію.",
  "privacy_s6_p1": "Деякі постачальники можуть зберігати дані за межами Австралії. Ми вживаємо розумних заходів для відповідності APPs.", "privacy_s6_table_h2": "Мета", "privacy_s6_table_h3": "Регіон даних", "privacy_s6_table_r1_c2": "Автентифікація, база даних, зберігання файлів", "privacy_s6_table_r1_c3": "Налаштовано для проекту (AU/US/EU)", "privacy_s6_table_r2_c2": "Хостинг та CDN", "privacy_s6_table_r2_c3": "Глобальний edge (US основний)", "privacy_s6_table_r3_c2": "Моніторинг помилок та діагностика", "privacy_s6_table_r4_c2": "Маршрутизація навігації (лише серверна)", "privacy_s6_table_r4_c3": "ЄС (Німеччина)",
  "privacy_s7_p1": "Ми вживаємо розумних заходів для захисту особистої інформації. Наші заходи безпеки включають:", "privacy_s7_li1": "Шифрування при передачі (TLS/HTTPS через HSTS)", "privacy_s7_li2": "Шифрування в стані спокою для бази даних та файлів", "privacy_s7_li3": "Безпечне хешування паролів", "privacy_s7_li4": "Опції багатофакторної автентифікації (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "Контроль доступу на основі ролей", "privacy_s7_li6": "Обмеження швидкості та захист від brute-force", "privacy_s7_li7": "Content Security Policy (CSP) з nonces проти XSS", "privacy_s7_li8": "Безпека service worker: маршрути API ніколи не кешуються; всі кеші очищуються при виході", "privacy_s7_li9": "Автоматичне закінчення сеансу та безпечна обробка cookie", "privacy_s7_footer": "Жоден метод електронної передачі не є на 100% безпечним.",
  "privacy_s8_p1": "Ми зберігаємо особисту інформацію лише стільки, скільки необхідно для:", "privacy_s8_li1": "Надання Сервісу та підтримки облікового запису", "privacy_s8_li2": "Виконання юридичних зобов'язань", "privacy_s8_li3": "Вирішення спорів", "privacy_s8_li4": "Підтримки безпеки та цілісності аудиту", "privacy_s8_footer": "Коли ваші дані більше не потрібні, ми вживаємо заходів для їх видалення або анонімізації.",
  "privacy_s9_p1": "Ми використовуємо cookie для:", "privacy_s9_li1": "Підтримки вашого входу", "privacy_s9_li2": "Запам'ятовування ваших уподобань", "privacy_s9_li3": "Моніторингу помилок (через Sentry)", "privacy_s9_footer": "Ми не використовуємо рекламні cookie третіх сторін.",
  "privacy_s10_p1": "Відповідно до APPs 12 і 13, ви можете запитати доступ до своїх даних та їх виправлення.", "privacy_s10_p2_part1": "Ви можете переглядати та оновлювати свої дані в", "privacy_s10_p2_part2": "та", "privacy_s10_p2_part3": ". Для інших запитів зв'яжіться з нами за адресою", "privacy_s10_p2_part4": ". Може знадобитися підтвердження вашої особи.",
  "privacy_s11_p1_part1": "Якщо ви вважаєте, що ми порушили Australian Privacy Principles, ви можете подати скаргу на", "privacy_s11_p1_part2": "з деталями.", "privacy_s11_p2_part1": "Ми підтвердимо скаргу та відповімо протягом розумного часу (зазвичай 30 днів). Якщо ви незадоволені, можете звернутися до", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "У разі витоку даних, який може завдати серйозної шкоди, ми повідомимо постраждалих та OAIC відповідно до", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} призначений для студентів {{uniName}}. Ми свідомо не збираємо дані дітей до 16 років.",
  "privacy_s14_p1": "Ми можемо оновлювати цю політику. Суттєві зміни повідомлятимуться через повідомлення в додатку."
}

T["ne"] = {
  "privacy_back_to": "{{appName}} मा फर्कनुहोस्", "privacy_title": "गोपनीयता नीति", "privacy_last_updated": "अन्तिम अद्यावधिक: १६ फेब्रुअरी २०२६ (AEDT)",
  "privacy_s1_title": "उद्देश्य र दायरा", "privacy_s1_p1": "यो गोपनीयता नीतिले {{appName}} ले तपाईंको व्यक्तिगत जानकारी कसरी सङ्कलन, भण्डारण, प्रयोग र खुलासा गर्छ भनेर व्याख्या गर्दछ।", "privacy_s1_p2": "{{appName}} {{uniName}} का विद्यार्थीहरूका लागि विकसित गरिएको क्याम्पस उपकरण हो।",
  "privacy_s2_title": "हामी कुन व्यक्तिगत जानकारी सङ्कलन गर्छौं", "privacy_s2_a_title": "क) खाता र पहिचान डाटा", "privacy_s2_a_li1": "पूरा नाम (वा प्रदर्शन नाम)", "privacy_s2_a_li2": "इमेल ठेगाना", "privacy_s2_a_li3": "पासवर्ड (क्रिप्टोग्राफिक ह्यासको रूपमा भण्डारण गरिएको)", "privacy_s2_a_li4": "विद्यार्थी नम्बर, पाठ्यक्रम र अध्ययन वर्ष", "privacy_s2_a_li5": "खाता प्राथमिकता र सेटिङहरू", "privacy_s2_a_li6": "प्रोफाइल अवतार (अपलोड गरिएको भए)", "privacy_s2_b_title": "ख) बहु-कारक प्रमाणीकरण डाटा", "privacy_s2_b_li1": "TOTP दर्ता गोपनीयता, एन्क्रिप्ट गरी भण्डारण गरिएको", "privacy_s2_b_li2": "WebAuthn/passkey प्रमाण पत्र ID र सार्वजनिक कुञ्जीहरू", "privacy_s2_c_title": "ग) प्रयोग र उपकरण डाटा", "privacy_s2_c_li1": "उपकरण प्रकार, ब्राउजर, अपरेटिङ सिस्टम, भाषा प्राथमिकता", "privacy_s2_c_li2": "IP ठेगाना (सुरक्षा दर सीमितताका लागि)", "privacy_s2_c_li3": "समय स्ट्याम्प र आधारभूत अनुरोध मेटाडाटा", "privacy_s2_c_li4": "एप्लिकेसन त्रुटि लगहरू र प्रदर्शन निदान (Sentry मार्फत)", "privacy_s2_d_title": "घ) शिक्षण सामग्री (प्रयोगकर्ताद्वारा प्रदान)", "privacy_s2_d_li1": "विषयहरू, तालिकाहरू, समयसीमाहरू र कार्यहरू", "privacy_s2_d_li2": "क्यालेन्डर कार्यक्रमहरू र फिड प्राथमिकताहरू", "privacy_s2_e_title": "ङ) स्थान डाटा (तपाईंको अनुमतिमा मात्र)", "privacy_s2_e_li1": "क्याम्पस नक्सा र नेभिगेसनका लागि GPS निर्देशाङ्कहरू", "privacy_s2_e_li2": "स्थान डाटा तपाईंको उपकरणमा स्थानीय रूपमा प्रशोधन गरिन्छ", "privacy_s2_e_li3": "तपाईं स्थान अनुमति जुनसुकै बेला रद्द गर्न सक्नुहुन्छ", "privacy_s2_f_title": "च) कुकीहरू र सत्र डाटा", "privacy_s2_f_li1": "सत्र कुकीहरू (प्रमाणीकरणका लागि अनिवार्य)", "privacy_s2_f_li2": "सुरक्षा कुकीहरू (CSRF सुरक्षा)", "privacy_s2_f_li3": "थिम र भाषा प्राथमिकता कुकीहरू",
  "privacy_s2_footer": "हामी Privacy Act अनुसार संवेदनशील जानकारी जानाजानी सङ्कलन गर्दैनौं।",
  "privacy_s3_p1": "हामी जानकारी सङ्कलन गर्छौं:", "privacy_s3_li1": "तपाईंबाट सिधै — दर्ता, प्रोफाइल अद्यावधिक, सामग्री सिर्जना वा सेटिङ समायोजन गर्दा", "privacy_s3_li2": "स्वचालित रूपमा — सत्र कुकीहरू, सर्भर लगहरू र त्रुटि निगरानी मार्फत", "privacy_s3_footer": "APP 5 अनुसार, हामी सङ्कलनको समयमा वा पहिले सूचित गर्न उचित कदम चाल्छौं।",
  "privacy_s4_p1": "हामी व्यक्तिगत जानकारी प्रयोग गर्छौं:", "privacy_s4_li1": "सेवा प्रदान र सञ्चालन गर्न", "privacy_s4_li2": "तपाईंको अनुभव व्यक्तिगत बनाउन", "privacy_s4_li3": "सुरक्षा कायम राख्न", "privacy_s4_li4": "प्रदर्शन सुधार गर्न", "privacy_s4_li5": "तपाईंसँग सञ्चार गर्न", "privacy_s4_li6": "कानूनी दायित्व पूरा गर्न", "privacy_s4_footer": "हामी आवश्यक जानकारी मात्र सङ्कलन गर्छौं।",
  "privacy_s5_p1": "हामी व्यक्तिगत जानकारी खुलासा गर्न सक्छौं:", "privacy_s5_li1": "सेवा प्रदायकहरूलाई (खण्ड ६ हेर्नुहोस्)", "privacy_s5_li2": "कानूनद्वारा आवश्यक भएमा अधिकारीहरूलाई", "privacy_s5_li3": "व्यापार हस्तान्तरणमा उचित सुरक्षाका साथ", "privacy_s5_footer": "हामी व्यक्तिगत जानकारी बेच्दैनौं।",
  "privacy_s6_p1": "केही प्रदायकहरूले अस्ट्रेलिया बाहिर डाटा भण्डारण गर्न सक्छन्। हामी APPs सँग अनुपालन सुनिश्चित गर्न उचित कदम चाल्छौं।", "privacy_s6_table_h2": "उद्देश्य", "privacy_s6_table_h3": "डाटा क्षेत्र", "privacy_s6_table_r1_c2": "प्रमाणीकरण, डाटाबेस, फाइल भण्डारण", "privacy_s6_table_r1_c3": "प्रत्येक परियोजनाका लागि कन्फिगर गरिएको (AU/US/EU)", "privacy_s6_table_r2_c2": "होस्टिङ र CDN", "privacy_s6_table_r2_c3": "विश्वव्यापी edge (US प्राथमिक)", "privacy_s6_table_r3_c2": "त्रुटि निगरानी र प्रदर्शन निदान", "privacy_s6_table_r4_c2": "नेभिगेसन राउटिङ (सर्भर-साइड मात्र)", "privacy_s6_table_r4_c3": "EU (जर्मनी)",
  "privacy_s7_p1": "हामी व्यक्तिगत जानकारी सुरक्षित गर्न उचित कदम चाल्छौं। हाम्रा सुरक्षा उपायहरू:", "privacy_s7_li1": "ट्रान्जिटमा एन्क्रिप्सन (TLS/HTTPS HSTS मार्फत)", "privacy_s7_li2": "डाटाबेस र फाइलहरूका लागि विश्राममा एन्क्रिप्सन", "privacy_s7_li3": "सुरक्षित पासवर्ड ह्यासिङ", "privacy_s7_li4": "बहु-कारक प्रमाणीकरण विकल्पहरू (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "भूमिका-आधारित पहुँच नियन्त्रण", "privacy_s7_li6": "दर सीमितता र brute-force सुरक्षा", "privacy_s7_li7": "Content Security Policy (CSP) nonces सहित XSS रोक्न", "privacy_s7_li8": "Service worker सुरक्षा: API मार्गहरू क्यास गरिँदैन; लग आउटमा सबै क्यास हटाइन्छ", "privacy_s7_li9": "स्वचालित सत्र समाप्ति र सुरक्षित कुकी ह्यान्डलिङ", "privacy_s7_footer": "कुनै पनि इलेक्ट्रोनिक प्रसारण विधि १००% सुरक्षित छैन।",
  "privacy_s8_p1": "हामी व्यक्तिगत जानकारी आवश्यक भएसम्म मात्र राख्छौं:", "privacy_s8_li1": "सेवा प्रदान गर्न र खाता कायम राख्न", "privacy_s8_li2": "कानूनी दायित्व पूरा गर्न", "privacy_s8_li3": "विवाद समाधान गर्न", "privacy_s8_li4": "सुरक्षा र लेखापरीक्षा अखण्डता कायम राख्न", "privacy_s8_footer": "डाटा आवश्यक नभएमा हामी मेटाउने वा अज्ञात बनाउने कदम चाल्छौं।",
  "privacy_s9_p1": "हामी कुकीहरू प्रयोग गर्छौं:", "privacy_s9_li1": "तपाईंलाई लग इन राख्न", "privacy_s9_li2": "तपाईंका प्राथमिकताहरू सम्झन", "privacy_s9_li3": "त्रुटिहरू निगरानी गर्न (Sentry मार्फत)", "privacy_s9_footer": "हामी तेस्रो-पक्ष विज्ञापन कुकीहरू प्रयोग गर्दैनौं।",
  "privacy_s10_p1": "APPs 12 र 13 अनुसार, तपाईं आफ्नो डाटामा पहुँच र सुधार अनुरोध गर्न सक्नुहुन्छ।", "privacy_s10_p2_part1": "तपाईं आफ्नो जानकारी सिधै हेर्न र अद्यावधिक गर्न सक्नुहुन्छ", "privacy_s10_p2_part2": "र", "privacy_s10_p2_part3": "मा। अन्य अनुरोधहरूका लागि सम्पर्क गर्नुहोस्", "privacy_s10_p2_part4": "। पहिचान प्रमाणीकरण आवश्यक हुन सक्छ।",
  "privacy_s11_p1_part1": "यदि तपाईं विश्वास गर्नुहुन्छ कि हामीले Australian Privacy Principles उल्लङ्घन गरेका छौं, तपाईं गुनासो गर्न सक्नुहुन्छ", "privacy_s11_p1_part2": "विवरणहरूसहित।", "privacy_s11_p2_part1": "हामी गुनासो स्वीकार गर्नेछौं र ३० दिनभित्र जवाफ दिनेछौं। सन्तुष्ट नभएमा सम्पर्क गर्नुहोस्", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "गम्भीर क्षति हुन सक्ने डाटा उल्लङ्घनमा, हामी प्रभावित व्यक्ति र OAIC लाई सूचित गर्नेछौं", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} {{uniName}} का विद्यार्थीहरूका लागि डिजाइन गरिएको हो। हामी १६ वर्षमुनिका बालबालिकाबाट जानाजानी जानकारी सङ्कलन गर्दैनौं।",
  "privacy_s14_p1": "हामी यो नीति अद्यावधिक गर्न सक्छौं। महत्त्वपूर्ण परिवर्तनहरू एप भित्र सूचनाद्वारा सूचित गरिनेछ।"
}

T["si"] = {
  "privacy_back_to": "{{appName}} වෙත ආපසු", "privacy_title": "පෞද්ගලිකත්ව ප්‍රතිපත්තිය", "privacy_last_updated": "අවසන් යාවත්කාලීන: 2026 පෙබරවාරි 16 (AEDT)",
  "privacy_s1_title": "අරමුණ සහ විෂය පථය", "privacy_s1_p1": "මෙම පෞද්ගලිකත්ව ප්‍රතිපත්තිය {{appName}} ඔබේ පුද්ගලික තොරතුරු එකතු කරන, ගබඩා කරන, භාවිතා කරන සහ හෙළි කරන ආකාරය පැහැදිලි කරයි.", "privacy_s1_p2": "{{appName}} යනු {{uniName}} හි සිසුන් සඳහා සංවර්ධනය කරන ලද මණ්ඩල මෙවලමකි.",
  "privacy_s2_title": "අපි එකතු කරන පුද්ගලික තොරතුරු", "privacy_s2_a_title": "අ) ගිණුම් සහ හැඳුනුම් දත්ත", "privacy_s2_a_li1": "සම්පූර්ණ නම (හෝ සංදර්ශන නම)", "privacy_s2_a_li2": "විද්‍යුත් තැපැල් ලිපිනය", "privacy_s2_a_li3": "මුරපදය (ගුප්තකේතන hash ලෙස ගබඩා කෙරේ)", "privacy_s2_a_li4": "සිසු අංකය, පාඨමාලාව සහ අධ්‍යයන වසර", "privacy_s2_a_li5": "ගිණුම් මනාප සහ සැකසුම්", "privacy_s2_a_li6": "පැතිකඩ රූපය (උඩුගත කළහොත්)", "privacy_s2_b_title": "ආ) බහු-සාධක සත්‍යාපන දත්ත", "privacy_s2_b_li1": "TOTP ලියාපදිංචි රහස්, සංකේතනය කර ගබඩා කර ඇත", "privacy_s2_b_li2": "WebAuthn/passkey හැඳුනුම් සහ පොදු යතුරු", "privacy_s2_c_title": "ඇ) භාවිත සහ උපකරණ දත්ත", "privacy_s2_c_li1": "උපකරණ වර්ගය, බ්‍රව්සරය, මෙහෙයුම් පද්ධතිය, භාෂා මනාපය", "privacy_s2_c_li2": "IP ලිපිනය (ආරක්ෂක අනුපාත සීමාව සඳහා)", "privacy_s2_c_li3": "කාල මුද්‍රා සහ ඉල්ලීම් පාරදත්ත", "privacy_s2_c_li4": "යෙදුම් දෝෂ ලඝු-සටහන් සහ කාර්ය සාධන විශ්ලේෂණ (Sentry හරහා)", "privacy_s2_d_title": "ඈ) ඉගෙනුම් අන්තර්ගතය (පරිශීලක විසින් සපයනු ලැබේ)", "privacy_s2_d_li1": "මොඩියුල, කාලසටහන්, නියමිත දින, මතක්කිරීම් සහ කාර්යයන්", "privacy_s2_d_li2": "දින දර්ශන සිදුවීම් සහ පෝෂණ මනාප", "privacy_s2_e_title": "ඉ) ස්ථාන දත්ත (ඔබේ අවසරය සමග පමණි)", "privacy_s2_e_li1": "මණ්ඩල සිතියම සහ සංචාලනය සඳහා GPS ඛණ්ඩාංක", "privacy_s2_e_li2": "ස්ථාන දත්ත ඔබේ උපකරණයේ ස්ථානිකව සකසනු ලැබේ", "privacy_s2_e_li3": "ඔබට ඕනෑම වේලාවක ස්ථාන අවසරය අවලංගු කළ හැක", "privacy_s2_f_title": "ඊ) කුකීස් සහ සැසි දත්ත", "privacy_s2_f_li1": "සැසි කුකීස් (සත්‍යාපනය සඳහා අත්‍යවශ්‍යයි)", "privacy_s2_f_li2": "ආරක්ෂණ කුකීස් (CSRF ආරක්ෂාව)", "privacy_s2_f_li3": "තේමා සහ භාෂා මනාප කුකීස්",
  "privacy_s2_footer": "Privacy Act යටතේ සංවේදී තොරතුරු අපි හිතාමතා එකතු නොකරමු.",
  "privacy_s3_p1": "අපි තොරතුරු එකතු කරමු:", "privacy_s3_li1": "ඔබෙන් කෙලින්ම — ලියාපදිංචි වන විට, පැතිකඩ යාවත්කාලීන කරන විට, අන්තර්ගතය සාදන විට", "privacy_s3_li2": "ස්වයංක්‍රීයව — සැසි කුකීස්, සේවාදායක ලඝු-සටහන් සහ දෝෂ නිරීක්ෂණය හරහා", "privacy_s3_footer": "APP 5 අනුව, අපි එකතු කිරීමේ අවස්ථාවේ ඔබට දැනුම් දීමට පියවර ගනිමු.",
  "privacy_s4_p1": "අපි පුද්ගලික තොරතුරු භාවිතා කරමු:", "privacy_s4_li1": "සේවාව සැපයීම සහ ක්‍රියාත්මක කිරීම", "privacy_s4_li2": "ඔබේ අත්දැකීම පුද්ගලීකරණය කිරීම", "privacy_s4_li3": "ආරක්ෂාව පවත්වා ගැනීම", "privacy_s4_li4": "කාර්ය සාධනය වැඩි දියුණු කිරීම", "privacy_s4_li5": "ඔබ සමග සන්නිවේදනය", "privacy_s4_li6": "නීතිමය බැඳීම් ඉටු කිරීම", "privacy_s4_footer": "අපි අවශ්‍ය තොරතුරු පමණක් එකතු කරමු.",
  "privacy_s5_p1": "අපි පුද්ගලික තොරතුරු හෙළි කළ හැක:", "privacy_s5_li1": "සේවා සැපයුම්කරුවන්ට (6 වන කොටස බලන්න)", "privacy_s5_li2": "නීතියෙන් අවශ්‍ය නම් අධිකාරීන්ට", "privacy_s5_li3": "ව්‍යාපාර මාරුවේදී සුදුසු ආරක්ෂාව සමග", "privacy_s5_footer": "අපි පුද්ගලික තොරතුරු විකුණන්නේ නැත.",
  "privacy_s6_p1": "සමහර සැපයුම්කරුවන් ඕස්ට්‍රේලියාවෙන් පිටත දත්ත ගබඩා කළ හැක. APPs අනුකූලතාව සහතික කිරීමට අපි පියවර ගනිමු.", "privacy_s6_table_h2": "අරමුණ", "privacy_s6_table_h3": "දත්ත කලාපය", "privacy_s6_table_r1_c2": "සත්‍යාපනය, දත්ත සමුදාය, ගොනු ගබඩාව", "privacy_s6_table_r1_c3": "ව්‍යාපෘතිය අනුව වින්‍යාස කර ඇත (AU/US/EU)", "privacy_s6_table_r2_c2": "සත්කාරක සේවය සහ CDN", "privacy_s6_table_r2_c3": "ගෝලීය edge (US ප්‍රාථමික)", "privacy_s6_table_r3_c2": "දෝෂ නිරීක්ෂණය සහ විශ්ලේෂණ", "privacy_s6_table_r4_c2": "සංචාලන මාර්ගකරණය (සේවාදායක පැත්ත පමණි)", "privacy_s6_table_r4_c3": "EU (ජර්මනිය)",
  "privacy_s7_p1": "පුද්ගලික තොරතුරු ආරක්ෂා කිරීමට අපි පියවර ගනිමු:", "privacy_s7_li1": "සම්ප්‍රේෂණයේදී සංකේතනය (TLS/HTTPS HSTS හරහා)", "privacy_s7_li2": "විවේකයේ සංකේතනය", "privacy_s7_li3": "ආරක්ෂිත මුරපද හැෂිං", "privacy_s7_li4": "බහු-සාධක සත්‍යාපන විකල්ප (TOTP, WebAuthn/passkeys)", "privacy_s7_li5": "භූමිකා-පදනම් ප්‍රවේශ පාලනය", "privacy_s7_li6": "අනුපාත සීමාව සහ brute-force ආරක්ෂාව", "privacy_s7_li7": "Content Security Policy (CSP) nonces සමග XSS වැළැක්වීම", "privacy_s7_li8": "Service worker ආරක්ෂාව: API මාර්ග කැෂ් නොකරයි; පිටවීමේදී සියලු කැෂ් මකනු ලැබේ", "privacy_s7_li9": "ස්වයංක්‍රීය සැසි කල් ඉකුත් වීම සහ ආරක්ෂිත කුකී හැසිරවීම", "privacy_s7_footer": "කිසිදු ඉලෙක්ට්‍රොනික සම්ප්‍රේෂණ ක්‍රමයක් 100% ආරක්ෂිත නැත.",
  "privacy_s8_p1": "අපි පුද්ගලික තොරතුරු අවශ්‍ය කාලය පමණක් තබා ගනිමු:", "privacy_s8_li1": "සේවාව සැපයීම", "privacy_s8_li2": "නීතිමය බැඳීම් ඉටු කිරීම", "privacy_s8_li3": "ආරවුල් විසඳීම", "privacy_s8_li4": "ආරක්ෂාව පවත්වා ගැනීම", "privacy_s8_footer": "දත්ත තවදුරටත් අවශ්‍ය නැති විට මකනු හෝ නිර්නාමික කරනු ලැබේ.",
  "privacy_s9_p1": "අපි කුකීස් භාවිතා කරමු:", "privacy_s9_li1": "ඔබව පිවිසී තබා ගැනීමට", "privacy_s9_li2": "ඔබේ මනාප මතක තබා ගැනීමට", "privacy_s9_li3": "දෝෂ නිරීක්ෂණය කිරීමට (Sentry හරහා)", "privacy_s9_footer": "අපි තෙවන-පාර්ශවික දැන්වීම් කුකීස් භාවිතා නොකරමු.",
  "privacy_s10_p1": "APPs 12 සහ 13 යටතේ, ඔබට ඔබේ දත්ත වෙත ප්‍රවේශය සහ නිවැරදි කිරීම ඉල්ලිය හැක.", "privacy_s10_p2_part1": "ඔබට ඔබේ තොරතුරු කෙලින්ම බැලිය හැක", "privacy_s10_p2_part2": "සහ", "privacy_s10_p2_part3": " හි. වෙනත් ඉල්ලීම් සඳහා අපව සම්බන්ධ කර ගන්න", "privacy_s10_p2_part4": ". හැඳුනුම්පත් තහවුරු කිරීම අවශ්‍ය විය හැක.",
  "privacy_s11_p1_part1": "ඔබ Australian Privacy Principles උල්ලංඝනය කර ඇතැයි සිතන්නේ නම්, ඔබට පැමිණිල්ලක් ඉදිරිපත් කළ හැක", "privacy_s11_p1_part2": "විස්තර සමග.", "privacy_s11_p2_part1": "අපි පැමිණිල්ල තහවුරු කර දින 30 ක් ඇතුළත පිළිතුරු දෙමු. සෑහීමකට පත් නොවන්නේ නම්", "privacy_s11_p2_link": "Office of the Australian Information Commissioner (OAIC)",
  "privacy_s12_p1_part1": "බරපතල හානියක් ඇති කළ හැකි දත්ත කඩවීමකදී, අපි බලපෑමට ලක් වූවන්ට සහ OAIC වෙත දැනුම් දෙමු", "privacy_s12_p1_link": "Notifiable Data Breaches (NDB) scheme",
  "privacy_s13_p1": "{{appName}} {{uniName}} හි සරසවි සිසුන් සඳහා නිර්මාණය කර ඇත. වයස අවුරුදු 16 ට අඩු ළමුන්ගෙන් දැනුවත්ව තොරතුරු එකතු නොකරමු.",
  "privacy_s14_p1": "අපට මෙම ප්‍රතිපත්තිය යාවත්කාලීන කළ හැක. සැලකිය යුතු වෙනස්කම් යෙදුම තුළ දැනුම්දීමක් හරහා සන්නිවේදනය කරනු ලැබේ."
}

for locale, data in T.items():
    fp = os.path.join(PATCHES_DIR, f"{locale}.json")
    with open(fp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"  Written {fp} ({len(data)} keys)")

print(f"\nDone. Written {len(T)} patch files.")

