import type { TranslationKey } from '@/lib/i18n/translations';

// Geographic coordinates from OpenStreetMap
export type GeoLocation = {
  lat: number;
  lng: number;
  osmId?: number; // OpenStreetMap ID for attribution
};

export type Building = {
  id: string;
  name: string;
  position: [number, number]; // [x, y] pixel coordinates for map placement
  description?: string;
  tags?: string[];
  translationKey: TranslationKey;
  descriptionKey: TranslationKey;
  gridRef?: string; // Campus map grid reference (e.g., 'N16', 'O22')
  address?: string; // Physical address on campus
  category?: BuildingCategory;
  location?: GeoLocation; // Real-world GPS coordinates from OSM
  levels?: number; // Number of floors
  wheelchair?: boolean; // Wheelchair accessible
};

export type BuildingCategory =
  | 'academic'
  | 'services'
  | 'health'
  | 'food'
  | 'sports'
  | 'venue'
  | 'research'
  | 'residential'
  | 'other';

// Grid reference to approximate pixel position mapping
// The campus map uses a grid system (columns A-X, rows 1-30 approx)
// Map dimensions: 4678 x 3307 pixels
// These are approximate conversions based on the campus layout
const gridToPixel = (ref: string): [number, number] => {
  // Extract column letter(s) and row number
  const match = ref.match(/^([A-Z]+)(\d+)$/);
  if (!match) return [2339, 1654]; // Center fallback

  const colStr = match[1];
  const row = parseInt(match[2], 10);

  // Column mapping (A=1, B=2, ... X=24)
  // Campus spans roughly columns C to W (3 to 23)
  let col = 0;
  for (let i = 0; i < colStr.length; i++) {
    col = col * 26 + (colStr.charCodeAt(i) - 64);
  }

  // Map grid to pixels
  // Approximate: columns span ~200px each, rows span ~110px each
  // Grid starts around column C (3) at x~200 and goes to W (23) at x~4400
  // Grid starts around row 5 at y~300 and goes to row 30 at y~3100

  const x = Math.round(((col - 3) / 20) * 4200 + 200);
  const y = Math.round(((row - 5) / 25) * 2800 + 300);

  // Clamp to map bounds
  return [Math.max(100, Math.min(4578, x)), Math.max(100, Math.min(3207, y))];
};

export const buildings: Building[] = [
  // KEY SERVICE LOCATIONS
  {
    id: '18WW',
    name: "18 Wally's Walk (Central Hub)",
    position: gridToPixel('N16'),
    description:
      'Main student services building housing Service Connect, IT, HR, Financial Services, and administration offices.',
    tags: ['services', 'administration', 'study'],
    translationKey: 'building_18WW_name',
    descriptionKey: 'building_18WW_desc',
    gridRef: 'N16',
    address: "18 Wally's Walk",
    category: 'services',
    location: { lat: -33.774021, lng: 151.11261, osmId: 205588336 },
    levels: 4,
  },
  {
    id: 'LIB',
    name: 'Waranara Library',
    position: gridToPixel('Q17'),
    description:
      'Main campus library with extensive collections, study spaces, Library Cafe, and the Lachlan Macquarie Room.',
    tags: ['academic', 'study', 'resources'],
    translationKey: 'building_LIB_name',
    descriptionKey: 'building_LIB_desc',
    gridRef: 'Q17',
    address: '16 Macquarie Walk',
    category: 'academic',
    location: { lat: -33.775705, lng: 151.113082, osmId: 141281549 },
    levels: 8,
  },
  {
    id: 'SEC',
    name: 'Security & Emergency',
    position: gridToPixel('P2'),
    description: 'Campus security headquarters and emergency first aid services. Available 24/7.',
    tags: ['services', 'safety', 'emergency'],
    translationKey: 'building_SEC_name',
    descriptionKey: 'building_SEC_desc',
    gridRef: 'P2',
    address: '4 Link Road',
    category: 'services',
  },

  // FACULTY OF ARTS
  {
    id: '25BWW',
    name: "25B Wally's Walk (Arts Faculty)",
    position: gridToPixel('O13'),
    description:
      'Faculty of Arts administration, Education, Social Sciences, Indigenous Studies, History, and the Gale History Museum.',
    tags: ['academic', 'arts', 'teaching'],
    translationKey: 'building_25BWW_name',
    descriptionKey: 'building_25BWW_desc',
    gridRef: 'O13',
    address: "25B Wally's Walk",
    category: 'academic',
    location: { lat: -33.774873, lng: 151.110937, osmId: 458998300 },
  },
  {
    id: '17WW',
    name: "17 Wally's Walk (Law & Media)",
    position: gridToPixel('O19'),
    description: 'Macquarie Law School, Media & Communication, Michael Kirby Law Building.',
    tags: ['academic', 'law', 'media'],
    translationKey: 'building_17WW_name',
    descriptionKey: 'building_17WW_desc',
    gridRef: 'O19',
    address: "17 Wally's Walk, Macquarie Park, NSW",
    category: 'academic',
    location: { lat: -33.774709, lng: 151.11334, osmId: 7867502 },
    levels: 3,
  },

  // MACQUARIE BUSINESS SCHOOL
  {
    id: '4ER',
    name: '4 Eastern Road (Business School)',
    position: gridToPixel('Q22'),
    description:
      'Macquarie Business School - Accounting, Finance, Management, Marketing, Actuarial Studies.',
    tags: ['academic', 'business', 'teaching'],
    translationKey: 'building_4ER_name',
    descriptionKey: 'building_4ER_desc',
    gridRef: 'Q22',
    address: '4 Eastern Road',
    category: 'academic',
    location: { lat: -33.775808, lng: 151.115985, osmId: 51673946 },
    levels: 8,
  },

  // FACULTY OF MEDICINE, HEALTH & HUMAN SCIENCES
  {
    id: '75TAL',
    name: '75 Talavera Road (Health Sciences)',
    position: gridToPixel('M28'),
    description:
      'Faculty of Medicine, Health Sciences, Medical School, Australian Institute of Health Innovation, Chiropractic.',
    tags: ['academic', 'health', 'research'],
    translationKey: 'building_75TAL_name',
    descriptionKey: 'building_75TAL_desc',
    gridRef: 'M28',
    address: '75 Talavera Road, Macquarie Park, NSW',
    category: 'academic',
    location: { lat: -33.774163, lng: 151.118636, osmId: 23716719 },
  },
  {
    id: '16UA',
    name: '16 University Avenue (Psychology)',
    position: gridToPixel('T14'),
    description:
      'Psychology, Linguistics, Speech & Hearing Clinic, Reading Clinic, Centre for Emotional Health.',
    tags: ['academic', 'psychology', 'health'],
    translationKey: 'building_16UA_name',
    descriptionKey: 'building_16UA_desc',
    gridRef: 'T14',
    address: '16 University Avenue',
    category: 'academic',
    location: { lat: -33.776499, lng: 151.111815, osmId: 271661421 },
  },

  // FACULTY OF SCIENCE & ENGINEERING
  {
    id: '9WW',
    name: "9 Wally's Walk (Engineering)",
    position: gridToPixel('O22'),
    description: 'School of Engineering, Australian Astronomical Optics.',
    tags: ['academic', 'engineering', 'labs'],
    translationKey: 'building_9WW_name',
    descriptionKey: 'building_9WW_desc',
    gridRef: 'O22',
    address: "9 Wally's Walk",
    category: 'academic',
  },
  {
    id: '4RPD',
    name: '4 Research Park Drive (Computing)',
    position: gridToPixel('O26'),
    description: 'School of Computing, Esc Cafe.',
    tags: ['academic', 'technology', 'labs'],
    translationKey: 'building_4RPD_name',
    descriptionKey: 'building_4RPD_desc',
    gridRef: 'O26',
    address: '4 Research Park Drive',
    category: 'academic',
    location: { lat: -33.774839, lng: 151.117814, osmId: 324612875 },
  },
  {
    id: '12WW',
    name: "12 Wally's Walk (Maths & Physics)",
    position: gridToPixel('N20'),
    description: 'School of Mathematical & Physical Sciences.',
    tags: ['academic', 'science', 'research'],
    translationKey: 'building_12WW_name',
    descriptionKey: 'building_12WW_desc',
    gridRef: 'N20',
    address: "12 Wally's Walk",
    category: 'academic',
    location: { lat: -33.775174, lng: 151.114141, osmId: 1192234871 },
  },
  {
    id: '6WW',
    name: "6 Wally's Walk (Natural Sciences)",
    position: gridToPixel('M23'),
    description: 'School of Natural Sciences, Biological Sciences, Herbarium.',
    tags: ['academic', 'science', 'research'],
    translationKey: 'building_6WW_name',
    descriptionKey: 'building_6WW_desc',
    gridRef: 'M23',
    address: "6 Wally's Walk",
    category: 'academic',
    location: { lat: -33.774152, lng: 151.116117, osmId: 157975718 },
    levels: 3,
  },
  {
    id: '4WW',
    name: "4 Wally's Walk (Proteome)",
    position: gridToPixel('M24'),
    description: 'Australian Proteome Analysis Facility.',
    tags: ['academic', 'research', 'labs'],
    translationKey: 'building_4WW_name',
    descriptionKey: 'building_4WW_desc',
    gridRef: 'M24',
    address: "4 Wally's Walk",
    category: 'research',
    location: { lat: -33.774109, lng: 151.116726, osmId: 459015462 },
  },

  // VENUES & THEATRES
  {
    id: 'LOTUS',
    name: 'Lotus Theatre',
    position: gridToPixel('O11'),
    description: 'Major teaching and entertainment venue.',
    tags: ['venue', 'teaching', 'events'],
    translationKey: 'building_LOTUS_name',
    descriptionKey: 'building_LOTUS_desc',
    gridRef: 'O11',
    address: "27 Wally's Walk",
    category: 'venue',
    location: { lat: -33.774631, lng: 151.110656, osmId: 455246542 },
  },
  {
    id: 'MQTH',
    name: 'Macquarie Theatre',
    position: gridToPixel('O15'),
    description: 'Large lecture theatre and entertainment venue.',
    tags: ['venue', 'teaching', 'events'],
    translationKey: 'building_MQTH_name',
    descriptionKey: 'building_MQTH_desc',
    gridRef: 'O15',
    address: "21 Wally's Walk",
    category: 'venue',
    location: { lat: -33.77466, lng: 151.11228, osmId: 458998304 },
  },
  {
    id: 'PRICE',
    name: 'Price Theatre',
    position: gridToPixel('O14'),
    description: 'Teaching theatre.',
    tags: ['venue', 'teaching'],
    translationKey: 'building_PRICE_name',
    descriptionKey: 'building_PRICE_desc',
    gridRef: 'O14',
    address: "23 Wally's Walk",
    category: 'venue',
    location: { lat: -33.774655, lng: 151.11174, osmId: 458998303 },
  },
  {
    id: 'LIGHT',
    name: 'Lighthouse Theatre',
    position: gridToPixel('H14'),
    description: 'Performance venue.',
    tags: ['venue', 'performance', 'arts'],
    translationKey: 'building_LIGHT_name',
    descriptionKey: 'building_LIGHT_desc',
    gridRef: 'H14',
    address: '11 Gymnasium Road',
    category: 'venue',
    location: { lat: -33.772283, lng: 151.111919, osmId: 205588350 },
  },
  {
    id: 'AINS',
    name: 'Ainsworth Building',
    position: gridToPixel('N27'),
    description: 'Teaching facility.',
    tags: ['academic', 'teaching'],
    translationKey: 'building_AINS_name',
    descriptionKey: 'building_AINS_desc',
    gridRef: 'N27',
    address: "1 Wally's Walk",
    category: 'academic',
    location: { lat: -33.774218, lng: 151.118133, osmId: 1303624871 },
  },

  // MQ HEALTH
  {
    id: 'HOSP',
    name: 'MQ University Hospital',
    position: gridToPixel('L27'),
    description: 'Teaching hospital with specialist clinics, medical imaging, and pharmacy.',
    tags: ['health', 'medical', 'services'],
    translationKey: 'building_HOSP_name',
    descriptionKey: 'building_HOSP_desc',
    gridRef: 'L27',
    address: '3 Technology Place',
    category: 'health',
    location: { lat: -33.773819, lng: 151.118075, osmId: 459015460 },
    wheelchair: true,
  },
  {
    id: 'CLINIC',
    name: 'GP & Physio Clinics',
    position: gridToPixel('K26'),
    description: 'General practice and physiotherapy clinics, specialist consultations.',
    tags: ['health', 'medical', 'services'],
    translationKey: 'building_CLINIC_name',
    descriptionKey: 'building_CLINIC_desc',
    gridRef: 'K26',
    address: '2 Technology Place',
    category: 'health',
    location: { lat: -33.773038, lng: 151.117681, osmId: 459015453 },
    wheelchair: true,
  },
  {
    id: 'WOOL',
    name: 'Woolcock Institute',
    position: gridToPixel('O30'),
    description: 'Woolcock Institute of Medical Research.',
    tags: ['health', 'research'],
    translationKey: 'building_WOOL_name',
    descriptionKey: 'building_WOOL_desc',
    gridRef: 'O30',
    address: '2 Innovation Road',
    category: 'research',
  },

  // SPORTS & RECREATION
  {
    id: 'SPORT',
    name: 'Sport & Aquatic Centre',
    position: gridToPixel('J12'),
    description:
      'Gym, swimming pool, sports facilities, Crunch Cafe, Sporting Hall of Fame Museum.',
    tags: ['sports', 'recreation', 'fitness'],
    translationKey: 'building_Sports_name',
    descriptionKey: 'building_Sports_desc',
    gridRef: 'J12',
    address: '10 Gymnasium Road',
    category: 'sports',
    location: { lat: -33.772661, lng: 151.110771, osmId: 205588367 },
    wheelchair: true,
  },
  {
    id: 'FIELDS',
    name: 'Sports Fields & Tennis',
    position: gridToPixel('K16'),
    description: 'Outdoor sports fields and tennis centre.',
    tags: ['sports', 'recreation', 'outdoor'],
    translationKey: 'building_FIELDS_name',
    descriptionKey: 'building_FIELDS_desc',
    gridRef: 'K16',
    address: '15-17 Gymnasium Road',
    category: 'sports',
  },

  // FOOD & RETAIL
  {
    id: 'UBAR',
    name: 'UBar & Central Courtyard',
    position: gridToPixel('K18'),
    description: 'Campus bar, social venue, graduation ceremonies area.',
    tags: ['food', 'social', 'events'],
    translationKey: 'building_UBAR_name',
    descriptionKey: 'building_UBAR_desc',
    gridRef: 'K18',
    address: '1 Central Courtyard',
    category: 'food',
    location: { lat: -33.773263, lng: 151.113652, osmId: 914350786 },
  },
  {
    id: 'CULT',
    name: 'Cult Eatery',
    position: gridToPixel('O13'),
    description: 'Campus eatery in Arts precinct.',
    tags: ['food', 'cafe'],
    translationKey: 'building_CULT_name',
    descriptionKey: 'building_CULT_desc',
    gridRef: 'O13',
    address: "25B Wally's Walk",
    category: 'food',
  },
  {
    id: 'LACH',
    name: "Lachlan's Restaurant",
    position: gridToPixel('E23'),
    description: 'Fine dining restaurant.',
    tags: ['food', 'restaurant'],
    translationKey: 'building_LACH_name',
    descriptionKey: 'building_LACH_desc',
    gridRef: 'E23',
    address: '1 Executive Road',
    category: 'food',
    location: { lat: -33.771289, lng: 151.11605, osmId: 148387967 },
  },

  // OTHER SERVICES
  {
    id: '8SCO',
    name: '8 Sir Christopher Ondaatje Ave',
    position: gridToPixel('P20'),
    description:
      'Future Students, MQ College, MQ Academy, Prayer Room, IELTS/PTE Test Centre, Access & Widening Participation.',
    tags: ['services', 'student', 'administration'],
    translationKey: 'building_8SCO_name',
    descriptionKey: 'building_8SCO_desc',
    gridRef: 'P20',
    address: '8 Sir Christopher Ondaatje Ave, Macquarie Park, NSW',
    category: 'services',
    location: { lat: -33.77557, lng: 151.114936, osmId: 23716703 },
    levels: 4,
  },
  {
    id: '16WW',
    name: "16 Wally's Walk (Research)",
    position: gridToPixel('N18'),
    description: 'Graduate Research Academy, Research Services, Commercialisation & Innovation.',
    tags: ['research', 'services'],
    translationKey: 'building_16WW_name',
    descriptionKey: 'building_16WW_desc',
    gridRef: 'N18',
    address: "16 Wally's Walk",
    category: 'research',
    location: { lat: -33.774231, lng: 151.113649, osmId: 205588359 },
  },
  {
    id: '12SW',
    name: '12 Second Way (Student Services)',
    position: gridToPixel('P16'),
    description: 'Student Wellbeing, Student Engagement, Graduation Unit.',
    tags: ['services', 'student', 'wellbeing'],
    translationKey: 'building_12SW_name',
    descriptionKey: 'building_12SW_desc',
    gridRef: 'P16',
    address: '12 Second Way',
    category: 'services',
    location: { lat: -33.775059, lng: 151.113014, osmId: 458998306 },
  },
  {
    id: '19ER',
    name: '19 Eastern Road (Chancellery)',
    position: gridToPixel('H20'),
    description: 'Chancellery, Archives & Records, Art Gallery.',
    tags: ['administration', 'gallery', 'arts'],
    translationKey: 'building_19ER_name',
    descriptionKey: 'building_19ER_desc',
    gridRef: 'H20',
    address: '19 Eastern Road',
    category: 'services',
    location: { lat: -33.77242, lng: 151.114854, osmId: 205588364 },
  },
  {
    id: 'OBS',
    name: 'Observatory',
    position: gridToPixel('C12'),
    description: 'Astronomy observatory.',
    tags: ['research', 'science', 'astronomy'],
    translationKey: 'building_OBS_name',
    descriptionKey: 'building_OBS_desc',
    gridRef: 'C12',
    address: '5 Gymnasium Road',
    category: 'research',
    location: { lat: -33.770357, lng: 151.111125, osmId: 1192242193 },
  },
  {
    id: 'INCUB',
    name: 'MQ Incubator',
    position: gridToPixel('S8'),
    description: 'Macquarie University Incubator for startups.',
    tags: ['services', 'business', 'innovation'],
    translationKey: 'building_INCUB_name',
    descriptionKey: 'building_INCUB_desc',
    gridRef: 'S8',
    address: '8 Hadenfeld Avenue',
    category: 'services',
    location: { lat: -33.776162, lng: 151.109078, osmId: 1107882877 },
  },
  {
    id: 'CHAP',
    name: 'Chaplaincy',
    position: gridToPixel('R6'),
    description: 'Multi-faith chaplaincy services.',
    tags: ['services', 'spiritual'],
    translationKey: 'building_CHAP_name',
    descriptionKey: 'building_CHAP_desc',
    gridRef: 'R6',
    address: '10 Hadenfeld Avenue',
    category: 'services',
    location: { lat: -33.776044, lng: 151.108066, osmId: 100955278 },
    levels: 3,
  },
  {
    id: 'WALU',
    name: 'Walanga Muru',
    position: gridToPixel('N11'),
    description: 'Indigenous student support and cultural services.',
    tags: ['services', 'indigenous', 'culture'],
    translationKey: 'building_WALU_name',
    descriptionKey: 'building_WALU_desc',
    gridRef: 'N11',
    address: "29 Wally's Walk",
    category: 'services',
    location: { lat: -33.774513, lng: 151.110334, osmId: 455246541 },
  },

  // CHILDCARE
  {
    id: 'BANK',
    name: 'Banksia Cottage (Childcare)',
    position: gridToPixel('P8'),
    description: 'Campus childcare facility.',
    tags: ['services', 'childcare'],
    translationKey: 'building_BANK_name',
    descriptionKey: 'building_BANK_desc',
    gridRef: 'P8',
    address: '8 Link Road, Macquarie Park, NSW',
    category: 'services',
    location: { lat: -33.775158, lng: 151.108997, osmId: 148389594 },
  },
  {
    id: 'GUMNUT',
    name: 'Gumnut Cottage (Childcare)',
    position: gridToPixel('V15'),
    description: 'Campus childcare facility.',
    tags: ['services', 'childcare'],
    translationKey: 'building_GUMNUT_name',
    descriptionKey: 'building_GUMNUT_desc',
    gridRef: 'V15',
    address: '17 University Avenue',
    category: 'services',
  },
  {
    id: 'MIAMIA',
    name: 'Mia Mia (Childcare)',
    position: gridToPixel('N11'),
    description: 'Campus childcare facility near Walanga Muru.',
    tags: ['services', 'childcare'],
    translationKey: 'building_MIAMIA_name',
    descriptionKey: 'building_MIAMIA_desc',
    gridRef: 'N11',
    address: "29 Wally's Walk",
    category: 'services',
  },
  {
    id: 'WARATAH',
    name: 'Waratah (Childcare)',
    position: gridToPixel('W17'),
    description: 'Campus childcare facility.',
    tags: ['services', 'childcare'],
    translationKey: 'building_WARATAH_name',
    descriptionKey: 'building_WARATAH_desc',
    gridRef: 'W17',
    address: '11 University Avenue',
    category: 'services',
  },

  // NEXTSENSE & SPECIALIST SERVICES
  {
    id: 'NEXTSENSE',
    name: 'NextSense Centre of Excellence',
    position: gridToPixel('F9'),
    description: 'NextSense Centre of Excellence for hearing, vision, and sensory research.',
    tags: ['services', 'health', 'research'],
    translationKey: 'building_NEXTSENSE_name',
    descriptionKey: 'building_NEXTSENSE_desc',
    gridRef: 'F9',
    address: '2 Gymnasium Road',
    category: 'research',
  },
  {
    id: 'NEXTSCHOOL',
    name: 'NextSense School',
    position: gridToPixel('G7'),
    description: 'NextSense School for deaf and vision impaired students.',
    tags: ['services', 'education', 'accessibility'],
    translationKey: 'building_NEXTSCHOOL_name',
    descriptionKey: 'building_NEXTSCHOOL_desc',
    gridRef: 'G7',
    address: '131 Culloden Road',
    category: 'academic',
  },
  {
    id: 'METS',
    name: 'METS (Engineering Services)',
    position: gridToPixel('K24'),
    description: 'Macquarie Engineering Technical Services - workshop and technical support.',
    tags: ['services', 'engineering', 'workshop'],
    translationKey: 'building_METS_name',
    descriptionKey: 'building_METS_desc',
    gridRef: 'K24',
    address: '3 Science Road',
    category: 'services',
    location: { lat: -33.773313, lng: 151.116659, osmId: 23716725 },
  },

  // ADDITIONAL CAFES
  {
    id: 'WALLYS',
    name: "Wally's Coffee and Toasties",
    position: gridToPixel('N15'),
    description: 'Campus cafe in the Central Hub building.',
    tags: ['food', 'cafe', 'coffee'],
    translationKey: 'building_WALLYS_name',
    descriptionKey: 'building_WALLYS_desc',
    gridRef: 'N15',
    address: "18 Wally's Walk",
    category: 'food',
  },
  {
    id: 'LIBCAFE',
    name: 'Library Cafe',
    position: gridToPixel('Q17'),
    description: 'Cafe located in Waranara Library.',
    tags: ['food', 'cafe', 'coffee'],
    translationKey: 'building_LIBCAFE_name',
    descriptionKey: 'building_LIBCAFE_desc',
    gridRef: 'Q17',
    address: '16 Macquarie Walk',
    category: 'food',
  },

  // RESIDENTIAL
  {
    id: 'DLC',
    name: 'Dunmore Lang College',
    position: gridToPixel('W25'),
    description: 'Student residential college.',
    tags: ['residential', 'accommodation'],
    translationKey: 'building_DLC_name',
    descriptionKey: 'building_DLC_desc',
    gridRef: 'W25',
    address: '130 Herring Road',
    category: 'residential',
    location: { lat: -33.77817, lng: 151.11606, osmId: 488128858 },
  },
  {
    id: 'RMC',
    name: 'Robert Menzies College',
    position: gridToPixel('V26'),
    description: 'Student residential college.',
    tags: ['residential', 'accommodation'],
    translationKey: 'building_RMC_name',
    descriptionKey: 'building_RMC_desc',
    gridRef: 'V26',
    address: '136 Herring Road',
    category: 'residential',
  },
  {
    id: 'MQV',
    name: 'MQ Village',
    position: gridToPixel('F7'),
    description: 'Student accommodation village.',
    tags: ['residential', 'accommodation'],
    translationKey: 'building_MQV_name',
    descriptionKey: 'building_MQV_desc',
    gridRef: 'F7',
    address: '122 Culloden Road',
    category: 'residential',
  },

  // MUSEUMS & GALLERIES
  {
    id: 'GALLERY',
    name: 'Art Gallery',
    position: gridToPixel('H20'),
    description: 'University art gallery and exhibitions.',
    tags: ['arts', 'gallery', 'culture'],
    translationKey: 'building_GALLERY_name',
    descriptionKey: 'building_GALLERY_desc',
    gridRef: 'H20',
    address: '19 Eastern Road',
    category: 'venue',
  },
  {
    id: 'BIODISC',
    name: 'Biology Discovery Centre',
    position: gridToPixel('L23'),
    description: 'Biology museum and discovery centre.',
    tags: ['science', 'museum', 'education'],
    translationKey: 'building_BIODISC_name',
    descriptionKey: 'building_BIODISC_desc',
    gridRef: 'L23',
    address: '6 Science Road',
    category: 'venue',
  },

  // ADDITIONAL BUILDINGS FROM OSM DATA
  {
    id: '11WW',
    name: "11 Wally's Walk",
    position: gridToPixel('N22'),
    description: 'Academic building on Wallys Walk.',
    tags: ['academic', 'teaching'],
    translationKey: 'building_11WW_name',
    descriptionKey: 'building_11WW_desc',
    gridRef: 'N22',
    address: "11 Wally's Walk",
    category: 'academic',
    location: { lat: -33.774641, lng: 151.115085, osmId: 23716716 },
    levels: 4,
  },
  {
    id: '13RPD',
    name: '13 Research Park Drive',
    position: gridToPixel('M26'),
    description: 'Research facility on Research Park Drive.',
    tags: ['research', 'academic'],
    translationKey: 'building_13RPD_name',
    descriptionKey: 'building_13RPD_desc',
    gridRef: 'M26',
    address: '13 Research Park Drive, Macquarie Park, NSW',
    category: 'research',
    location: { lat: -33.77325, lng: 151.117162, osmId: 23716723 },
  },
  {
    id: '6ER',
    name: '6 Eastern Road',
    position: gridToPixel('Q21'),
    description: 'Academic building on Eastern Road.',
    tags: ['academic', 'teaching'],
    translationKey: 'building_6ER_name',
    descriptionKey: 'building_6ER_desc',
    gridRef: 'Q21',
    address: '6 Eastern Road, Macquarie Park, NSW',
    category: 'academic',
    location: { lat: -33.775576, lng: 151.115895, osmId: 51673951 },
    levels: 4,
  },
  {
    id: '1CC',
    name: '1 Central Courtyard',
    position: gridToPixel('K19'),
    description: 'Central Courtyard building and student hub.',
    tags: ['services', 'student'],
    translationKey: 'building_1CC_name',
    descriptionKey: 'building_1CC_desc',
    gridRef: 'K19',
    address: '1 Central Courtyard',
    category: 'services',
    location: { lat: -33.773263, lng: 151.113652, osmId: 914350786 },
  },
  {
    id: 'MERCURE',
    name: 'Mercure Sydney Macquarie Park',
    position: gridToPixel('L25'),
    description: 'Hotel adjacent to campus.',
    tags: ['accommodation', 'hotel'],
    translationKey: 'building_MERCURE_name',
    descriptionKey: 'building_MERCURE_desc',
    gridRef: 'L25',
    address: 'Research Park Drive',
    category: 'other',
    location: { lat: -33.772395, lng: 151.11687, osmId: 459015422 },
  },
  {
    id: '13ARPD',
    name: '13A Research Park Drive',
    position: gridToPixel('M26'),
    description: 'Research facility on Research Park Drive.',
    tags: ['research', 'academic'],
    translationKey: 'building_13ARPD_name',
    descriptionKey: 'building_13ARPD_desc',
    gridRef: 'M26',
    address: '13 Research Park Drive',
    category: 'research',
    location: { lat: -33.773151, lng: 151.116676, osmId: 1303624873 },
  },
  {
    id: 'COCHLEAR',
    name: 'Cochlear Limited',
    position: gridToPixel('U16'),
    description: 'Cochlear headquarters and research facility.',
    tags: ['research', 'commercial', 'health'],
    translationKey: 'building_COCHLEAR_name',
    descriptionKey: 'building_COCHLEAR_desc',
    gridRef: 'U16',
    address: 'University Avenue',
    category: 'research',
    location: { lat: -33.777452, lng: 151.113603, osmId: 260224790 },
  },
  {
    id: '10SCO',
    name: '10 Sir Christopher Ondaatje Ave',
    position: gridToPixel('P21'),
    description: 'Academic building.',
    tags: ['academic', 'teaching'],
    translationKey: 'building_10SCO_name',
    descriptionKey: 'building_10SCO_desc',
    gridRef: 'P21',
    address: '10 Sir Christopher Ondaatje Ave',
    category: 'academic',
    location: { lat: -33.774901, lng: 151.114706, osmId: 458998307 },
  },
  {
    id: '14ER',
    name: '14 Eastern Road',
    position: gridToPixel('P22'),
    description: 'Academic building on Eastern Road. Faculty of Science.',
    tags: ['academic', 'teaching'],
    translationKey: 'building_14ER_name',
    descriptionKey: 'building_14ER_desc',
    gridRef: 'P22',
    address: '14 Eastern Road',
    category: 'academic',
    location: { lat: -33.77386, lng: 151.115721, osmId: 157975715 },
  },
  {
    id: '6SR',
    name: '6 Science Road',
    position: gridToPixel('M23'),
    description: 'Science building on Science Road.',
    tags: ['academic', 'science', 'labs'],
    translationKey: 'building_6SR_name',
    descriptionKey: 'building_6SR_desc',
    gridRef: 'M23',
    address: '6 Science Road, Macquarie Park, NSW',
    category: 'academic',
    location: { lat: -33.773641, lng: 151.116131, osmId: 157975717 },
  },
  // Additional buildings from MQ Location Guide
  {
    id: '14FW',
    name: '14 First Walk (MUSEC)',
    position: gridToPixel('O10'),
    description: 'Macquarie University Special Education Centre - education programs for children.',
    tags: ['academic', 'education', 'services'],
    translationKey: 'building_14FW_name',
    descriptionKey: 'building_14FW_desc',
    gridRef: 'O10',
    address: '14 First Walk, Macquarie Park, NSW',
    category: 'academic',
    location: { lat: -33.774814, lng: 151.109691, osmId: 148389592 },
  },
  {
    id: '14SCO',
    name: '14 Sir Christopher Ondaatje Ave',
    position: gridToPixel('N20'),
    description: 'Academic building with teaching spaces and exam halls. Faculty of Sciences.',
    tags: ['academic', 'teaching', 'exams'],
    translationKey: 'building_14SCO_name',
    descriptionKey: 'building_14SCO_desc',
    gridRef: 'N20',
    address: '14 Sir Christopher Ondaatje Ave',
    category: 'academic',
    location: { lat: -33.773899, lng: 151.114706, osmId: 157975716 },
    levels: 7,
  },
  {
    id: '4WR',
    name: '4 Western Road',
    position: gridToPixel('P14'),
    description: 'Academic building with teaching and examination rooms.',
    tags: ['academic', 'teaching', 'exams'],
    translationKey: 'building_4WR_name',
    descriptionKey: 'building_4WR_desc',
    gridRef: 'P14',
    address: '4 Western Road',
    category: 'academic',
  },
  // --- NEW BUILDINGS (Imported from OSM) ---
  {
    id: 'EAST3',
    name: 'East 3 Car Park',
    position: [2836, 2466],
    description: 'Multi-storey car park.',
    tags: ['other', 'parking'],
    translationKey: 'building_EAST3_name',
    descriptionKey: 'building_EAST3_desc',

    category: 'other',
    location: { lat: -33.775629, lng: 151.116761, osmId: 14744550 },
  },
  {
    id: 'EAST2',
    name: 'East 2 Car Park',
    position: [2492, 2505],
    description: 'Multi-storey car park.',
    tags: ['other', 'parking'],
    translationKey: 'building_EAST2_name',
    descriptionKey: 'building_EAST2_desc',

    category: 'other',
    location: { lat: -33.774796, lng: 151.116951, osmId: 14744551 },
  },
  {
    id: '75TR',
    name: '75 Talavera Road',
    position: [2119, 2870],
    description: 'Commercial building in the Macquarie Park precinct.',
    tags: ['commercial', 'office'],
    translationKey: 'building_75TR_name',
    descriptionKey: 'building_75TR_desc',
    address: '75 Talavera Road Macquarie Park NSW',
    category: 'other',
    location: { lat: -33.774162, lng: 151.118597, osmId: 23716719 },
  },
  {
    id: '3SR',
    name: '3 Science Road',
    position: [1925, 2423],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_3SR_name',
    descriptionKey: 'building_3SR_desc',
    address: '3 Science Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.773295, lng: 151.116613, osmId: 23716725 },
  },
  {
    id: '6FW',
    name: '6 First Walk',
    position: [3099, 1406],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_6FW_name',
    descriptionKey: 'building_6FW_desc',
    address: '6 First Walk',
    category: 'academic',
    location: { lat: -33.775402, lng: 151.112022, osmId: 62060227 },
    levels: 3,
  },
  {
    id: '17MW',
    name: '17 Macquarie Walk',
    position: [3335, 1667],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_17MW_name',
    descriptionKey: 'building_17MW_desc',
    address: '17 Macquarie Walk',
    category: 'academic',
    location: { lat: -33.776217, lng: 151.113178, osmId: 141281548 },
  },
  {
    id: '1MD',
    name: '1 Management Drive',
    position: [1307, 2298],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_1MD_name',
    descriptionKey: 'building_1MD_desc',
    address: '1 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.771631, lng: 151.116079, osmId: 148387966 },
  },
  {
    id: '3MD',
    name: '3 Management Drive',
    position: [1450, 2214],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_3MD_name',
    descriptionKey: 'building_3MD_desc',
    address: '3 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.771921, lng: 151.1157, osmId: 148387968 },
  },
  {
    id: '5MD',
    name: '5 Management Drive',
    position: [1418, 2431],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_5MD_name',
    descriptionKey: 'building_5MD_desc',
    address: '5 Management Drive',
    category: 'academic',
    location: { lat: -33.772023, lng: 151.116669, osmId: 148387969 },
  },
  {
    id: '1EXR',
    name: '1 Executive Road',
    position: [1108, 2259],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_1EXR_name',
    descriptionKey: 'building_1EXR_desc',
    address: '1 Executive Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.771097, lng: 151.115913, osmId: 148387970 },
  },
  {
    id: '2FW',
    name: '2 First Walk',
    position: [2969, 1709],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_2FW_name',
    descriptionKey: 'building_2FW_desc',
    address: '2 First Walk Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775327, lng: 151.113379, osmId: 148389591 },
    levels: 3,
  },
  {
    id: '4FW',
    name: '4 First Walk',
    position: [3025, 1590],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_4FW_name',
    descriptionKey: 'building_4FW_desc',
    address: '4 First Walk',
    category: 'academic',
    location: { lat: -33.77537, lng: 151.112847, osmId: 148389593 },
    levels: 4,
  },
  {
    id: '2LR',
    name: '2 Link Road',
    position: [3400, 42],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_2LR_name',
    descriptionKey: 'building_2LR_desc',
    address: '2 Link Road',
    category: 'academic',
    location: { lat: -33.775009, lng: 151.105921, osmId: 148390207 },
  },
  {
    id: '6LR',
    name: '6 Link Road',
    position: [3363, 151],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_6LR_name',
    descriptionKey: 'building_6LR_desc',
    address: '6 Link Road',
    category: 'academic',
    location: { lat: -33.775009, lng: 151.106411, osmId: 148390210 },
  },
  {
    id: '4LR',
    name: '4 Link Road',
    position: [3485, 83],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_4LR_name',
    descriptionKey: 'building_4LR_desc',
    address: '4 Link Road',
    category: 'academic',
    location: { lat: -33.775259, lng: 151.106101, osmId: 148390211 },
  },
  {
    id: 'DESTINATIO',
    name: 'Destination Orana',
    position: [1810, 3099],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_DESTINATIO_name',
    descriptionKey: 'building_DESTINATIO_desc',
    address: '112-118 Talavera Road Macquarie Park',
    category: 'residential',
    location: { lat: -33.773576, lng: 151.11963, osmId: 286832282 },
    levels: 28,
  },
  {
    id: '3IR',
    name: '3 Innovation Road',
    position: [2540, 2881],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_3IR_name',
    descriptionKey: 'building_3IR_desc',
    address: '3 Innovation Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775235, lng: 151.118627, osmId: 324612872 },
  },
  {
    id: '1IR',
    name: '1 Innovation Road',
    position: [2634, 2996],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_1IR_name',
    descriptionKey: 'building_1IR_desc',
    address: '1 Innovation Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775569, lng: 151.119137, osmId: 324612876 },
  },
  {
    id: '15RPD',
    name: '15 Research Park Drive',
    position: [1742, 2472],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_15RPD_name',
    descriptionKey: 'building_15RPD_desc',
    address: '15 Research Park Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772875, lng: 151.116836, osmId: 459015425 },
  },
  {
    id: 'RONREILLYP',
    name: 'Ron Reilly Pavilion',
    position: [1, 2016],
    description: 'Sports pavilion.',
    tags: ['sports'],
    translationKey: 'building_RONREILLYP_name',
    descriptionKey: 'building_RONREILLYP_desc',

    category: 'sports',
    location: { lat: -33.766262, lng: 151.114914, osmId: 791253931 },
  },
  {
    id: 'M2OPERATIO',
    name: 'M2 Operations Centre',
    position: [199, 2350],
    description: 'Operations Centre for M2 Motorway.',
    tags: ['other'],
    translationKey: 'building_M2OPERATIO_name',
    descriptionKey: 'building_M2OPERATIO_desc',

    category: 'other',
    location: { lat: -33.768879, lng: 151.11636, osmId: 791276982 },
  },
  {
    id: 'ADELAIDE',
    name: 'Adelaide',
    position: [4813, 1526],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_ADELAIDE_name',
    descriptionKey: 'building_ADELAIDE_desc',

    category: 'residential',
    location: { lat: -33.779828, lng: 151.112484, osmId: 967523408 },
  },
  {
    id: 'DARWIN',
    name: 'Darwin',
    position: [4893, 1618],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_DARWIN_name',
    descriptionKey: 'building_DARWIN_desc',

    category: 'residential',
    location: { lat: -33.780107, lng: 151.112889, osmId: 967523409 },
  },
  {
    id: 'PERTH',
    name: 'Perth',
    position: [4949, 1453],
    description: 'Student accommodation.',
    tags: ['residential'],
    translationKey: 'building_PERTH_name',
    descriptionKey: 'building_PERTH_desc',

    category: 'residential',
    location: { lat: -33.780108, lng: 151.112151, osmId: 967523414 },
  },
  {
    id: 'BLOCKA',
    name: 'Block A (Herring Road)',
    position: [4931, 1937],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKA_name',
    descriptionKey: 'building_BLOCKA_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780472, lng: 151.114311, osmId: 967530686 },
  },
  {
    id: 'BLOCKB',
    name: 'Block B (Herring Road)',
    position: [4873, 1904],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKB_name',
    descriptionKey: 'building_BLOCKB_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780298, lng: 151.114168, osmId: 967533739 },
  },
  {
    id: 'BLOCKC',
    name: 'Block C (Herring Road)',
    position: [4814, 1873],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKC_name',
    descriptionKey: 'building_BLOCKC_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780121, lng: 151.114029, osmId: 967533740 },
  },
  {
    id: 'BLOCKD',
    name: 'Block D (Herring Road)',
    position: [4774, 1832],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKD_name',
    descriptionKey: 'building_BLOCKD_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779986, lng: 151.113847, osmId: 967533741 },
  },
  {
    id: 'BLOCKE',
    name: 'Block E (Herring Road)',
    position: [4737, 1790],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKE_name',
    descriptionKey: 'building_BLOCKE_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779857, lng: 151.113663, osmId: 967533742 },
  },
  {
    id: 'BLOCKF',
    name: 'Block F (Herring Road)',
    position: [4824, 1769],
    description: 'Residential block.',
    tags: ['residential'],
    translationKey: 'building_BLOCKF_name',
    descriptionKey: 'building_BLOCKF_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.780059, lng: 151.113567, osmId: 967533743 },
  },
  {
    id: 'VILLAS',
    name: 'The Villas',
    position: [4660, 1616],
    description: 'Residential villas.',
    tags: ['residential'],
    translationKey: 'building_VILLAS_name',
    descriptionKey: 'building_VILLAS_desc',
    address: '116-118 Herring Road Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779518, lng: 151.11289, osmId: 967533744 },
  },
  {
    id: 'HOLIDAYINN',
    name: 'Holiday Inn Express',
    position: [4660, 3219],
    description: 'Holiday Inn Express Sydney Macquarie Park.',
    tags: ['other', 'hotel'],
    translationKey: 'building_HOLIDAYINN_name',
    descriptionKey: 'building_HOLIDAYINN_desc',

    category: 'other',
    location: { lat: -33.780869, lng: 151.120041, osmId: 1108110442 },
  },
  {
    id: 'MACRESIDEN',
    name: 'Mac Residences',
    position: [4920, 2164],
    description: 'Residential building.',
    tags: ['residential'],
    translationKey: 'building_MACRESIDEN_name',
    descriptionKey: 'building_MACRESIDEN_desc',

    category: 'residential',
    location: { lat: -33.780634, lng: 151.115322, osmId: 1161574505 },
  },
  {
    id: '6MD',
    name: '6 Management Drive',
    position: [1503, 2297],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_6MD_name',
    descriptionKey: 'building_6MD_desc',
    address: '6 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772124, lng: 151.116066, osmId: 1192234862 },
  },
  {
    id: '7MD',
    name: '7 Management Drive',
    position: [1584, 2211],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_7MD_name',
    descriptionKey: 'building_7MD_desc',
    address: '7 Management Drive Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772257, lng: 151.115679, osmId: 1192234863 },
  },
  {
    id: '12MW',
    name: '12 Macquarie Walk',
    position: [2846, 1875],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_12MW_name',
    descriptionKey: 'building_12MW_desc',
    address: '12 Macquarie Walk Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.775158, lng: 151.114124, osmId: 1192234871 },
  },
  {
    id: '18ER',
    name: '18 Eastern Road',
    position: [1824, 2221],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_18ER_name',
    descriptionKey: 'building_18ER_desc',
    address: '18 Eastern Road Macquarie Park NSW',
    category: 'academic',
    location: { lat: -33.772871, lng: 151.115713, osmId: 1192257351 },
  },
  {
    id: '2WW',
    name: "2 Wally's Walk",
    position: [2216, 2560],
    description: 'Academic building.',
    tags: ['academic'],
    translationKey: 'building_2WW_name',
    descriptionKey: 'building_2WW_desc',
    address: "2 Wally's Walk Macquarie Park NSW",
    category: 'academic',
    location: { lat: -33.774145, lng: 151.117209, osmId: 1303624872 },
  },
  {
    id: 'REDDYEXPRE',
    name: 'Reddy Express',
    position: [3483, 1],
    description: 'Convenience store.',
    tags: ['food', 'retail'],
    translationKey: 'building_REDDYEXPRE_name',
    descriptionKey: 'building_REDDYEXPRE_desc',

    category: 'food',
    location: { lat: -33.775123, lng: 151.105399, osmId: 1444070791 },
  }, // --- ADDITIONAL BUILDINGS (Full Scan) ---
  {
    id: '23WW',
    name: '23WW',
    position: [2982, 1358],
    description: '23WW building.',
    tags: ['academic'],
    translationKey: 'building_23WW_name',
    descriptionKey: 'building_23WW_desc',
    category: 'academic',
    location: { lat: -33.775064, lng: 151.111811, osmId: 6784791 },
    levels: 1,
  },
  {
    id: 'SIEMENS',
    name: 'Siemens',
    position: [2258, 3173],
    description: 'Siemens building.',
    tags: ['commercial', 'office'],
    translationKey: 'building_SIEMENS_name',
    descriptionKey: 'building_SIEMENS_desc',
    category: 'other',
    location: { lat: -33.774767, lng: 151.11994, osmId: 6784971 },
    levels: 1,
  },
  {
    id: '82WATERLOO',
    name: '82 Waterloo Road',
    position: [4246, 3222],
    description: '82 Waterloo Road apartments.',
    tags: ['residential'],
    translationKey: 'building_82WATERLOO_name',
    descriptionKey: 'building_82WATERLOO_desc',
    category: 'residential',
    location: { lat: -33.779827, lng: 151.120073, osmId: 23716745 },
    levels: 1,
  },
  {
    id: '93WATERLOO',
    name: '93 Waterloo Road',
    position: [4001, 3663],
    description: '93 Waterloo Road commercial office building.',
    tags: ['commercial', 'office'],
    translationKey: 'building_93WATERLOO_name',
    descriptionKey: 'building_93WATERLOO_desc',
    category: 'other',
    location: { lat: -33.77958, lng: 151.122053, osmId: 23716748 },
    levels: 1,
  },
  {
    id: 'THERANCH',
    name: 'The Ranch',
    position: [5495, 1550],
    description: 'The Ranch restaurant.',
    tags: ['food'],
    translationKey: 'building_THERANCH_name',
    descriptionKey: 'building_THERANCH_desc',
    category: 'food',
    location: { lat: -33.781568, lng: 151.112559, osmId: 75739210 },
    levels: 1,
  },
  {
    id: '10HA',
    name: '10 Hadenfeld Avenue (Chaplaincy)',
    position: [3645, 518],
    description: 'Multi-faith chaplaincy and spiritual services building.',
    tags: ['services', 'spiritual', 'chaplaincy'],
    translationKey: 'building_10HA_name',
    descriptionKey: 'building_10HA_desc',
    category: 'services',
    location: { lat: -33.776031, lng: 151.108038, osmId: 100955278 },
    levels: 1,
  },
  {
    id: '16MW',
    name: '16 Macquarie Walk (Waranara Library)',
    position: [3133, 1670],
    description: 'Main campus library with study spaces, Library Cafe, and extensive collections.',
    tags: ['academic', 'study', 'library', 'resources'],
    translationKey: 'building_16MW_name',
    descriptionKey: 'building_16MW_desc',
    category: 'academic',
    location: { lat: -33.77571, lng: 151.1132, osmId: 141281549 },
    levels: 8,
  },
  {
    id: 'LAKESIDEHO',
    name: 'Lakeside Hotel & Conference Centre',
    position: [1191, 2285],
    description: 'Lakeside Hotel & Conference Centre.',
    tags: ['accommodation', 'hotel', 'venue'],
    translationKey: 'building_LAKESIDEHO_name',
    descriptionKey: 'building_LAKESIDEHO_desc',
    category: 'other',
    location: { lat: -33.771329, lng: 151.116029, osmId: 148387967 },
    levels: 1,
  },
  {
    id: '8LR',
    name: '8LR (Banksia Cottage)',
    position: [3237, 732],
    description: 'Banksia Cottage campus childcare facility.',
    tags: ['services', 'childcare'],
    translationKey: 'building_8LR_name',
    descriptionKey: 'building_8LR_desc',
    category: 'services',
    location: { lat: -33.77518, lng: 151.109008, osmId: 148389594 },
    levels: 1,
  },
  {
    id: 'MACQUARIEC',
    name: 'Macquarie Centre',
    position: [3094, 3630],
    description: 'Macquarie Centre shopping mall with food court, retail stores, and cinema.',
    tags: ['food', 'retail', 'shopping'],
    translationKey: 'building_MACQUARIEC_name',
    descriptionKey: 'building_MACQUARIEC_desc',
    category: 'other',
    location: { lat: -33.777263, lng: 151.121943, osmId: 201725087 },
    levels: 1,
  },
  {
    id: '11GR',
    name: '11GR (Lighthouse Theatre)',
    position: [1847, 1371],
    description: 'Performance venue and theatre.',
    tags: ['venue', 'performance', 'arts'],
    translationKey: 'building_11GR_name',
    descriptionKey: 'building_11GR_desc',
    category: 'venue',
    location: { lat: -33.772213, lng: 151.111922, osmId: 205588350 },
    levels: 1,
  },
  {
    id: '10GR',
    name: '10GR (Macquarie University Sport and Aquatic Centre)',
    position: [2132, 1111],
    description: '10GR building.',
    tags: ['sports'],
    translationKey: 'building_10GR_name',
    descriptionKey: 'building_10GR_desc',
    category: 'sports',
    location: { lat: -33.772712, lng: 151.11075, osmId: 205588367 },
    levels: 1,
  },
  {
    id: 'DUNMORELAN',
    name: 'Dunmore Lang College - Postgraduate Apartments',
    position: [4447, 2350],
    description: 'Dunmore Lang College apartments.',
    tags: ['residential'],
    translationKey: 'building_DUNMORELAN_name',
    descriptionKey: 'building_DUNMORELAN_desc',
    category: 'residential',
    location: { lat: -33.779599, lng: 151.116174, osmId: 205588642 },
    levels: 1,
  },
  {
    id: 'FUJITSUAUS',
    name: 'Fujitsu Australia Limited',
    position: [1707, 2981],
    description: 'Fujitsu Australia Limited office.',
    tags: ['commercial', 'office'],
    translationKey: 'building_FUJITSUAUS_name',
    descriptionKey: 'building_FUJITSUAUS_desc',
    category: 'other',
    location: { lat: -33.773217, lng: 151.11911, osmId: 412583875 },
    levels: 1,
  },
  {
    id: '8492TALAVE',
    name: '84-92 Talavera Road',
    position: [2360, 3624],
    description: '84-92 Talavera Road commercial office building.',
    tags: ['commercial', 'office'],
    translationKey: 'building_8492TALAVE_name',
    descriptionKey: 'building_8492TALAVE_desc',
    category: 'other',
    location: { lat: -33.775407, lng: 151.12195, osmId: 420147599 },
    levels: 1,
  },
  {
    id: '94110TALAV',
    name: '94-110 Talavera Road',
    position: [2293, 3559],
    description: '94-110 Talavera Road commercial office building.',
    tags: ['commercial', 'office'],
    translationKey: 'building_94110TALAV_name',
    descriptionKey: 'building_94110TALAV_desc',
    category: 'other',
    location: { lat: -33.775182, lng: 151.121663, osmId: 420147600 },
    levels: 1,
  },
  {
    id: '29WW',
    name: '29WW',
    position: [2838, 1027],
    description: '29WW building.',
    tags: ['academic'],
    translationKey: 'building_29WW_name',
    descriptionKey: 'building_29WW_desc',
    category: 'academic',
    location: { lat: -33.774423, lng: 151.110342, osmId: 455246541 },
    levels: 1,
  },
  {
    id: '27WW',
    name: '27WW (Lotus Theatre)',
    position: [2887, 1092],
    description: 'Major teaching and entertainment venue.',
    tags: ['venue', 'teaching', 'events'],
    translationKey: 'building_27WW_name',
    descriptionKey: 'building_27WW_desc',
    category: 'venue',
    location: { lat: -33.774601, lng: 151.110631, osmId: 455246542 },
    levels: 1,
  },
  {
    id: '25WW',
    name: '25WW',
    position: [2957, 1184],
    description: '25WW building.',
    tags: ['academic'],
    translationKey: 'building_25WW_name',
    descriptionKey: 'building_25WW_desc',
    category: 'academic',
    location: { lat: -33.774855, lng: 151.111037, osmId: 458998300 },
    levels: 1,
  },
  {
    id: '21WW',
    name: '21WW (Macquarie Theatre)',
    position: [2773, 1474],
    description: 'Large lecture theatre and entertainment venue.',
    tags: ['venue', 'teaching', 'events'],
    translationKey: 'building_21WW_name',
    descriptionKey: 'building_21WW_desc',
    category: 'venue',
    location: { lat: -33.774636, lng: 151.112338, osmId: 458998304 },
    levels: 1,
  },
  {
    id: '14SW',
    name: '14SW',
    position: [2849, 1551],
    description: '14SW building.',
    tags: ['academic'],
    translationKey: 'building_14SW_name',
    descriptionKey: 'building_14SW_desc',
    category: 'academic',
    location: { lat: -33.774892, lng: 151.112682, osmId: 458998305 },
    levels: 1,
  },
  {
    id: 'MERCURESYD',
    name: 'Mercure Sydney Macquarie',
    position: [1572, 2491],
    description: 'Mercure Sydney Macquarie.',
    tags: ['accommodation', 'hotel'],
    translationKey: 'building_MERCURESYD_name',
    descriptionKey: 'building_MERCURESYD_desc',
    category: 'other',
    location: { lat: -33.772462, lng: 151.116932, osmId: 459015422 },
    levels: 1,
  },
  {
    id: '2TP',
    name: '2 Technology Place',
    position: [1723, 2663],
    description: '2 Technology Place - health and medical facilities.',
    tags: ['health', 'medical'],
    translationKey: 'building_2TP_name',
    descriptionKey: 'building_2TP_desc',
    category: 'health',
    location: { lat: -33.772989, lng: 151.117692, osmId: 459015453 },
    levels: 1,
  },
  {
    id: 'MACQUARIEU',
    name: 'Macquarie University Hospital',
    position: [1993, 2744],
    description: 'Macquarie University Hospital.',
    tags: ['health', 'medical', 'hospital'],
    translationKey: 'building_MACQUARIEU_name',
    descriptionKey: 'building_MACQUARIEU_desc',
    category: 'health',
    location: { lat: -33.773738, lng: 151.118041, osmId: 459015460 },
    levels: 1,
  },
  {
    id: 'STUDENTACC',
    name: 'Student Accommodation',
    position: [2161, 1552],
    description: 'Student Accommodation.',
    tags: ['residential', 'accommodation'],
    translationKey: 'building_STUDENTACC_name',
    descriptionKey: 'building_STUDENTACC_desc',
    category: 'residential',
    location: { lat: -33.773156, lng: 151.112713, osmId: 914350787 },
    levels: 1,
  },
  {
    id: 'HOBART',
    name: 'Hobart',
    position: [5009, 1733],
    description: 'Hobart apartments.',
    tags: ['residential'],
    translationKey: 'building_HOBART_name',
    descriptionKey: 'building_HOBART_desc',
    category: 'residential',
    location: { lat: -33.780496, lng: 151.113395, osmId: 967523410 },
    levels: 1,
  },
  {
    id: 'MELBOURNE',
    name: 'Melbourne',
    position: [5088, 1834],
    description: 'Melbourne apartments.',
    tags: ['residential'],
    translationKey: 'building_MELBOURNE_name',
    descriptionKey: 'building_MELBOURNE_desc',
    category: 'residential',
    location: { lat: -33.780779, lng: 151.113843, osmId: 967523411 },
    levels: 1,
  },
  {
    id: 'SYDNEY',
    name: 'Sydney',
    position: [5177, 1703],
    description: 'Sydney apartments.',
    tags: ['residential'],
    translationKey: 'building_SYDNEY_name',
    descriptionKey: 'building_SYDNEY_desc',
    category: 'residential',
    location: { lat: -33.780895, lng: 151.113255, osmId: 967523412 },
    levels: 1,
  },
  {
    id: 'BRISBANE',
    name: 'Brisbane',
    position: [5070, 1580],
    description: 'Brisbane apartments.',
    tags: ['residential'],
    translationKey: 'building_BRISBANE_name',
    descriptionKey: 'building_BRISBANE_desc',
    category: 'residential',
    location: { lat: -33.780522, lng: 151.112713, osmId: 967523413 },
    levels: 1,
  },
  {
    id: '1SAUNDERSC',
    name: '1 Saunders Close',
    position: [4417, 2133],
    description: '1 Saunders Close apartments.',
    tags: ['residential'],
    translationKey: 'building_1SAUNDERSC_name',
    descriptionKey: 'building_1SAUNDERSC_desc',
    category: 'residential',
    location: { lat: -33.779339, lng: 151.115209, osmId: 967530681 },
    levels: 1,
  },
  {
    id: '2SAUNDERSC',
    name: '2 Saunders Close',
    position: [4249, 2263],
    description: '2 Saunders Close apartments.',
    tags: ['residential'],
    translationKey: 'building_2SAUNDERSC_name',
    descriptionKey: 'building_2SAUNDERSC_desc',
    category: 'residential',
    location: { lat: -33.779025, lng: 151.115796, osmId: 967530682 },
    levels: 1,
  },
  {
    id: '4SAUNDERSC',
    name: '4 Saunders Close',
    position: [4191, 2165],
    description: '4 Saunders Close apartments.',
    tags: ['residential'],
    translationKey: 'building_4SAUNDERSC_name',
    descriptionKey: 'building_4SAUNDERSC_desc',
    category: 'residential',
    location: { lat: -33.778795, lng: 151.11536, osmId: 967530683 },
    levels: 1,
  },
  {
    id: '6SAUNDERSC',
    name: '6 Saunders Close',
    position: [4082, 2061],
    description: '6 Saunders Close apartments.',
    tags: ['residential'],
    translationKey: 'building_6SAUNDERSC_name',
    descriptionKey: 'building_6SAUNDERSC_desc',
    category: 'residential',
    location: { lat: -33.778433, lng: 151.1149, osmId: 967530684 },
    levels: 1,
  },
  {
    id: '8SAUNDERSC',
    name: '8 Saunders Close',
    position: [3995, 1959],
    description: '8 Saunders Close apartments.',
    tags: ['residential'],
    translationKey: 'building_8SAUNDERSC_name',
    descriptionKey: 'building_8SAUNDERSC_desc',
    category: 'residential',
    location: { lat: -33.778128, lng: 151.114451, osmId: 967530685 },
    levels: 1,
  },
  {
    id: '120HERRING',
    name: '120 Herring Road',
    position: [4702, 1971],
    description: '120 Herring Road apartments.',
    tags: ['residential'],
    translationKey: 'building_120HERRING_name',
    descriptionKey: 'building_120HERRING_desc',
    category: 'residential',
    location: { lat: -33.779922, lng: 151.11447, osmId: 968737345 },
    levels: 1,
  },
  {
    id: '155HERRING',
    name: '155 Herring Road',
    position: [4694, 2235],
    description: '155 Herring Road apartments.',
    tags: ['residential'],
    translationKey: 'building_155HERRING_name',
    descriptionKey: 'building_155HERRING_desc',
    category: 'residential',
    location: { lat: -33.780123, lng: 151.115651, osmId: 982138146 },
    levels: 1,
  },
  {
    id: '1PEACHTREE',
    name: '1 Peach Tree Road',
    position: [4894, 2405],
    description: '1 Peach Tree Road apartments.',
    tags: ['residential'],
    translationKey: 'building_1PEACHTREE_name',
    descriptionKey: 'building_1PEACHTREE_desc',
    category: 'residential',
    location: { lat: -33.780772, lng: 151.116402, osmId: 982138154 },
    levels: 1,
  },
  {
    id: '3PEACHTREE',
    name: '3 Peach Tree Road',
    position: [4949, 2469],
    description: '3 Peach Tree Road apartments.',
    tags: ['residential'],
    translationKey: 'building_3PEACHTREE_name',
    descriptionKey: 'building_3PEACHTREE_desc',
    category: 'residential',
    location: { lat: -33.780964, lng: 151.116685, osmId: 982138158 },
    levels: 1,
  },
  {
    id: '5PEACHTREE',
    name: '5 Peach Tree Road',
    position: [5013, 2537],
    description: '5 Peach Tree Road apartments.',
    tags: ['residential'],
    translationKey: 'building_5PEACHTREE_name',
    descriptionKey: 'building_5PEACHTREE_desc',
    category: 'residential',
    location: { lat: -33.781183, lng: 151.116982, osmId: 982138159 },
    levels: 1,
  },
  {
    id: '7PEACHTREE',
    name: '7 Peach Tree Road',
    position: [5079, 2602],
    description: '7 Peach Tree Road apartments.',
    tags: ['residential'],
    translationKey: 'building_7PEACHTREE_name',
    descriptionKey: 'building_7PEACHTREE_desc',
    category: 'residential',
    location: { lat: -33.781406, lng: 151.117272, osmId: 982138160 },
    levels: 1,
  },
  {
    id: '210COTTONW',
    name: '2-10 Cottonwood Crescent',
    position: [4435, 2867],
    description: '2-10 Cottonwood Crescent apartments.',
    tags: ['residential'],
    translationKey: 'building_210COTTONW_name',
    descriptionKey: 'building_210COTTONW_desc',
    category: 'residential',
    location: { lat: -33.780003, lng: 151.11848, osmId: 982143456 },
    levels: 1,
  },
  {
    id: '13LACHLANA',
    name: '1-3 Lachlan Avenue',
    position: [4778, 2302],
    description: '1-3 Lachlan Avenue residential apartments.',
    tags: ['residential'],
    translationKey: 'building_13LACHLANA_name',
    descriptionKey: 'building_13LACHLANA_desc',
    category: 'residential',
    location: { lat: -33.780393, lng: 151.115944, osmId: 982143458 },
    levels: 1,
  },
  {
    id: '9PEACHTREE',
    name: '9 Peach Tree Road',
    position: [5136, 2692],
    description: '9 Peach Tree Road apartments.',
    tags: ['residential'],
    translationKey: 'building_9PEACHTREE_name',
    descriptionKey: 'building_9PEACHTREE_desc',
    category: 'residential',
    location: { lat: -33.781624, lng: 151.117671, osmId: 982143459 },
    levels: 1,
  },
  {
    id: '157HERRING',
    name: '157 Herring Road',
    position: [4572, 2296],
    description: '157 Herring Road apartments.',
    tags: ['residential'],
    translationKey: 'building_157HERRING_name',
    descriptionKey: 'building_157HERRING_desc',
    category: 'residential',
    location: { lat: -33.779869, lng: 151.11593, osmId: 984576836 },
    levels: 1,
  },
  {
    id: 'DANMURPHYS',
    name: "Dan Murphy's",
    position: [5366, 1385],
    description: "Dan Murphy's liquor store.",
    tags: ['food'],
    translationKey: 'building_DANMURPHYS_name',
    descriptionKey: 'building_DANMURPHYS_desc',
    category: 'food',
    location: { lat: -33.781102, lng: 151.111828, osmId: 991365824 },
    levels: 1,
  },
  {
    id: '205A',
    name: '205A Culloden Road',
    position: [667, 1324],
    description: '205A Culloden Road residential building.',
    tags: ['residential'],
    translationKey: 'building_205A_name',
    descriptionKey: 'building_205A_desc',
    category: 'residential',
    location: { lat: -33.769196, lng: 151.111763, osmId: 1065030401 },
    levels: 1,
  },
  {
    id: '205B',
    name: '205B Culloden Road',
    position: [814, 1294],
    description: '205B Culloden Road residential building.',
    tags: ['residential'],
    translationKey: 'building_205B_name',
    descriptionKey: 'building_205B_desc',
    category: 'residential',
    location: { lat: -33.769541, lng: 151.111623, osmId: 1065030402 },
    levels: 1,
  },
  {
    id: '8HA',
    name: '8HA (Incubator)',
    position: [3616, 747],
    description: 'Macquarie University Incubator for startups and innovation.',
    tags: ['services', 'business', 'innovation'],
    translationKey: 'building_8HA_name',
    descriptionKey: 'building_8HA_desc',
    category: 'services',
    location: { lat: -33.776149, lng: 151.109059, osmId: 1107882877 },
    levels: 1,
  },
  {
    id: '5GR',
    name: '5GR (Macquarie Observatory)',
    position: [1173, 1186],
    description: 'Astronomy observatory for research and education.',
    tags: ['research', 'science', 'astronomy'],
    translationKey: 'building_5GR_name',
    descriptionKey: 'building_5GR_desc',
    category: 'research',
    location: { lat: -33.770356, lng: 151.111124, osmId: 1192242193 },
    levels: 1,
  },
  {
    id: '1WW',
    name: '1WW (Ainsworth Building)',
    position: [2166, 2769],
    description: '1WW (Ainsworth Building).',
    tags: ['academic'],
    translationKey: 'building_1WW_name',
    descriptionKey: 'building_1WW_desc',
    category: 'academic',
    location: { lat: -33.774195, lng: 151.118145, osmId: 1303624871 },
    levels: 1,
  },

  // --- FINAL SCAN ADDITIONS ---
  {
    id: '17WWMICHAE',
    name: '17WW (Michael Kirby Building)',
    position: [2756, 1684],
    description: '17WW (Michael Kirby Building).',
    tags: ['academic'],
    translationKey: 'building_17WWMICHAE_name',
    descriptionKey: 'building_17WWMICHAE_desc',
    category: 'academic',
    location: { lat: -33.774771, lng: 151.113278, osmId: 7867502 },
    levels: 1,
  },

  {
    id: '18WWSERVIC',
    name: '18WW (Service Connect)',
    position: [2517, 1522],
    description: 'Service Connect - main student services hub with IT, HR, and Financial Services.',
    tags: ['services', 'administration', 'student'],
    translationKey: 'building_18WWSERVIC_name',
    descriptionKey: 'building_18WWSERVIC_desc',
    category: 'services',
    location: { lat: -33.774029, lng: 151.112563, osmId: 205588336 },
    levels: 1,
  },

  {
    id: '16WWLINCOL',
    name: '16WW (Lincoln Building)',
    position: [2524, 1747],
    description: '16WW (Lincoln Building).',
    tags: ['academic'],
    translationKey: 'building_16WWLINCOL_name',
    descriptionKey: 'building_16WWLINCOL_desc',
    category: 'academic',
    location: { lat: -33.774239, lng: 151.11357, osmId: 205588359 },
    levels: 1,
  },

  {
    id: '19ERTHECHA',
    name: '19ER (The Chancellery)',
    position: [1693, 2045],
    description: 'The Chancellery - University administration headquarters.',
    tags: ['services', 'administration'],
    translationKey: 'building_19ERTHECHA_name',
    descriptionKey: 'building_19ERTHECHA_desc',
    category: 'services',
    location: { lat: -33.772391, lng: 151.114933, osmId: 205588364 },
    levels: 1,
  },

  {
    id: '16UAAUSTRA',
    name: '16UA (Australian Hearing Hub)',
    position: [3589, 1342],
    description: 'Australian Hearing Hub - hearing research and clinical services.',
    tags: ['health', 'research', 'clinic'],
    translationKey: 'building_16UAAUSTRA_name',
    descriptionKey: 'building_16UAAUSTRA_desc',
    category: 'health',
    location: { lat: -33.776584, lng: 151.111717, osmId: 271661421 },
    levels: 1,
  },
  // --- NEW BUILDINGS FROM MQ_Full.geojson (2026-01-09) ---
  {
    id: 'DLCNEW',
    name: 'Dunmore Lang College - New Wing',
    position: [4290, 2419],
    description: 'Dunmore Lang College New Wing residential building.',
    tags: ['residential'],
    translationKey: 'building_DLCNEW_name',
    descriptionKey: 'building_DLCNEW_desc',
    address: '130 Herring Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.777772, lng: 151.116569, osmId: 488128859 },
    levels: 3,
  },
  {
    id: 'DLCOFFICE',
    name: 'Dunmore Lang College - Office',
    position: [4276, 2487],
    description: 'Dunmore Lang College administration office.',
    tags: ['residential', 'services'],
    translationKey: 'building_DLCOFFICE_name',
    descriptionKey: 'building_DLCOFFICE_desc',
    address: '130 Herring Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.778147, lng: 151.116507, osmId: 488128860 },
    levels: 2,
  },
  {
    id: 'VILLAS2',
    name: 'Villas (Building 2)',
    position: [4675, 1627],
    description: 'Residential villas - second building.',
    tags: ['residential'],
    translationKey: 'building_VILLAS2_name',
    descriptionKey: 'building_VILLAS2_desc',
    address: '116-118 Herring Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779176, lng: 151.12716, osmId: 967533745 },
  },
  {
    id: 'BLOCKCWAT',
    name: 'Block C (Waterloo Road)',
    position: [4751, 3185],
    description: 'Residential block on Waterloo Road.',
    tags: ['residential'],
    translationKey: 'building_BLOCKCWAT_name',
    descriptionKey: 'building_BLOCKCWAT_desc',
    address: '101 Waterloo Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779187, lng: 151.121267, osmId: 982138149 },
  },
  {
    id: 'BLOCKDWAT',
    name: 'Block D (Waterloo Road)',
    position: [4751, 3170],
    description: 'Residential block on Waterloo Road.',
    tags: ['residential'],
    translationKey: 'building_BLOCKDWAT_name',
    descriptionKey: 'building_BLOCKDWAT_desc',
    address: '101 Waterloo Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.779153, lng: 151.121194, osmId: 982138150 },
  },
  {
    id: 'BLOCKAWAT',
    name: 'Block A (Waterloo Road)',
    position: [4759, 3125],
    description: 'Residential block on Waterloo Road.',
    tags: ['residential'],
    translationKey: 'building_BLOCKAWAT_name',
    descriptionKey: 'building_BLOCKAWAT_desc',
    address: '101 Waterloo Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.778673, lng: 151.121302, osmId: 982138151 },
  },
  {
    id: 'BLOCKBWAT',
    name: 'Block B (Waterloo Road)',
    position: [4830, 3125],
    description: 'Residential block on Waterloo Road.',
    tags: ['residential'],
    translationKey: 'building_BLOCKBWAT_name',
    descriptionKey: 'building_BLOCKBWAT_desc',
    address: '101 Waterloo Road, Macquarie Park NSW',
    category: 'residential',
    location: { lat: -33.778659, lng: 151.121994, osmId: 982138152 },
  },
];

export const getBuildingById = (id: string): Building | undefined => {
  return buildings.find((building) => building.id === id);
};

export const searchBuildings = (query: string): Building[] => {
  const lowerQuery = query.toLowerCase();
  return buildings.filter(
    (building) =>
      building.name.toLowerCase().includes(lowerQuery) ||
      building.id.toLowerCase().includes(lowerQuery) ||
      building.tags?.some((tag) => tag.toLowerCase().includes(lowerQuery)) ||
      building.description?.toLowerCase().includes(lowerQuery) ||
      building.gridRef?.toLowerCase().includes(lowerQuery) ||
      building.address?.toLowerCase().includes(lowerQuery),
  );
};

export const getBuildingsByCategory = (category: BuildingCategory): Building[] => {
  return buildings.filter((building) => building.category === category);
};

export const getBuildingsByTag = (tag: string): Building[] => {
  return buildings.filter((building) => building.tags?.includes(tag));
};

// Building category labels for display
export const BUILDING_CATEGORY_LABELS: Record<BuildingCategory, string> = {
  academic: 'Academic',
  services: 'Student Services',
  health: 'Health & Medical',
  food: 'Food & Retail',
  sports: 'Sports & Recreation',
  venue: 'Venues & Theatres',
  research: 'Research',
  residential: 'Accommodation',
  other: 'Other',
};
