// lib/map/locations.ts
// MQ Campus Location Guide - extracted from official PDF (Property, Aug 2025)

export type LocationCategory =
  | 'KEY_LOCATIONS'
  | 'ADMINISTRATION'
  | 'FACULTY_OF_ARTS'
  | 'MACQUARIE_BUSINESS_SCHOOL'
  | 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES'
  | 'FACULTY_OF_SCIENCE_ENGINEERING'
  | 'VENUES'
  | 'ART_GALLERY_MUSEUMS'
  | 'FOOD_BEVERAGE_RETAIL'
  | 'MQ_HEALTH'
  | 'OTHER_SERVICES'
  | 'OTHER_LOCATIONS';

export interface CampusLocation {
  id: string;
  category: LocationCategory;
  name: string;
  address: string;
  ref: string;
  campus: string;
}

export const campusLocations: CampusLocation[] = [
  // KEY LOCATIONS
  {
    id: 'emergency-first-aid',
    category: 'KEY_LOCATIONS',
    name: 'Emergency & First Aid',
    address: '4 Link Road',
    ref: 'P2',
    campus: 'Wallumattagal',
  },
  {
    id: 'security-info',
    category: 'KEY_LOCATIONS',
    name: 'Security & Information',
    address: '4 Link Road',
    ref: 'P2',
    campus: 'Wallumattagal',
  },
  {
    id: 'first-aid-room',
    category: 'KEY_LOCATIONS',
    name: 'First Aid Room',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'service-connect',
    category: 'KEY_LOCATIONS',
    name: 'Service Connect',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'student-wellbeing',
    category: 'KEY_LOCATIONS',
    name: 'Student Wellbeing',
    address: '12 Second Way',
    ref: 'P16',
    campus: 'Wallumattagal',
  },

  // ADMINISTRATION
  {
    id: 'access-widening',
    category: 'ADMINISTRATION',
    name: 'Access and Widening Participation',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'admissions-scholarships',
    category: 'ADMINISTRATION',
    name: 'Admissions and Scholarships',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'archives-records',
    category: 'ADMINISTRATION',
    name: 'Archives & Records Management',
    address: '19 Eastern Road',
    ref: 'H20',
    campus: 'Wallumattagal',
  },
  {
    id: 'business-intelligence',
    category: 'ADMINISTRATION',
    name: 'Business Intelligence Reporting',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'campus-life',
    category: 'ADMINISTRATION',
    name: 'Campus Life',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'chancellery',
    category: 'ADMINISTRATION',
    name: 'Chancellery',
    address: '19 Eastern Road',
    ref: 'H20',
    campus: 'Wallumattagal',
  },
  {
    id: 'corporate-engagement',
    category: 'ADMINISTRATION',
    name: 'Corporate Engagement & Advancement',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'financial-services',
    category: 'ADMINISTRATION',
    name: 'Financial Services',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'group-marketing',
    category: 'ADMINISTRATION',
    name: 'Group Marketing',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'human-resources',
    category: 'ADMINISTRATION',
    name: 'Human Resources',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'it-services',
    category: 'ADMINISTRATION',
    name: 'Information Technology',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'participation-community',
    category: 'ADMINISTRATION',
    name: 'Participation & Community Engagement',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'property',
    category: 'ADMINISTRATION',
    name: 'Property',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'tech-bar',
    category: 'ADMINISTRATION',
    name: 'Tech Bar',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },

  // FACULTY OF ARTS
  {
    id: 'arts-admin',
    category: 'FACULTY_OF_ARTS',
    name: 'Faculty Administration (Arts)',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'critical-indigenous-studies',
    category: 'FACULTY_OF_ARTS',
    name: 'Department of Critical Indigenous Studies',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'history-archaeology',
    category: 'FACULTY_OF_ARTS',
    name: 'Department of History and Archaeology',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'media-communication',
    category: 'FACULTY_OF_ARTS',
    name: 'Department of Media, Communication, Creative Arts, Language & Literature',
    address: "17 Wally's Walk",
    ref: 'O19',
    campus: 'Wallumattagal',
  },
  {
    id: 'security-criminology',
    category: 'FACULTY_OF_ARTS',
    name: 'Department of Security Studies & Criminology',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'law-school',
    category: 'FACULTY_OF_ARTS',
    name: 'Macquarie Law School',
    address: "17 Wally's Walk",
    ref: 'O19',
    campus: 'Wallumattagal',
  },
  {
    id: 'education-school',
    category: 'FACULTY_OF_ARTS',
    name: 'Macquarie School of Education',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'social-sciences',
    category: 'FACULTY_OF_ARTS',
    name: 'Macquarie School of Social Sciences',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'special-education',
    category: 'FACULTY_OF_ARTS',
    name: 'Macquarie University Special Education Centre',
    address: '14 First Walk',
    ref: 'O10',
    campus: 'Wallumattagal',
  },

  // MACQUARIE BUSINESS SCHOOL
  {
    id: 'mbs-admin',
    category: 'MACQUARIE_BUSINESS_SCHOOL',
    name: 'Faculty Administration (Business)',
    address: '4 Eastern Road',
    ref: 'Q22',
    campus: 'Wallumattagal',
  },
  {
    id: 'accounting-governance',
    category: 'MACQUARIE_BUSINESS_SCHOOL',
    name: 'Department of Accounting & Corporate Governance',
    address: '4 Eastern Road',
    ref: 'Q22',
    campus: 'Wallumattagal',
  },
  {
    id: 'actuarial-analytics',
    category: 'MACQUARIE_BUSINESS_SCHOOL',
    name: 'Department of Actuarial Studies & Business Analytics',
    address: '4 Eastern Road',
    ref: 'Q22',
    campus: 'Wallumattagal',
  },
  {
    id: 'applied-finance',
    category: 'MACQUARIE_BUSINESS_SCHOOL',
    name: 'Department of Applied Finance',
    address: '4 Eastern Road',
    ref: 'Q22',
    campus: 'Wallumattagal',
  },
  {
    id: 'management',
    category: 'MACQUARIE_BUSINESS_SCHOOL',
    name: 'Department of Management',
    address: '4 Eastern Road',
    ref: 'Q22',
    campus: 'Wallumattagal',
  },
  {
    id: 'marketing',
    category: 'MACQUARIE_BUSINESS_SCHOOL',
    name: 'Department of Marketing',
    address: '4 Eastern Road',
    ref: 'Q22',
    campus: 'Wallumattagal',
  },

  // FACULTY OF MEDICINE, HEALTH & HUMAN SCIENCES
  {
    id: 'mhhs-admin',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Faculty Administration (Medicine, Health & Human Sciences)',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'health-innovation',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Australian Institute of Health Innovation',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'emotional-health',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Centre for Emotional Health',
    address: '16 University Avenue',
    ref: 'T14',
    campus: 'Wallumattagal',
  },
  {
    id: 'chiropractic',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Department of Chiropractic',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'health-sciences',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Department of Health Sciences',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'linguistics',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Department of Linguistics',
    address: '16 University Avenue',
    ref: 'T14',
    campus: 'Wallumattagal',
  },
  {
    id: 'medical-school',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Macquarie Medical School',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'psychology-clinic',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Macquarie University Psychology Clinic',
    address: '16 University Avenue',
    ref: 'T14',
    campus: 'Wallumattagal',
  },
  {
    id: 'reading-clinic',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'Macquarie University Reading Clinic',
    address: '16 University Avenue',
    ref: 'T14',
    campus: 'Wallumattagal',
  },
  {
    id: 'psychological-sciences',
    category: 'FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES',
    name: 'School of Psychological Sciences',
    address: '16 University Avenue',
    ref: 'T14',
    campus: 'Wallumattagal',
  },

  // FACULTY OF SCIENCE & ENGINEERING
  {
    id: 'astronomical-optics',
    category: 'FACULTY_OF_SCIENCE_ENGINEERING',
    name: 'Australian Astronomical Optics',
    address: "9 Wally's Walk",
    ref: 'O22',
    campus: 'Wallumattagal',
  },
  {
    id: 'proteome-facility',
    category: 'FACULTY_OF_SCIENCE_ENGINEERING',
    name: 'Australian Proteome Analysis Facility',
    address: "4 Wally's Walk",
    ref: 'M24',
    campus: 'Wallumattagal',
  },
  {
    id: 'engineering-school',
    category: 'FACULTY_OF_SCIENCE_ENGINEERING',
    name: 'School of Engineering',
    address: "9 Wally's Walk",
    ref: 'O22',
    campus: 'Wallumattagal',
  },
  {
    id: 'computing-school',
    category: 'FACULTY_OF_SCIENCE_ENGINEERING',
    name: 'School of Computing',
    address: '4 Research Park Drive',
    ref: 'O26',
    campus: 'Wallumattagal',
  },
  {
    id: 'math-physics',
    category: 'FACULTY_OF_SCIENCE_ENGINEERING',
    name: 'School of Mathematical & Physical Sciences',
    address: "12 Wally's Walk",
    ref: 'N20',
    campus: 'Wallumattagal',
  },
  {
    id: 'natural-sciences',
    category: 'FACULTY_OF_SCIENCE_ENGINEERING',
    name: 'School of Natural Sciences',
    address: "6 Wally's Walk",
    ref: 'M23',
    campus: 'Wallumattagal',
  },

  // VENUES
  {
    id: 'ainsworth',
    category: 'VENUES',
    name: 'Ainsworth Building (Teaching)',
    address: "1 Wally's Walk",
    ref: 'N27',
    campus: 'Wallumattagal',
  },
  {
    id: 'graduation-venue',
    category: 'VENUES',
    name: 'Graduation Venue',
    address: '1 Central Courtyard',
    ref: 'K18',
    campus: 'Wallumattagal',
  },
  {
    id: 'lighthouse-theatre',
    category: 'VENUES',
    name: 'Lighthouse Theatre (Performance)',
    address: '11 Gymnasium Road',
    ref: 'H14',
    campus: 'Wallumattagal',
  },
  {
    id: 'lotus-theatre',
    category: 'VENUES',
    name: 'Lotus Theatre (Teaching & Entertainment)',
    address: "27 Wally's Walk",
    ref: 'O11',
    campus: 'Wallumattagal',
  },
  {
    id: 'macquarie-theatre',
    category: 'VENUES',
    name: 'Macquarie Theatre (Teaching & Entertainment)',
    address: "21 Wally's Walk",
    ref: 'O15',
    campus: 'Wallumattagal',
  },
  {
    id: 'kirby-law',
    category: 'VENUES',
    name: 'Michael Kirby Law Building (Teaching)',
    address: "17 Wally's Walk",
    ref: 'O19',
    campus: 'Wallumattagal',
  },
  {
    id: 'price-theatre',
    category: 'VENUES',
    name: 'Price Theatre (Teaching)',
    address: "23 Wally's Walk",
    ref: 'O14',
    campus: 'Wallumattagal',
  },

  // ART GALLERY & MUSEUMS
  {
    id: 'art-gallery',
    category: 'ART_GALLERY_MUSEUMS',
    name: 'Art Gallery',
    address: '19 Eastern Road',
    ref: 'H20',
    campus: 'Wallumattagal',
  },
  {
    id: 'biology-discovery',
    category: 'ART_GALLERY_MUSEUMS',
    name: 'Biology Discovery Centre',
    address: '6 Science Road',
    ref: 'L23',
    campus: 'Wallumattagal',
  },
  {
    id: 'herbarium',
    category: 'ART_GALLERY_MUSEUMS',
    name: 'Herbarium',
    address: "6 Wally's Walk",
    ref: 'M23',
    campus: 'Wallumattagal',
  },
  {
    id: 'lachlan-macquarie-room',
    category: 'ART_GALLERY_MUSEUMS',
    name: 'Lachlan Macquarie Room',
    address: '16 Macquarie Walk',
    ref: 'Q17',
    campus: 'Wallumattagal',
  },
  {
    id: 'sporting-hall-fame',
    category: 'ART_GALLERY_MUSEUMS',
    name: 'Sporting Hall of Fame Museum',
    address: '10 Gymnasium Road',
    ref: 'J12',
    campus: 'Wallumattagal',
  },
  {
    id: 'gale-history-museum',
    category: 'ART_GALLERY_MUSEUMS',
    name: 'The Gale History Museum',
    address: "25C Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },

  // FOOD, BEVERAGE & RETAIL
  {
    id: 'crunch-cafe',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: 'Crunch Cafe',
    address: '10 Gymnasium Road',
    ref: 'J12',
    campus: 'Wallumattagal',
  },
  {
    id: 'cult-eatery',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: 'Cult Eatery',
    address: "25B Wally's Walk",
    ref: 'O13',
    campus: 'Wallumattagal',
  },
  {
    id: 'esc-cafe',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: 'Esc Cafe',
    address: '4 Research Park Drive',
    ref: 'O26',
    campus: 'Wallumattagal',
  },
  {
    id: 'lachlans-restaurant',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: "Lachlan's Restaurant",
    address: '1 Executive Road',
    ref: 'E23',
    campus: 'Wallumattagal',
  },
  {
    id: 'library-cafe',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: 'Library Cafe',
    address: '16 Macquarie Walk',
    ref: 'Q17',
    campus: 'Wallumattagal',
  },
  {
    id: 'ubar',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: 'UBar',
    address: '1 Central Courtyard',
    ref: 'K18',
    campus: 'Wallumattagal',
  },
  {
    id: 'wallys-coffee',
    category: 'FOOD_BEVERAGE_RETAIL',
    name: "Wally's Coffee and Toasties",
    address: "18 Wally's Walk",
    ref: 'N15',
    campus: 'Wallumattagal',
  },

  // MQ HEALTH
  {
    id: 'gp-physio',
    category: 'MQ_HEALTH',
    name: 'GP & Physiotherapy Clinics',
    address: '2 Technology Place',
    ref: 'K26',
    campus: 'Wallumattagal',
  },
  {
    id: 'hospital',
    category: 'MQ_HEALTH',
    name: 'Hospital',
    address: '3 Technology Place',
    ref: 'L27',
    campus: 'Wallumattagal',
  },
  {
    id: 'medical-imaging',
    category: 'MQ_HEALTH',
    name: 'Macquarie Medical Imaging (MMI)',
    address: '3 Technology Place',
    ref: 'L27',
    campus: 'Wallumattagal',
  },
  {
    id: 'pharmacy',
    category: 'MQ_HEALTH',
    name: 'Pharmacy (Hospital)',
    address: '3 Technology Place',
    ref: 'L27',
    campus: 'Wallumattagal',
  },
  {
    id: 'specialist-clinics',
    category: 'MQ_HEALTH',
    name: 'Specialist Clinics',
    address: '2 Technology Place',
    ref: 'K26',
    campus: 'Wallumattagal',
  },
  {
    id: 'speech-hearing',
    category: 'MQ_HEALTH',
    name: 'Speech & Hearing Clinic',
    address: '16 University Avenue',
    ref: 'T14',
    campus: 'Wallumattagal',
  },
  {
    id: 'woolcock',
    category: 'MQ_HEALTH',
    name: 'Woolcock Institute of Medical Research',
    address: '2 Innovation Road',
    ref: 'O30',
    campus: 'Wallumattagal',
  },

  // OTHER SERVICES
  {
    id: 'chaplaincy',
    category: 'OTHER_SERVICES',
    name: 'Chaplaincy',
    address: '10 Hadenfeld Avenue',
    ref: 'R6',
    campus: 'Wallumattagal',
  },
  {
    id: 'childcare-banksia',
    category: 'OTHER_SERVICES',
    name: 'Childcare (Banksia Cottage)',
    address: '8 Link Road',
    ref: 'P8',
    campus: 'Wallumattagal',
  },
  {
    id: 'childcare-gumnut',
    category: 'OTHER_SERVICES',
    name: 'Childcare (Gumnut Cottage)',
    address: '17 University Avenue',
    ref: 'V15',
    campus: 'Wallumattagal',
  },
  {
    id: 'childcare-miamia',
    category: 'OTHER_SERVICES',
    name: 'Childcare (Mia Mia)',
    address: "29 Wally's Walk",
    ref: 'N11',
    campus: 'Wallumattagal',
  },
  {
    id: 'childcare-waratah',
    category: 'OTHER_SERVICES',
    name: 'Childcare (Waratah)',
    address: '11 University Avenue',
    ref: 'W17',
    campus: 'Wallumattagal',
  },
  {
    id: 'chiro-clinic',
    category: 'OTHER_SERVICES',
    name: 'Chiropractic Clinic',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'future-students',
    category: 'OTHER_SERVICES',
    name: 'Future Students',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'grad-research',
    category: 'OTHER_SERVICES',
    name: 'Graduate Research Academy',
    address: "16 Wally's Walk",
    ref: 'N18',
    campus: 'Wallumattagal',
  },
  {
    id: 'graduation-unit',
    category: 'OTHER_SERVICES',
    name: 'Graduation Unit',
    address: '12 Second Way',
    ref: 'P16',
    campus: 'Wallumattagal',
  },
  {
    id: 'library',
    category: 'OTHER_SERVICES',
    name: 'Library (Waranara Library)',
    address: '16 Macquarie Walk',
    ref: 'Q17',
    campus: 'Wallumattagal',
  },
  {
    id: 'mq-college',
    category: 'OTHER_SERVICES',
    name: 'Macquarie University College',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'incubator',
    category: 'OTHER_SERVICES',
    name: 'Macquarie University Incubator',
    address: '8 Hadenfeld Avenue',
    ref: 'S8',
    campus: 'Wallumattagal',
  },
  {
    id: 'mets',
    category: 'OTHER_SERVICES',
    name: 'METS (Macquarie Engineering Technical Services)',
    address: '3 Science Road',
    ref: 'K24',
    campus: 'Wallumattagal',
  },
  {
    id: 'mindspot',
    category: 'OTHER_SERVICES',
    name: 'Mindspot',
    address: '75 Talavera Road',
    ref: 'M28',
    campus: 'Wallumattagal',
  },
  {
    id: 'mq-academy',
    category: 'OTHER_SERVICES',
    name: 'MQ Academy',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'observatory',
    category: 'OTHER_SERVICES',
    name: 'Observatory (Astronomy)',
    address: '5 Gymnasium Road',
    ref: 'C12',
    campus: 'Wallumattagal',
  },
  {
    id: 'commercialisation',
    category: 'OTHER_SERVICES',
    name: 'Office of Commercialisation and Innovation',
    address: "16 Wally's Walk",
    ref: 'N18',
    campus: 'Wallumattagal',
  },
  {
    id: 'prayer-room',
    category: 'OTHER_SERVICES',
    name: 'Prayer Room',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'research-services',
    category: 'OTHER_SERVICES',
    name: 'Research Services',
    address: "16 Wally's Walk",
    ref: 'N18',
    campus: 'Wallumattagal',
  },
  {
    id: 'sport-aquatic',
    category: 'OTHER_SERVICES',
    name: 'Sport & Aquatic Centre',
    address: '10 Gymnasium Road',
    ref: 'J12',
    campus: 'Wallumattagal',
  },
  {
    id: 'student-engagement',
    category: 'OTHER_SERVICES',
    name: 'Student Engagement',
    address: '12 Second Way',
    ref: 'P16',
    campus: 'Wallumattagal',
  },
  {
    id: 'student-services',
    category: 'OTHER_SERVICES',
    name: 'Student Services',
    address: "18 Wally's Walk",
    ref: 'N16',
    campus: 'Wallumattagal',
  },
  {
    id: 'walanga-muru',
    category: 'OTHER_SERVICES',
    name: 'Walanga Muru',
    address: "29 Wally's Walk",
    ref: 'N11',
    campus: 'Wallumattagal',
  },

  // OTHER LOCATIONS
  {
    id: 'dunmore-lang',
    category: 'OTHER_LOCATIONS',
    name: 'Dunmore Lang College',
    address: '130 Herring Road',
    ref: 'W25',
    campus: 'Wallumattagal',
  },
  {
    id: 'ielts-pte',
    category: 'OTHER_LOCATIONS',
    name: 'IELTS / PTE Test Centre',
    address: '8 Sir Christopher Ondaatje Ave',
    ref: 'P20',
    campus: 'Wallumattagal',
  },
  {
    id: 'mq-village',
    category: 'OTHER_LOCATIONS',
    name: 'Macquarie University Village',
    address: '122 Culloden Road',
    ref: 'F7',
    campus: 'Wallumattagal',
  },
  {
    id: 'nextsense-excellence',
    category: 'OTHER_LOCATIONS',
    name: 'NextSense Centre of Excellence',
    address: '2 Gymnasium Road',
    ref: 'F9',
    campus: 'Wallumattagal',
  },
  {
    id: 'nextsense-school',
    category: 'OTHER_LOCATIONS',
    name: 'NextSense School',
    address: '131 Culloden Road',
    ref: 'G7',
    campus: 'Wallumattagal',
  },
  {
    id: 'robert-menzies',
    category: 'OTHER_LOCATIONS',
    name: 'Robert Menzies College',
    address: '136 Herring Road',
    ref: 'V26',
    campus: 'Wallumattagal',
  },
  {
    id: 'sports-fields',
    category: 'OTHER_LOCATIONS',
    name: 'Sports Fields & Tennis Centre',
    address: '15-17 Gymnasium Road',
    ref: 'K16',
    campus: 'Wallumattagal',
  },
];

// Helper functions
export const getLocationsByCategory = (category: LocationCategory): CampusLocation[] => {
  return campusLocations.filter((loc) => loc.category === category);
};

export const getLocationById = (id: string): CampusLocation | undefined => {
  return campusLocations.find((loc) => loc.id === id);
};

export const searchLocations = (query: string): CampusLocation[] => {
  const lowerQuery = query.toLowerCase();
  return campusLocations.filter(
    (loc) =>
      loc.name.toLowerCase().includes(lowerQuery) ||
      loc.address.toLowerCase().includes(lowerQuery) ||
      loc.ref.toLowerCase().includes(lowerQuery),
  );
};

export const LOCATION_CATEGORY_LABELS: Record<LocationCategory, string> = {
  KEY_LOCATIONS: 'Key Locations',
  ADMINISTRATION: 'Administration',
  FACULTY_OF_ARTS: 'Faculty of Arts',
  MACQUARIE_BUSINESS_SCHOOL: 'Macquarie Business School',
  FACULTY_OF_MEDICINE_HEALTH_HUMAN_SCIENCES: 'Faculty of Medicine, Health & Human Sciences',
  FACULTY_OF_SCIENCE_ENGINEERING: 'Faculty of Science & Engineering',
  VENUES: 'Venues',
  ART_GALLERY_MUSEUMS: 'Art Gallery & Museums',
  FOOD_BEVERAGE_RETAIL: 'Food, Beverage & Retail',
  MQ_HEALTH: 'MQ Health',
  OTHER_SERVICES: 'Other Services',
  OTHER_LOCATIONS: 'Other Locations',
};
